using Moq;
using RedShirt.Example.Api.Core.UseCases.Product.Queries.SearchRecords;
using RedShirt.Example.Api.DataStores.Product.Core.Models;
using RedShirt.Example.Api.DataStores.Product.Core.Services;

namespace RedShirt.Example.Api.Core.UnitTests.Tests.UseCases.Product.Queries.SearchRecords;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class SearchProductRecordsQueryHandlerTests
{
    private static ProductInternalDto CreateInternalRecord(Guid? id = null, decimal price = 12.50m)
    {
        var created = DateTime.UtcNow.AddDays(-1);
        return new ProductInternalDto
        {
            Id = id ?? Guid.NewGuid(),
            CreatedAtUtc = created,
            UpdatedAtUtc = created,
            Sku = "SKU-1",
            Name = "Widget",
            Price = price
        };
    }

    [Fact]
    public async Task Handle_MapsQueryToServiceRequest_AndReturnsPublicDtos()
    {
        var continuation = Guid.NewGuid();
        var internalRecord = CreateInternalRecord(price: 42.00m);
        ProductServiceSearchRequest? capturedRequest = null;
        var productService = new Mock<IProductService>();
        productService
            .Setup(s => s.SearchAsync(
                It.IsAny<ProductServiceSearchRequest>(),
                continuation,
                TestContext.Current.CancellationToken))
            .Callback<ProductServiceSearchRequest, Guid?, CancellationToken>((request, _, _) =>
                capturedRequest = request)
            .ReturnsAsync(new ProductServiceSearchResponse
            {
                ContinuationToken = continuation,
                Records = [internalRecord]
            });
        var handler = new SearchProductRecordsQueryHandler(productService.Object);
        var createdBefore = DateTime.UtcNow.AddDays(-7);
        var createdAfter = DateTime.UtcNow.AddDays(-14);

        var result = await handler.Handle(
            new SearchProductRecordsQuery(
                25,
                createdBefore,
                createdAfter,
                null,
                null,
                "SKU-1",
                "SKU",
                "Widget",
                "Wid",
                "10.00",
                "5.50",
                "99.99",
                continuation),
            TestContext.Current.CancellationToken);

        Assert.NotNull(capturedRequest);
        Assert.Equal(25, capturedRequest!.PageSize);
        Assert.Equal(createdBefore, capturedRequest.CreatedBeforeUtc);
        Assert.Equal(createdAfter, capturedRequest.CreatedAfterUtc);
        Assert.Equal("SKU-1", capturedRequest.Sku);
        Assert.Equal("SKU", capturedRequest.SkuContains);
        Assert.Equal("Widget", capturedRequest.Name);
        Assert.Equal("Wid", capturedRequest.NameContains);
        Assert.Equal(10.00m, capturedRequest.Price);
        Assert.Equal(5.50m, capturedRequest.PriceGreaterThan);
        Assert.Equal(99.99m, capturedRequest.PriceLessThan);
        Assert.Equal(continuation, result.ContinuationToken);
        Assert.Single(result.Records);
        Assert.Equal(internalRecord.Id, result.Records[0].Id);
        Assert.Equal("42.00", result.Records[0].Price);
        productService.Verify(s => s.SearchAsync(
            It.IsAny<ProductServiceSearchRequest>(),
            continuation,
            TestContext.Current.CancellationToken), Times.Once);
    }

    [Fact]
    public async Task Handle_PassesNullDecimalFilters_WhenPriceStringsAreBlank()
    {
        ProductServiceSearchRequest? capturedRequest = null;
        var productService = new Mock<IProductService>();
        productService
            .Setup(s => s.SearchAsync(
                It.IsAny<ProductServiceSearchRequest>(),
                null,
                TestContext.Current.CancellationToken))
            .Callback<ProductServiceSearchRequest, Guid?, CancellationToken>((request, _, _) =>
                capturedRequest = request)
            .ReturnsAsync(new ProductServiceSearchResponse
            {
                ContinuationToken = null,
                Records = []
            });
        var handler = new SearchProductRecordsQueryHandler(productService.Object);

        await handler.Handle(
            new SearchProductRecordsQuery(
                10,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                " ",
                null,
                "",
                null),
            TestContext.Current.CancellationToken);

        Assert.NotNull(capturedRequest);
        Assert.Null(capturedRequest!.Price);
        Assert.Null(capturedRequest.PriceGreaterThan);
        Assert.Null(capturedRequest.PriceLessThan);
    }
}