using Moq;
using RedShirt.Example.Api.Common.Exceptions.Responses;
using RedShirt.Example.Api.DataStores.Order.Models;
using RedShirt.Example.Api.DataStores.Order.Models.Generated;

namespace RedShirt.Example.Api.DataStores.Order.UnitTests.Tests.Services;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class OrderServiceTests
{
    private static OrderDto CreateDto(
        Guid? id = null,
        Guid? customerId = null,
        string status = "Pending",
        string totalAmount = "10.00",
        string? totalPrice = null,
        DateTime? createdAtUtc = null,
        DateTime? updatedAtUtc = null)
    {
        var created = createdAtUtc ?? DateTime.UtcNow.AddDays(-1);
        return new OrderDto
        {
            Id = id ?? Guid.NewGuid(),
            CreatedAtUtc = created,
            UpdatedAtUtc = updatedAtUtc ?? created,
            CustomerId = customerId ?? Guid.NewGuid(),
            Status = status,
            TotalAmount = totalAmount,
            TotalPrice = totalPrice
        };
    }

    private static OrderService CreateService(IOrderRepository? repository = null)
    {
        return new OrderService(repository ?? new Mock<IOrderRepository>().Object);
    }

    [Fact]
    public async Task DeleteAsync_Completes_WhenRepositoryReturnsTrue()
    {
        var id = Guid.NewGuid();
        var repository = new Mock<IOrderRepository>();
        repository
            .Setup(r => r.DeleteAsync(id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(true);
        var service = CreateService(repository.Object);

        await service.DeleteAsync(id, TestContext.Current.CancellationToken);

        repository.Verify(r => r.DeleteAsync(id, TestContext.Current.CancellationToken), Times.Once);
    }

    [Fact]
    public async Task DeleteAsync_ThrowsResourceNotFound_WhenRepositoryReturnsFalse()
    {
        var id = Guid.NewGuid();
        var repository = new Mock<IOrderRepository>();
        repository
            .Setup(r => r.DeleteAsync(id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(false);
        var service = CreateService(repository.Object);

        await Assert.ThrowsAsync<ResourceNotFoundException>(() =>
            service.DeleteAsync(id, TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task GetByIdAsync_ReturnsDto_WhenFound()
    {
        var dto = CreateDto();
        var repository = new Mock<IOrderRepository>();
        repository
            .Setup(r => r.GetByIdAsync(dto.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(dto);
        var service = CreateService(repository.Object);

        var result = await service.GetByIdAsync(dto.Id, TestContext.Current.CancellationToken);

        Assert.Same(dto, result);
    }

    [Fact]
    public async Task GetByIdAsync_ThrowsResourceNotFound_WhenMissing()
    {
        var id = Guid.NewGuid();
        var repository = new Mock<IOrderRepository>();
        repository
            .Setup(r => r.GetByIdAsync(id, It.IsAny<CancellationToken>()))
            .ReturnsAsync((OrderDto?) null);
        var service = CreateService(repository.Object);

        await Assert.ThrowsAsync<ResourceNotFoundException>(() =>
            service.GetByIdAsync(id, TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task PatchAsync_MergesFields_AndUpserts()
    {
        var existing = CreateDto(status: "Pending", totalAmount: "10.00");
        var repository = new Mock<IOrderRepository>();
        repository
            .Setup(r => r.GetByIdAsync(existing.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(existing);
        repository
            .Setup(r => r.UpsertAsync(It.IsAny<OrderDto>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((OrderDto item, CancellationToken _) => item);
        var service = CreateService(repository.Object);

        var result = await service.PatchAsync(new OrderServicePatchRequest
        {
            Id = existing.Id,
            CustomerId = null,
            Status = "Shipped",
            TotalAmount = null,
            TotalPrice = null,
            ClearTotalPrice = null
        }, TestContext.Current.CancellationToken);

        Assert.Equal("Shipped", result.Status);
        Assert.Equal(existing.CustomerId, result.CustomerId);
        Assert.Equal(existing.TotalAmount, result.TotalAmount);
        Assert.Equal(existing.CreatedAtUtc, result.CreatedAtUtc);
    }

    [Fact]
    public async Task PatchAsync_ThrowsNoChanges_WhenNoFieldsProvided()
    {
        var service = CreateService();

        await Assert.ThrowsAsync<NoChangesToModifyException>(() =>
            service.PatchAsync(new OrderServicePatchRequest
            {
                Id = Guid.NewGuid(),
                CustomerId = null,
                Status = null,
                TotalAmount = null,
                TotalPrice = null,
                ClearTotalPrice = null
            }, TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task PatchAsync_ThrowsResourceNotFound_WhenMissing()
    {
        var id = Guid.NewGuid();
        var repository = new Mock<IOrderRepository>();
        repository
            .Setup(r => r.GetByIdAsync(id, It.IsAny<CancellationToken>()))
            .ReturnsAsync((OrderDto?) null);
        var service = CreateService(repository.Object);

        await Assert.ThrowsAsync<ResourceNotFoundException>(() =>
            service.PatchAsync(new OrderServicePatchRequest
            {
                Id = id,
                CustomerId = null,
                Status = "Cancelled",
                TotalAmount = null,
                TotalPrice = null,
                ClearTotalPrice = null
            }, TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task PostAsync_ThrowsBadRequest_WhenStatusEmpty()
    {
        var service = CreateService();

        var exception = await Assert.ThrowsAsync<BadRequestException>(() =>
            service.PostAsync(new OrderServicePostRequest
            {
                CustomerId = Guid.NewGuid(),
                Status = " ",
                TotalAmount = "1.00",
                TotalPrice = null
            }, TestContext.Current.CancellationToken));

        Assert.Equal("Status cannot be empty.", exception.Message);
    }

    [Fact]
    public async Task PostAsync_ThrowsBadRequest_WhenTotalAmountEmpty()
    {
        var service = CreateService();

        var exception = await Assert.ThrowsAsync<BadRequestException>(() =>
            service.PostAsync(new OrderServicePostRequest
            {
                CustomerId = Guid.NewGuid(),
                Status = "Pending",
                TotalAmount = "",
                TotalPrice = null
            }, TestContext.Current.CancellationToken));

        Assert.Equal("TotalAmount cannot be empty.", exception.Message);
    }

    [Fact]
    public async Task PostAsync_UpsertsNewDto()
    {
        var customerId = Guid.NewGuid();
        var repository = new Mock<IOrderRepository>();
        repository
            .Setup(r => r.UpsertAsync(It.IsAny<OrderDto>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((OrderDto item, CancellationToken _) => item);
        var service = CreateService(repository.Object);

        var result = await service.PostAsync(new OrderServicePostRequest
        {
            CustomerId = customerId,
            Status = "Pending",
            TotalAmount = "42.00",
            TotalPrice = null
        }, TestContext.Current.CancellationToken);

        Assert.NotEqual(Guid.Empty, result.Id);
        Assert.Equal(customerId, result.CustomerId);
        Assert.Equal("Pending", result.Status);
        Assert.Equal("42.00", result.TotalAmount);
    }

    [Fact]
    public async Task PutAsync_PreservesCreatedAt_WhenUpdatingExisting()
    {
        var createdAt = DateTime.UtcNow.AddDays(-5);
        var existing = CreateDto(createdAtUtc: createdAt, updatedAtUtc: createdAt);
        var repository = new Mock<IOrderRepository>();
        repository
            .Setup(r => r.GetByIdAsync(existing.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(existing);
        repository
            .Setup(r => r.UpsertAsync(It.IsAny<OrderDto>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((OrderDto item, CancellationToken _) => item);
        var service = CreateService(repository.Object);

        var result = await service.PutAsync(new OrderServicePutRequest
        {
            Id = existing.Id,
            CustomerId = existing.CustomerId,
            Status = "Shipped",
            TotalAmount = "99.00",
            TotalPrice = existing.TotalPrice
        }, TestContext.Current.CancellationToken);

        Assert.Equal(createdAt, result.CreatedAtUtc);
        Assert.Equal("Shipped", result.Status);
        Assert.Equal("99.00", result.TotalAmount);
    }

    [Fact]
    public async Task PutAsync_ThrowsNoChanges_WhenExistingMatches()
    {
        var existing = CreateDto();
        var repository = new Mock<IOrderRepository>();
        repository
            .Setup(r => r.GetByIdAsync(existing.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(existing);
        var service = CreateService(repository.Object);

        await Assert.ThrowsAsync<NoChangesToModifyException>(() =>
            service.PutAsync(new OrderServicePutRequest
            {
                Id = existing.Id,
                CustomerId = existing.CustomerId,
                Status = existing.Status,
                TotalAmount = existing.TotalAmount,
                TotalPrice = existing.TotalPrice
            }, TestContext.Current.CancellationToken));

        repository.Verify(r => r.UpsertAsync(It.IsAny<OrderDto>(), It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task SearchAsync_DelegatesToRepository()
    {
        var parameters = new OrderServiceSearchRequest
        {
            PageSize = 10,
            CreatedBeforeUtc = null,
            CreatedAfterUtc = null,
            UpdatedBeforeUtc = null,
            UpdatedAfterUtc = null,
            CustomerId = Guid.NewGuid(),
            Status = "Pending",
            StatusContains = null,
            TotalAmount = null,
            TotalAmountGreaterThan = null,
            TotalAmountLessThan = null,
            TotalPrice = null,
            TotalPriceGreaterThan = null,
            TotalPriceLessThan = null,
            TotalPriceIsNull = false
        };
        var continuation = Guid.NewGuid();
        var expected = new OrderSearchResponse
        {
            ContinuationToken = null,
            Records = [CreateDto()]
        };
        var repository = new Mock<IOrderRepository>();
        repository
            .Setup(r => r.SearchAsync(parameters, continuation, It.IsAny<CancellationToken>()))
            .ReturnsAsync(expected);
        var service = CreateService(repository.Object);

        var result = await service.SearchAsync(parameters, continuation, TestContext.Current.CancellationToken);

        Assert.Same(expected, result);
    }
}