using Microsoft.AspNetCore.Mvc;
using Moq;
using RedShirt.Example.Api.Controllers;
using RedShirt.Example.Api.Common.Exceptions.Responses;
using RedShirt.Example.Api.Core.UseCases.ExampleItem.Commands.Create;
using RedShirt.Example.Api.Core.UseCases.ExampleItem.Commands.Delete;
using RedShirt.Example.Api.Core.UseCases.ExampleItem.Models;
using RedShirt.Example.Api.Core.UseCases.ExampleItem.Queries.GetRecord;
using RedShirt.Example.Api.Core.UseCases.ExampleItem.Queries.ListRecords;
using RedShirt.Example.Api.Models.ExampleItem;

namespace RedShirt.Example.Api.UnitTests.Tests.Controllers;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class ExampleItemControllerTests
{
    private readonly ExampleItemController _controller = new();

    [Fact]
    public async Task Delete_PropagatesBadRequestException()
    {
        var deleteHandler = new Mock<IDeleteExampleItemCommandHandler>();
        deleteHandler
            .Setup(h => h.Handle(It.IsAny<DeleteExampleItemCommand>(), It.IsAny<CancellationToken>()))
            .ThrowsAsync(new BadRequestException("Name is required"));

        var exception = await Assert.ThrowsAsync<BadRequestException>(() =>
            _controller.Delete(" ", deleteHandler.Object, TestContext.Current.CancellationToken));

        Assert.Equal("Name is required", exception.Message);
    }

    [Fact]
    public async Task Delete_PropagatesResourceNotFoundException()
    {
        var deleteHandler = new Mock<IDeleteExampleItemCommandHandler>();
        deleteHandler
            .Setup(h => h.Handle(It.IsAny<DeleteExampleItemCommand>(), It.IsAny<CancellationToken>()))
            .ThrowsAsync(new ResourceNotFoundException());

        await Assert.ThrowsAsync<ResourceNotFoundException>(() =>
            _controller.Delete("missing", deleteHandler.Object, TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task Delete_ReturnsOk_WhenCommandSucceeds()
    {
        var deleteHandler = new Mock<IDeleteExampleItemCommandHandler>();
        deleteHandler
            .Setup(h => h.Handle(It.Is<DeleteExampleItemCommand>(c => c.Name == "widget"),
                It.IsAny<CancellationToken>()))
            .Returns(Task.CompletedTask);

        var result = await _controller.Delete("widget", deleteHandler.Object,
            TestContext.Current.CancellationToken);

        Assert.IsType<OkResult>(result);
        deleteHandler.Verify(h => h.Handle(It.Is<DeleteExampleItemCommand>(c => c.Name == "widget"),
            It.IsAny<CancellationToken>()), Times.Once);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("token-1")]
    public async Task GetList_ReturnsOkWithList_AndPassesContinuationToken(string? continuationToken)
    {
        var expected = new ExampleItemListModel
        {
            ContinuationToken = "next",
            Items = [new ExampleItemModel {Name = "a"}]
        };
        var listHandler = new Mock<IListExampleItemRecordsQueryHandler>();
        listHandler
            .Setup(h => h.Handle(
                It.Is<ListExampleItemRecordsQuery>(q => q.ContinuationToken == continuationToken),
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(expected);

        var result = await _controller.GetList(continuationToken, listHandler.Object,
            TestContext.Current.CancellationToken);

        var ok = Assert.IsType<OkObjectResult>(result);
        Assert.Same(expected, ok.Value);
        listHandler.Verify(h => h.Handle(
            It.Is<ListExampleItemRecordsQuery>(q => q.ContinuationToken == continuationToken),
            It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task Get_PropagatesBadRequestException()
    {
        var getHandler = new Mock<IGetExampleItemRecordQueryHandler>();
        getHandler
            .Setup(h => h.Handle(It.IsAny<GetExampleItemRecordQuery>(), It.IsAny<CancellationToken>()))
            .ThrowsAsync(new BadRequestException("Name is required"));

        var exception = await Assert.ThrowsAsync<BadRequestException>(() =>
            _controller.Get(" ", getHandler.Object, TestContext.Current.CancellationToken));

        Assert.Equal("Name is required", exception.Message);
    }

    [Fact]
    public async Task Get_PropagatesResourceNotFoundException()
    {
        var getHandler = new Mock<IGetExampleItemRecordQueryHandler>();
        getHandler
            .Setup(h => h.Handle(It.IsAny<GetExampleItemRecordQuery>(), It.IsAny<CancellationToken>()))
            .ThrowsAsync(new ResourceNotFoundException());

        await Assert.ThrowsAsync<ResourceNotFoundException>(() =>
            _controller.Get("missing", getHandler.Object, TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task Get_ReturnsOkWithModel_WhenQuerySucceeds()
    {
        var expected = new ExampleItemModel {Name = "widget"};
        var getHandler = new Mock<IGetExampleItemRecordQueryHandler>();
        getHandler
            .Setup(h => h.Handle(It.Is<GetExampleItemRecordQuery>(q => q.Name == "widget"),
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(expected);

        var result = await _controller.Get("widget", getHandler.Object, TestContext.Current.CancellationToken);

        var ok = Assert.IsType<OkObjectResult>(result);
        Assert.Same(expected, ok.Value);
        getHandler.Verify(h => h.Handle(It.Is<GetExampleItemRecordQuery>(q => q.Name == "widget"),
            It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task Put_PropagatesBadRequestException()
    {
        var createHandler = new Mock<ICreateExampleItemCommandHandler>();
        createHandler
            .Setup(h => h.Handle(It.IsAny<CreateExampleItemCommand>(), It.IsAny<CancellationToken>()))
            .ThrowsAsync(new BadRequestException("Name is required"));
        var request = new ExampleItemPutRequest {Name = " "};

        var exception = await Assert.ThrowsAsync<BadRequestException>(() =>
            _controller.Put(request, "idem-1", createHandler.Object, TestContext.Current.CancellationToken));

        Assert.Equal("Name is required", exception.Message);
    }

    [Fact]
    public async Task Put_PropagatesConflictException()
    {
        var createHandler = new Mock<ICreateExampleItemCommandHandler>();
        createHandler
            .Setup(h => h.Handle(It.IsAny<CreateExampleItemCommand>(), It.IsAny<CancellationToken>()))
            .ThrowsAsync(new ConflictException(
                "An idempotent operation was requested while a previous instance of the same operation was in motion."));
        var request = new ExampleItemPutRequest {Name = "widget"};

        await Assert.ThrowsAsync<ConflictException>(() =>
            _controller.Put(request, "idem-1", createHandler.Object, TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task Put_ReturnsOkWithModel_WhenCommandSucceeds()
    {
        var expected = new ExampleItemModel {Name = "widget"};
        var createHandler = new Mock<ICreateExampleItemCommandHandler>();
        createHandler
            .Setup(h => h.Handle(
                It.Is<CreateExampleItemCommand>(c => c.Model.Name == "widget" && c.IdempotencyKey == "idem-1"),
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(expected);
        var request = new ExampleItemPutRequest {Name = "widget"};

        var result = await _controller.Put(request, "idem-1", createHandler.Object,
            TestContext.Current.CancellationToken);

        var ok = Assert.IsType<OkObjectResult>(result);
        Assert.Same(expected, ok.Value);
        createHandler.Verify(h => h.Handle(
            It.Is<CreateExampleItemCommand>(c => c.Model.Name == "widget" && c.IdempotencyKey == "idem-1"),
            It.IsAny<CancellationToken>()), Times.Once);
    }
}