using Microsoft.AspNetCore.Mvc;
using Moq;
using RedShirt.Example.Api.Controllers;
using RedShirt.Example.Api.Core.Exceptions;
using RedShirt.Example.Api.Core.Exceptions.Responses;
using RedShirt.Example.Api.Core.Models;
using RedShirt.Example.Api.Core.Services.Topics.ExampleItem;
using RedShirt.Example.Api.Models.ExampleItem;

namespace RedShirt.Example.Api.UnitTests.Tests.Controllers;

/// <summary>
/// Code generated by Cursor (Composer).
/// </summary>
public class ExampleItemControllerTests
{
    [Fact]
    public async Task Delete_ReturnsOk_WhenServiceSucceeds()
    {
        var service = new Mock<IExampleItemService>();
        service
            .Setup(s => s.DeleteAsync("widget", It.IsAny<CancellationToken>()))
            .Returns(Task.CompletedTask);
        var controller = new ExampleItemController(service.Object);

        var result = await controller.Delete("widget");

        Assert.IsType<OkResult>(result);
        service.Verify(s => s.DeleteAsync("widget", It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task Delete_ReturnsBadRequest_WhenServiceThrowsBadRequest()
    {
        var service = new Mock<IExampleItemService>();
        service
            .Setup(s => s.DeleteAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ThrowsAsync(new BadRequestException("Name is required"));
        var controller = new ExampleItemController(service.Object);

        var result = await controller.Delete(" ");

        var badRequest = Assert.IsType<BadRequestObjectResult>(result);
        Assert.Equal("Name is required", badRequest.Value);
    }

    [Fact]
    public async Task Delete_ReturnsNotFound_WhenServiceThrowsResourceNotFound()
    {
        var service = new Mock<IExampleItemService>();
        service
            .Setup(s => s.DeleteAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ThrowsAsync(new ResourceNotFoundException());
        var controller = new ExampleItemController(service.Object);

        var result = await controller.Delete("missing");

        Assert.IsType<NotFoundResult>(result);
    }

    [Fact]
    public async Task Get_ReturnsOkWithModel_WhenServiceSucceeds()
    {
        var expected = new ExampleItemModel { Name = "widget" };
        var service = new Mock<IExampleItemService>();
        service
            .Setup(s => s.GetAsync("widget", It.IsAny<CancellationToken>()))
            .ReturnsAsync(expected);
        var controller = new ExampleItemController(service.Object);

        var result = await controller.Get("widget");

        var ok = Assert.IsType<OkObjectResult>(result);
        Assert.Same(expected, ok.Value);
        service.Verify(s => s.GetAsync("widget", It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task Get_ReturnsBadRequest_WhenServiceThrowsBadRequest()
    {
        var service = new Mock<IExampleItemService>();
        service
            .Setup(s => s.GetAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ThrowsAsync(new BadRequestException("Name is required"));
        var controller = new ExampleItemController(service.Object);

        var result = await controller.Get(" ");

        var badRequest = Assert.IsType<BadRequestObjectResult>(result);
        Assert.Equal("Name is required", badRequest.Value);
    }

    [Fact]
    public async Task Get_ReturnsNotFound_WhenServiceThrowsResourceNotFound()
    {
        var service = new Mock<IExampleItemService>();
        service
            .Setup(s => s.GetAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ThrowsAsync(new ResourceNotFoundException());
        var controller = new ExampleItemController(service.Object);

        var result = await controller.Get("missing");

        Assert.IsType<NotFoundResult>(result);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("token-1")]
    public async Task GetList_ReturnsOkWithList_AndPassesContinuationToken(string? continuationToken)
    {
        var expected = new ExampleItemListModel
        {
            ContinuationToken = "next",
            Items = [new ExampleItemModel { Name = "a" }]
        };
        var service = new Mock<IExampleItemService>();
        service
            .Setup(s => s.GetListAsync(continuationToken, It.IsAny<CancellationToken>()))
            .ReturnsAsync(expected);
        var controller = new ExampleItemController(service.Object);

        var result = await controller.GetList(continuationToken);

        var ok = Assert.IsType<OkObjectResult>(result);
        Assert.Same(expected, ok.Value);
        service.Verify(s => s.GetListAsync(continuationToken, It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task Put_ReturnsOkWithModel_WhenServiceSucceeds()
    {
        var expected = new ExampleItemModel { Name = "widget" };
        var service = new Mock<IExampleItemService>();
        service
            .Setup(s => s.PutAsync(
                It.Is<ExampleItemModel>(m => m.Name == "widget"),
                "idem-1",
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(expected);
        var controller = new ExampleItemController(service.Object);
        var request = new ExampleItemPutRequest { Name = "widget" };

        var result = await controller.Put(request, "idem-1");

        var ok = Assert.IsType<OkObjectResult>(result);
        Assert.Same(expected, ok.Value);
        service.Verify(s => s.PutAsync(
            It.Is<ExampleItemModel>(m => m.Name == "widget"),
            "idem-1",
            It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task Put_ReturnsBadRequest_WhenServiceThrowsBadRequest()
    {
        var service = new Mock<IExampleItemService>();
        service
            .Setup(s => s.PutAsync(
                It.IsAny<ExampleItemModel>(),
                It.IsAny<string>(),
                It.IsAny<CancellationToken>()))
            .ThrowsAsync(new BadRequestException("Name is required"));
        var controller = new ExampleItemController(service.Object);
        var request = new ExampleItemPutRequest { Name = " " };

        var result = await controller.Put(request, "idem-1");

        var badRequest = Assert.IsType<BadRequestObjectResult>(result);
        Assert.Equal("Name is required", badRequest.Value);
    }

    [Fact]
    public async Task Put_ReturnsConflict_WhenServiceThrowsIdempotentConcurrency()
    {
        var service = new Mock<IExampleItemService>();
        service
            .Setup(s => s.PutAsync(
                It.IsAny<ExampleItemModel>(),
                It.IsAny<string>(),
                It.IsAny<CancellationToken>()))
            .ThrowsAsync(new IdempotentConcurrencyException());
        var controller = new ExampleItemController(service.Object);
        var request = new ExampleItemPutRequest { Name = "widget" };

        var result = await controller.Put(request, "idem-1");

        Assert.IsType<ConflictResult>(result);
    }
}
