using Microsoft.AspNetCore.Mvc;
using Moq;
using RedShirt.Example.Api.Authorization.ResourceScoping.Customer;
using RedShirt.Example.Api.Common.Exceptions.Responses;
using RedShirt.Example.Api.Controllers;
using RedShirt.Example.Api.Core.UseCases.Order.Commands.Delete;
using RedShirt.Example.Api.Core.UseCases.Order.Queries.GetRecord;
using RedShirt.Example.Api.Core.UseCases.Order.Queries.SearchRecords;
using RedShirt.Example.Api.DataStores.Order.Models;
using RedShirt.Example.Api.DataStores.Order.Models.Generated;
using RedShirt.Example.Api.Models.Order;
using System.Security.Claims;

namespace RedShirt.Example.Api.UnitTests.Tests.Controllers;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class OrderControllerTests
{
    private static readonly Guid OrderId = Guid.Parse("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa");
    private static readonly Guid CustomerId = Guid.Parse("11111111-1111-1111-1111-111111111111");

    private readonly OrderController _controller = new();

    private static OrderDto Order(Guid customerId)
    {
        return new OrderDto
        {
            Id = OrderId,
            CreatedAtUtc = DateTime.UtcNow,
            UpdatedAtUtc = DateTime.UtcNow,
            CustomerId = customerId,
            Status = "open",
            TotalAmount = "10.00",
            TotalPrice = null
        };
    }

    [Fact]
    public async Task Delete_DoesNotDelete_WhenResourceAuthorizationFails()
    {
        var getHandler = new Mock<IGetOrderRecordQueryHandler>();
        getHandler
            .Setup(handler => handler.Handle(It.IsAny<GetOrderRecordQuery>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(Order(CustomerId));
        var authorizer = new Mock<ICustomerScopedResourceEnforcer>();
        authorizer
            .Setup(a => a.EnsureCanAccessAsync(It.IsAny<ClaimsPrincipal>(), CustomerId))
            .ThrowsAsync(new ResourceNotFoundException());
        var deleteHandler = new Mock<IDeleteOrderCommandHandler>();

        await Assert.ThrowsAsync<ResourceNotFoundException>(() =>
            _controller.Delete(OrderId, getHandler.Object,
                authorizer.Object, deleteHandler.Object,
                TestContext.Current.CancellationToken));

        deleteHandler.Verify(
            handler => handler.Handle(It.IsAny<DeleteOrderCommand>(), It.IsAny<CancellationToken>()),
            Times.Never);
    }

    [Fact]
    public async Task Get_DoesNotReturnOrder_WhenResourceAuthorizationFails()
    {
        var getHandler = new Mock<IGetOrderRecordQueryHandler>();
        getHandler
            .Setup(handler => handler.Handle(It.IsAny<GetOrderRecordQuery>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(Order(CustomerId));
        var authorizer = new Mock<ICustomerScopedResourceEnforcer>();
        authorizer
            .Setup(a => a.EnsureCanAccessAsync(It.IsAny<ClaimsPrincipal>(), CustomerId))
            .ThrowsAsync(new ResourceNotFoundException());

        await Assert.ThrowsAsync<ResourceNotFoundException>(() =>
            _controller.Get(OrderId, getHandler.Object,
                authorizer.Object,
                TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task Get_ReturnsOk_AfterResourceAuthorization()
    {
        var expected = Order(CustomerId);
        var getHandler = new Mock<IGetOrderRecordQueryHandler>();
        getHandler
            .Setup(handler => handler.Handle(It.Is<GetOrderRecordQuery>(query => query.Id == OrderId),
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(expected);
        var authorizer = new Mock<ICustomerScopedResourceEnforcer>();

        var result = await _controller.Get(OrderId, getHandler.Object,
            authorizer.Object,
            TestContext.Current.CancellationToken);

        var ok = Assert.IsType<OkObjectResult>(result);
        Assert.Same(expected, ok.Value);
        authorizer.Verify(a => a.EnsureCanAccessAsync(It.IsAny<ClaimsPrincipal>(), CustomerId),
            Times.Once);
    }

    [Fact]
    public async Task Search_PassesConstrainedCustomerId()
    {
        var authorizer = new Mock<ICustomerScopedResourceEnforcer>();
        authorizer
            .Setup(a => a.ConstrainSearchCustomerId(It.IsAny<ClaimsPrincipal>(), null))
            .Returns(CustomerId);
        var expected = new OrderSearchResponse
        {
            ContinuationToken = null,
            Records = []
        };
        var searchHandler = new Mock<ISearchOrderRecordsQueryHandler>();
        searchHandler
            .Setup(handler => handler.Handle(
                It.Is<SearchOrderRecordsQuery>(query => query.CustomerId == CustomerId),
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(expected);

        var result = await _controller.Search(new OrderSearchRequest(),
            authorizer.Object, searchHandler.Object,
            TestContext.Current.CancellationToken);

        var ok = Assert.IsType<OkObjectResult>(result);
        Assert.Same(expected, ok.Value);
    }
}