using RedShirt.Example.Api.Common.Shared.Core.Services;

namespace RedShirt.Example.Api.Common.Shared.Implementation.InMemory.Services;

/// <summary>
///     In-memory implementation of a data cache.
///     This in-memory implementation was made to support other features such as idempotency support
///     while keeping this general template straightforward to use/test locally.
///     If you are applying this template to a production project, then
///     I would strongly encourage you to consider replacing this implementation
///     with a distributed system such as Redis that can allow multiple instances of this API to coordinate.
///     Code generated by Cursor (Composer).
/// </summary>
internal class InMemoryDataCacheService : IDataCacheService, IDisposable
{
    private static readonly TimeSpan CleanupInterval = TimeSpan.FromMinutes(1);
    private readonly Dictionary<string, CacheEntry> _cache = new();
    private readonly Timer _cleanupTimer;

    private readonly Lock _lock = new();

    private string? GetString(string key)
    {
        lock (_lock)
        {
            if (!_cache.TryGetValue(key, out var entry))
            {
                return null;
            }

            if (entry.ExpiresAt <= DateTimeOffset.UtcNow)
            {
                _cache.Remove(key);
                return null;
            }

            return entry.Value;
        }
    }

    private void SetString(string key, string value, TimeSpan expiration)
    {
        lock (_lock)
        {
            _cache[key] = new CacheEntry(value, DateTimeOffset.UtcNow.Add(expiration));
        }
    }

    private void CleanupExpiredEntries()
    {
        lock (_lock)
        {
            var now = DateTimeOffset.UtcNow;
            List<string>? expiredKeys = null;

            foreach (var (key, entry) in _cache)
            {
                if (entry.ExpiresAt > now)
                {
                    continue;
                }

                expiredKeys ??= [];
                expiredKeys.Add(key);
            }

            if (expiredKeys is null)
            {
                return;
            }

            foreach (var key in expiredKeys)
            {
                _cache.Remove(key);
            }
        }
    }

    public InMemoryDataCacheService()
    {
        _cleanupTimer = new Timer(_ => CleanupExpiredEntries(), null, CleanupInterval, CleanupInterval);
    }

    public Task<string?> GetStringAsync(string key)
    {
        return Task.FromResult(GetString(key));
    }

    public Task SetStringAsync(string key, string value, TimeSpan expiration)
    {
        SetString(key, value, expiration);
        return Task.CompletedTask;
    }

    public void Dispose()
    {
        _cleanupTimer.Dispose();
    }

    private sealed record CacheEntry(string Value, DateTimeOffset ExpiresAt);
}