using RedShirt.Example.Api.Common.Shared.Core.Abstractions;
using RedShirt.Example.Api.Common.Shared.Core.Services;

namespace RedShirt.Example.Api.Common.Shared.Implementation.InMemory.Services;

/// <summary>
///     In-memory implementation of a distributed-style lock.
///     This in-memory implementation was made to support other features such as idempotency support
///     while keeping this general template straightforward to use/test locally.
///     If you are applying this template to a production project, then
///     I would strongly encourage you to consider replacing this implementation
///     with a distributed approach such as using DistributedLock.Redis that would
///     allow multiple instances of this API to coordinate.
///     Code generated by Cursor (Composer).
/// </summary>
internal class InMemoryLockService : IAbstractedLockService
{
    private readonly HashSet<string> _heldKeys = [];
    private readonly Lock _lock = new();

    private IAbstractedLock GetLock(string key)
    {
        lock (_lock)
        {
            if (!_heldKeys.Add(key))
            {
                return new InMemoryLock(false, null);
            }

            return new InMemoryLock(true, () => Release(key));
        }
    }

    private void Release(string key)
    {
        lock (_lock)
        {
            _heldKeys.Remove(key);
        }
    }

    public Task<IAbstractedLock> GetLockAsync(string key)
    {
        return Task.FromResult(GetLock(key));
    }

    private sealed class InMemoryLock(bool isAcquired, Action? release) : IAbstractedLock
    {
        private int _unlocked;

        public bool IsAcquired { get; } = isAcquired;

        public void Unlock()
        {
            if (!IsAcquired)
            {
                return;
            }

            if (Interlocked.Exchange(ref _unlocked, 1) == 0)
            {
                release?.Invoke();
            }
        }
    }
}