using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using Moq;
using RedShirt.Example.Api.Common.SecretManagers.Core.Models;
using RedShirt.Example.Api.Common.SecretManagers.Core.Services;
using RedShirt.Example.Api.Connectors.Foo.Implementation.Exceptions;
using RedShirt.Example.Api.Connectors.Foo.Implementation.Services.Resilience;

namespace RedShirt.Example.Api.Connectors.Foo.Implementation.UnitTests.Tests.Services.Resilience;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class FooApiRequestHandlerRetryWrapperServiceTests
{
    private const string ApiKeyPath = "/foo/api-key";

    private static FooApiRequestHandlerRetryWrapperService CreateSut(
        ISecretManagerCacheService secretManager,
        int? cooldownSeconds = 60)
    {
        return new FooApiRequestHandlerRetryWrapperService(
            secretManager,
            NullLogger<FooApiRequestHandlerRetryWrapperService>.Instance,
            Options.Create(new FooApiRequestHandlerRetryWrapperService.ConfigurationModel
            {
                ApiKeyPath = ApiKeyPath,
                ApiKeyRefreshCooldownSeconds = cooldownSeconds
            }));
    }

    private static SecretManagerCacheSecretResponse Secret(string value, bool queried = true)
    {
        return new SecretManagerCacheSecretResponse
        {
            Value = value,
            QueriedSecretManager = queried
        };
    }

    [Fact]
    public async Task ExecuteAsync_RefreshesKey_AndRetriesOnce_OnFooUnauthorized()
    {
        var secrets = new Mock<ISecretManagerCacheService>(MockBehavior.Strict);
        secrets
            .Setup(s => s.GetSecretAsync(ApiKeyPath, It.IsAny<TimeSpan?>(), false,
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(Secret("old-key"));
        secrets
            .Setup(s => s.GetSecretAsync(ApiKeyPath, It.IsAny<TimeSpan?>(), true,
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(Secret("new-key"));

        var sut = CreateSut(secrets.Object, 1);
        await sut.GetApiKeyAsync(TestContext.Current.CancellationToken);

        // Leave the stability window so force-refresh is allowed.
        await Task.Delay(TimeSpan.FromMilliseconds(1100), TestContext.Current.CancellationToken);

        var attempts = 0;
        var result = await sut.ExecuteAsync(async ct =>
        {
            attempts++;
            var key = await sut.GetApiKeyAsync(ct);
            if (key == "old-key")
            {
                throw new FooUnauthorizedException();
            }

            return key;
        }, TestContext.Current.CancellationToken);

        Assert.Equal("new-key", result);
        Assert.Equal(2, attempts);
        secrets.Verify(
            s => s.GetSecretAsync(ApiKeyPath, It.IsAny<TimeSpan?>(), true, It.IsAny<CancellationToken>()),
            Times.Once);
    }

    [Fact]
    public async Task ExecuteAsync_Throws_WhenForceRefreshReturnsSameKey()
    {
        var secrets = new Mock<ISecretManagerCacheService>(MockBehavior.Strict);
        secrets
            .Setup(s => s.GetSecretAsync(ApiKeyPath, It.IsAny<TimeSpan?>(), It.IsAny<bool>(),
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(Secret("same-key"));

        var sut = CreateSut(secrets.Object, 1);
        await sut.GetApiKeyAsync(TestContext.Current.CancellationToken);
        await Task.Delay(TimeSpan.FromMilliseconds(1100), TestContext.Current.CancellationToken);

        await Assert.ThrowsAsync<FooUnauthorizedException>(() =>
            sut.ExecuteAsync<string>(_ => throw new FooUnauthorizedException(),
                TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task ExecuteAsync_Throws_WhenUnauthorizedDuringCooldown()
    {
        var secrets = new Mock<ISecretManagerCacheService>(MockBehavior.Strict);
        secrets
            .Setup(s => s.GetSecretAsync(ApiKeyPath, It.IsAny<TimeSpan?>(), false,
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(Secret("key-1"));

        var sut = CreateSut(secrets.Object, 120);
        await sut.GetApiKeyAsync(TestContext.Current.CancellationToken);

        await Assert.ThrowsAsync<FooUnauthorizedException>(() =>
            sut.ExecuteAsync<string>(_ => throw new FooUnauthorizedException(),
                TestContext.Current.CancellationToken));

        secrets.Verify(
            s => s.GetSecretAsync(ApiKeyPath, It.IsAny<TimeSpan?>(), true, It.IsAny<CancellationToken>()),
            Times.Never);
    }

    [Fact]
    public async Task GetApiKeyAsync_CachesSecret()
    {
        var secrets = new Mock<ISecretManagerCacheService>(MockBehavior.Strict);
        secrets
            .Setup(s => s.GetSecretAsync(ApiKeyPath, It.IsAny<TimeSpan?>(), false,
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(Secret("key-1"));

        var sut = CreateSut(secrets.Object);

        var first = await sut.GetApiKeyAsync(TestContext.Current.CancellationToken);
        var second = await sut.GetApiKeyAsync(TestContext.Current.CancellationToken);

        Assert.Equal("key-1", first);
        Assert.Equal("key-1", second);
        secrets.Verify(
            s => s.GetSecretAsync(ApiKeyPath, It.IsAny<TimeSpan?>(), false, It.IsAny<CancellationToken>()),
            Times.Once);
    }
}