using RedShirt.Example.Api.Common.SecretManagers.Core.Exceptions;
using RedShirt.Example.Api.Connectors.Foo.Core.Exceptions;
using RedShirt.Example.Api.Connectors.Foo.Implementation.Services.Resilience;
using System.Net;
using System.Net.Sockets;
using System.Text.Json;

namespace RedShirt.Example.Api.Connectors.Foo.Implementation.UnitTests.Tests.Services.Resilience;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class FooExceptionArbiterServiceTests
{
    private readonly FooExceptionArbiterService _sut = new();

    [Fact]
    public void GetReport_ApiSecretManagerException_IsAlreadyHandled()
    {
        var report = _sut.GetReport(new ApiSecretManagerException(new InvalidOperationException("ssm"))
        {
            IsHandled = true,
            CouldBeTransient = true,
            CouldBeExternallySolvable = true
        });

        Assert.True(report.AlreadyHandled);
        Assert.True(report.IsExpected);
    }

    [Fact]
    public void GetReport_FooConnectorException_IsAlreadyHandled()
    {
        var report = _sut.GetReport(new FooConnectorException("done")
        {
            IsHandled = true,
            CouldBeTransient = false,
            CouldBeExternallySolvable = true
        });

        Assert.True(report.AlreadyHandled);
        Assert.True(report.IsExpected);
        Assert.False(report.CouldBeTransient);
        Assert.True(report.CouldBeExternallySolvable);
    }

    [Fact]
    public void GetReport_FooRecordNotFound_IsExpectedNonTransient()
    {
        var report = _sut.GetReport(new FooRecordNotFoundException(1));

        Assert.False(report.AlreadyHandled);
        Assert.True(report.IsExpected);
        Assert.False(report.CouldBeTransient);
        Assert.False(report.CouldBeExternallySolvable);
    }

    [Fact]
    public void GetReport_FooUnauthorized_IsExpectedExternallySolvable()
    {
        var report = _sut.GetReport(new FooUnauthorizedException());

        Assert.False(report.AlreadyHandled);
        Assert.True(report.IsExpected);
        Assert.False(report.CouldBeTransient);
        Assert.True(report.CouldBeExternallySolvable);
    }

    [Fact]
    public void GetReport_Http404_IsExpectedNonTransient()
    {
        var report = _sut.GetReport(new HttpRequestException("missing", null, HttpStatusCode.NotFound));

        Assert.True(report.IsExpected);
        Assert.False(report.CouldBeTransient);
        Assert.True(report.CouldBeExternallySolvable);
    }

    [Fact]
    public void GetReport_Http503_IsTransient()
    {
        var report = _sut.GetReport(new HttpRequestException("boom", null, HttpStatusCode.ServiceUnavailable));

        Assert.True(report.IsExpected);
        Assert.True(report.CouldBeTransient);
        Assert.True(report.CouldBeExternallySolvable);
    }

    [Fact]
    public void GetReport_HttpWithoutStatus_IsTransient()
    {
        var report = _sut.GetReport(new HttpRequestException("connection refused"));

        Assert.True(report.IsExpected);
        Assert.True(report.CouldBeTransient);
    }

    [Fact]
    public void GetReport_JsonException_IsExpectedNonTransient()
    {
        var report = _sut.GetReport(new JsonException("bad payload"));

        Assert.True(report.IsExpected);
        Assert.False(report.CouldBeTransient);
    }

    [Fact]
    public void GetReport_SocketException_IsTransient()
    {
        var report = _sut.GetReport(new SocketException());

        Assert.True(report.IsExpected);
        Assert.True(report.CouldBeTransient);
    }

    [Fact]
    public void GetReport_UnknownException_IsUnexpected()
    {
        var report = _sut.GetReport(new InvalidOperationException("surprise"));

        Assert.False(report.AlreadyHandled);
        Assert.False(report.IsExpected);
        Assert.False(report.CouldBeTransient);
        Assert.False(report.CouldBeExternallySolvable);
    }

    [Fact]
    public void GetReport_UnwrapsSingleAggregateException()
    {
        var report = _sut.GetReport(new AggregateException(new FooUnauthorizedException()));

        Assert.True(report.IsExpected);
        Assert.False(report.CouldBeTransient);
        Assert.True(report.CouldBeExternallySolvable);
    }
}