using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using Moq;
using RedShirt.Example.Api.Common.Services.Utility;
using RedShirt.Example.Api.Connectors.Foo.Core.Exceptions;
using RedShirt.Example.Api.Connectors.Foo.Implementation.Exceptions;
using RedShirt.Example.Api.Connectors.Foo.Implementation.Services.Resilience;
using System.Net;

namespace RedShirt.Example.Api.Connectors.Foo.Implementation.UnitTests.Tests.Services.Resilience;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class FooRetryWrapperServiceTests
{
    private static FooRetryWrapperService CreateSut(
        IFooExceptionArbiterService? arbiter = null,
        ISleepService? sleep = null,
        int? retryCount = 3)
    {
        var sleepMock = new Mock<ISleepService>();
        sleepMock
            .Setup(s => s.DelayAsync(It.IsAny<TimeSpan>(), It.IsAny<CancellationToken>()))
            .Returns(Task.CompletedTask);

        return new FooRetryWrapperService(
            arbiter ?? new FooExceptionArbiterService(),
            NullLogger<FooRetryWrapperService>.Instance,
            sleep ?? sleepMock.Object,
            Options.Create(new FooRetryWrapperService.ConfigurationModel
            {
                RetryCount = retryCount
            }));
    }

    [Fact]
    public async Task RunAsync_DoesNotWrap_UnexpectedExceptions()
    {
        var sut = CreateSut();

        await Assert.ThrowsAsync<InvalidOperationException>(() =>
            sut.RunAsync<int>(_ => throw new InvalidOperationException("surprise"),
                TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task RunAsync_PassesThrough_FooRecordNotFoundException()
    {
        var sut = CreateSut();

        var ex = await Assert.ThrowsAsync<FooRecordNotFoundException>(() =>
            sut.RunAsync<int>(_ => throw new FooRecordNotFoundException(5),
                TestContext.Current.CancellationToken));

        Assert.Equal(5, ex.Id);
    }

    [Fact]
    public async Task RunAsync_RetriesTransientFailures_ThenSucceeds()
    {
        var attempts = 0;
        var sleep = new Mock<ISleepService>(MockBehavior.Strict);
        sleep
            .Setup(s => s.DelayAsync(It.IsAny<TimeSpan>(), It.IsAny<CancellationToken>()))
            .Returns(Task.CompletedTask);

        var sut = CreateSut(sleep: sleep.Object);

        var result = await sut.RunAsync(_ =>
        {
            attempts++;
            if (attempts < 3)
            {
                throw new HttpRequestException("unavailable", null, HttpStatusCode.ServiceUnavailable);
            }

            return Task.FromResult("ok");
        }, TestContext.Current.CancellationToken);

        Assert.Equal("ok", result);
        Assert.Equal(3, attempts);
        sleep.Verify(s => s.DelayAsync(It.IsAny<TimeSpan>(), It.IsAny<CancellationToken>()), Times.Exactly(2));
    }

    [Fact]
    public async Task RunAsync_ReturnsResult_WhenFuncSucceeds()
    {
        var sut = CreateSut();

        var result = await sut.RunAsync(_ => Task.FromResult(42), TestContext.Current.CancellationToken);

        Assert.Equal(42, result);
    }

    [Fact]
    public async Task RunAsync_WrapsExpectedNonTransient_AsFooConnectorException()
    {
        var sut = CreateSut();

        var wrapped = await Assert.ThrowsAsync<FooConnectorException>(() =>
            sut.RunAsync<int>(
                _ => throw new HttpRequestException("missing", null, HttpStatusCode.NotFound),
                TestContext.Current.CancellationToken));

        Assert.True(wrapped.IsHandled);
        Assert.False(wrapped.CouldBeTransient);
        Assert.True(wrapped.CouldBeExternallySolvable);
        Assert.IsType<HttpRequestException>(wrapped.InnerException);
    }

    [Fact]
    public async Task RunAsync_Wraps_FooUnauthorizedException_AsFooConnectorException()
    {
        var sut = CreateSut();

        var wrapped = await Assert.ThrowsAsync<FooConnectorException>(() =>
            sut.RunAsync<int>(_ => throw new FooUnauthorizedException(),
                TestContext.Current.CancellationToken));

        Assert.True(wrapped.IsHandled);
        Assert.False(wrapped.CouldBeTransient);
        Assert.True(wrapped.CouldBeExternallySolvable);
        Assert.IsType<FooUnauthorizedException>(wrapped.InnerException);
    }

    [Fact]
    public async Task RunAsync_Wraps_FooUnavailableException_AsFooConnectorException()
    {
        var sut = CreateSut();

        var wrapped = await Assert.ThrowsAsync<FooConnectorException>(() =>
            sut.RunAsync<int>(_ => throw new FooUnavailableException(),
                TestContext.Current.CancellationToken));

        Assert.True(wrapped.IsHandled);
        Assert.False(wrapped.CouldBeTransient);
        Assert.True(wrapped.CouldBeExternallySolvable);
        Assert.IsType<FooUnavailableException>(wrapped.InnerException);
    }
}