using RedShirt.Example.Api.Common.Shared.Implementation.InMemory.Services;

namespace RedShirt.Example.Api.Common.Shared.Implementation.InMemory.UnitTests.Tests.Services;

/// <summary>
/// Generated by Cursor (Composer).
/// </summary>
public class InMemoryLockServiceTests
{
    [Fact]
    public async Task GetLockAsync_AcquiresLock_WhenKeyIsFree()
    {
        var service = new InMemoryLockService();

        var acquired = await service.GetLockAsync("key");

        Assert.True(acquired.IsAcquired);
    }

    [Fact]
    public async Task GetLockAsync_DoesNotAcquire_WhenKeyIsHeld()
    {
        var service = new InMemoryLockService();

        var first = await service.GetLockAsync("key");
        var second = await service.GetLockAsync("key");

        Assert.True(first.IsAcquired);
        Assert.False(second.IsAcquired);
    }

    [Fact]
    public async Task GetLockAsync_CanAcquireAgain_AfterUnlock()
    {
        var service = new InMemoryLockService();

        var first = await service.GetLockAsync("key");
        first.Unlock();

        var second = await service.GetLockAsync("key");

        Assert.True(second.IsAcquired);
    }

    [Fact]
    public async Task GetLockAsync_AllowsIndependentKeys()
    {
        var service = new InMemoryLockService();

        var first = await service.GetLockAsync("key-a");
        var second = await service.GetLockAsync("key-b");

        Assert.True(first.IsAcquired);
        Assert.True(second.IsAcquired);
    }

    [Fact]
    public async Task Unlock_IsSafe_WhenLockWasNotAcquired()
    {
        var service = new InMemoryLockService();

        var first = await service.GetLockAsync("key");
        var second = await service.GetLockAsync("key");

        second.Unlock();

        Assert.True(first.IsAcquired);
        Assert.False(second.IsAcquired);

        var third = await service.GetLockAsync("key");
        Assert.False(third.IsAcquired);
    }

    [Fact]
    public async Task Unlock_IsIdempotent()
    {
        var service = new InMemoryLockService();

        var acquired = await service.GetLockAsync("key");
        acquired.Unlock();
        acquired.Unlock();

        var next = await service.GetLockAsync("key");

        Assert.True(next.IsAcquired);
    }
}
