using RedShirt.Example.Api.Common.Shared.Implementation.InMemory.Services;
using System.Collections;
using System.Reflection;

namespace RedShirt.Example.Api.Common.Shared.Implementation.InMemory.UnitTests.Tests.Services;

/// <summary>
/// Code generated by Cursor (Auto / Composer).
/// </summary>
public class InMemoryDataCacheServiceTests
{
    [Fact]
    public async Task GetStringAsync_ReturnsNull_WhenKeyIsMissing()
    {
        using var service = new InMemoryDataCacheService();

        Assert.Null(await service.GetStringAsync("missing"));
    }

    [Fact]
    public async Task SetStringAsync_ThenGetStringAsync_ReturnsStoredValue()
    {
        using var service = new InMemoryDataCacheService();

        await service.SetStringAsync("greeting", "hello", TimeSpan.FromMinutes(5));

        Assert.Equal("hello", await service.GetStringAsync("greeting"));
    }

    [Fact]
    public async Task SetStringAsync_CanStoreEmptyString()
    {
        using var service = new InMemoryDataCacheService();

        await service.SetStringAsync("empty", string.Empty, TimeSpan.FromMinutes(5));

        Assert.Equal(string.Empty, await service.GetStringAsync("empty"));
    }

    [Fact]
    public async Task SetStringAsync_OverwritesExistingValue_AndExpiration()
    {
        using var service = new InMemoryDataCacheService();

        await service.SetStringAsync("key", "first", TimeSpan.FromMilliseconds(-1));
        await service.SetStringAsync("key", "second", TimeSpan.FromMinutes(5));

        Assert.Equal("second", await service.GetStringAsync("key"));
    }

    [Fact]
    public async Task GetStringAsync_ReturnsNull_AndRemovesEntry_WhenExpired()
    {
        using var service = new InMemoryDataCacheService();

        await service.SetStringAsync("stale", "value", TimeSpan.FromMilliseconds(-1));

        Assert.Null(await service.GetStringAsync("stale"));
        Assert.False(GetCache(service).Contains("stale"));
    }

    [Fact]
    public async Task GetStringAsync_KeepsUnrelatedKeys_WhenOneKeyIsExpired()
    {
        using var service = new InMemoryDataCacheService();

        await service.SetStringAsync("fresh", "keep-me", TimeSpan.FromMinutes(5));
        await service.SetStringAsync("stale", "drop-me", TimeSpan.FromMilliseconds(-1));

        Assert.Null(await service.GetStringAsync("stale"));
        Assert.Equal("keep-me", await service.GetStringAsync("fresh"));
    }

    [Fact]
    public async Task SetStringAsync_IsolatesValuesByKey()
    {
        using var service = new InMemoryDataCacheService();

        await service.SetStringAsync("key-a", "value-a", TimeSpan.FromMinutes(5));
        await service.SetStringAsync("key-b", "value-b", TimeSpan.FromMinutes(5));

        Assert.Equal("value-a", await service.GetStringAsync("key-a"));
        Assert.Equal("value-b", await service.GetStringAsync("key-b"));
        Assert.Null(await service.GetStringAsync("key-c"));
    }

    [Fact]
    public async Task CleanupExpiredEntries_RemovesOnlyExpiredEntries()
    {
        using var service = new InMemoryDataCacheService();

        await service.SetStringAsync("fresh", "keep-me", TimeSpan.FromMinutes(5));
        await service.SetStringAsync("stale", "drop-me", TimeSpan.FromMilliseconds(-1));

        InvokeCleanupExpiredEntries(service);

        var cache = GetCache(service);
        Assert.True(cache.Contains("fresh"));
        Assert.False(cache.Contains("stale"));
        Assert.Equal("keep-me", await service.GetStringAsync("fresh"));
    }

    [Fact]
    public async Task CleanupExpiredEntries_IsNoOp_WhenNoEntriesAreExpired()
    {
        using var service = new InMemoryDataCacheService();

        await service.SetStringAsync("fresh", "keep-me", TimeSpan.FromMinutes(5));

        InvokeCleanupExpiredEntries(service);

        Assert.True(GetCache(service).Contains("fresh"));
        Assert.Equal("keep-me", await service.GetStringAsync("fresh"));
    }

    [Fact]
    public async Task ConcurrentSetAndGet_DoNotThrow()
    {
        using var service = new InMemoryDataCacheService();

        var tasks = Enumerable.Range(0, 100).Select(async i =>
        {
            var key = $"key-{i % 10}";
            await service.SetStringAsync(key, $"value-{i}", TimeSpan.FromMinutes(1));
            _ = await service.GetStringAsync(key);
        });

        var exception = await Record.ExceptionAsync(() => Task.WhenAll(tasks));

        Assert.Null(exception);
    }

    [Fact]
    public void Dispose_CanBeCalledSafely()
    {
        var service = new InMemoryDataCacheService();

        var exception = Record.Exception(service.Dispose);

        Assert.Null(exception);
    }

    private static IDictionary GetCache(InMemoryDataCacheService service)
    {
        var field = typeof(InMemoryDataCacheService).GetField("_cache",
            BindingFlags.Instance | BindingFlags.NonPublic);
        Assert.NotNull(field);

        var cache = field.GetValue(service) as IDictionary;
        Assert.NotNull(cache);
        return cache;
    }

    private static void InvokeCleanupExpiredEntries(InMemoryDataCacheService service)
    {
        var method = typeof(InMemoryDataCacheService).GetMethod("CleanupExpiredEntries",
            BindingFlags.Instance | BindingFlags.NonPublic);
        Assert.NotNull(method);

        method.Invoke(service, null);
    }
}
