using RedShirt.Api.Example.Connectors.Foo.Core.Exceptions;

namespace RedShirt.Api.Example.Connectors.Foo.Core.UnitTests.Tests.Exceptions;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class FooExceptionTests
{
    [Fact]
    public void FooConnectorException_MessageOnlyConstructor_SetsMessage()
    {
        var exception = new FooConnectorException("classified failure")
        {
            IsHandled = false,
            CouldBeTransient = true,
            CouldBeExternallySolvable = false
        };

        Assert.Equal("classified failure", exception.Message);
        Assert.Null(exception.InnerException);
    }

    [Fact]
    public void FooConnectorException_PreservesInnerExceptionAndFlags()
    {
        var inner = new InvalidOperationException("upstream failed");
        var exception = new FooConnectorException(inner)
        {
            IsHandled = true,
            CouldBeTransient = false,
            CouldBeExternallySolvable = true
        };

        Assert.Same(inner, exception.InnerException);
        Assert.Equal(inner.Message, exception.Message);
        Assert.True(exception.IsHandled);
        Assert.False(exception.CouldBeTransient);
        Assert.True(exception.CouldBeExternallySolvable);
    }

    [Fact]
    public void FooRecordNotFoundException_CapturesIdAndMessage()
    {
        var exception = new FooRecordNotFoundException(42);

        Assert.Equal(42, exception.Id);
        Assert.Equal("Foo record 42 was not found.", exception.Message);
    }

    [Fact]
    public void FooUnauthorizedException_UsesStableMessage()
    {
        var exception = new FooUnauthorizedException();

        Assert.Equal("Foo API rejected the API key.", exception.Message);
        Assert.Null(exception.InnerException);
    }
}