<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Dapper.SqlBuilder" Version="2.1.66"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10"/>
        <PackageReference Include="MySql.Data" Version="26.7.0"/>
        <PackageReference Include="Polly" Version="8.7.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\RedShirt.Example.Api.Common.Analyzers.Database.Abstractions\RedShirt.Example.Api.Common.Analyzers.Database.Abstractions.csproj"/>
        <ProjectReference Include="..\RedShirt.Example.Api.Common.Database\RedShirt.Example.Api.Common.Database.csproj"/>
        <ProjectReference Include="..\RedShirt.Example.Api.Common.Exceptions\RedShirt.Example.Api.Common.Exceptions.csproj"/>
        <ProjectReference Include="..\RedShirt.Example.Api.Common.SecretManagers.Core\RedShirt.Example.Api.Common.SecretManagers.Core.csproj"/>
        <ProjectReference Include="..\RedShirt.Example.Api.Common\RedShirt.Example.Api.Common.csproj"/>
    </ItemGroup>

</Project>
