using RedShirt.Example.Api.Core.UseCases.Product.Commands.Create;

namespace RedShirt.Example.Api.Core.UnitTests.Tests.UseCases.Product.Commands.Create;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class CreateProductCommandValidatorTests
{
    private readonly CreateProductCommandValidator _validator = new();

    [Theory]
    [InlineData("not-a-decimal")]
    [InlineData("12.34.56")]
    [InlineData("abc")]
    public async Task Validate_Fails_WhenPriceIsNotAValidDecimal(string price)
    {
        var result = await _validator.ValidateAsync(
            new CreateProductCommand("SKU-1", "Widget", price, "idem-1"),
            TestContext.Current.CancellationToken);

        Assert.False(result.IsValid);
        Assert.Contains(result.Errors,
            error => error.ErrorMessage == "'Price' must be a valid decimal number");
    }

    [Theory]
    [InlineData("9.99")]
    [InlineData("0")]
    [InlineData("1000")]
    [InlineData("-1.5")]
    public async Task Validate_Succeeds_WhenPriceIsAValidDecimal(string price)
    {
        var result = await _validator.ValidateAsync(
            new CreateProductCommand("SKU-1", "Widget", price, "idem-1"),
            TestContext.Current.CancellationToken);

        Assert.True(result.IsValid);
    }
}