using Moq;
using RedShirt.Example.Api.Core.Cqrs;
using RedShirt.Example.Api.Core.Services;
using RedShirt.Example.Api.Core.UseCases.Product.Commands.Create;
using RedShirt.Example.Api.DataStores.Product.Core.Models;
using RedShirt.Example.Api.DataStores.Product.Core.Services;

namespace RedShirt.Example.Api.Core.UnitTests.Tests.UseCases.Product.Commands.Create;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class CreateProductCommandHandlerTests
{
    private static CreateProductCommandHandler CreateHandler(
        IProductService? productService = null,
        ICacheBasedIdempotencyWrapperService? idempotencyWrapperService = null,
        ICoreRequestValidator? requestValidator = null)
    {
        return new CreateProductCommandHandler(
            productService ?? new Mock<IProductService>().Object,
            idempotencyWrapperService ?? CreateInvokingWrapper().Object,
            requestValidator ?? new Mock<ICoreRequestValidator>().Object);
    }

    private static Mock<ICacheBasedIdempotencyWrapperService> CreateInvokingWrapper()
    {
        var wrapper = new Mock<ICacheBasedIdempotencyWrapperService>();
        wrapper
            .Setup(w => w.RunIdempotentlyAsync(
                It.IsAny<string>(),
                It.IsAny<Func<Task<ProductDto>>>(),
                It.IsAny<CancellationToken>()))
            .Returns((string _, Func<Task<ProductDto>> callback, CancellationToken _) => callback());
        return wrapper;
    }

    [Fact]
    public async Task Handle_ReturnsWrapperResult_WithoutCallingService_WhenCallbackIsSkipped()
    {
        var cached = new ProductDto
        {
            Id = Guid.NewGuid(),
            CreatedAtUtc = DateTime.UtcNow,
            UpdatedAtUtc = DateTime.UtcNow,
            Sku = "SKU-CACHED",
            Name = "Cached",
            Price = "1.00"
        };
        var productService = new Mock<IProductService>();
        var wrapper = new Mock<ICacheBasedIdempotencyWrapperService>();
        wrapper
            .Setup(w => w.RunIdempotentlyAsync(
                "idem-1",
                It.IsAny<Func<Task<ProductDto>>>(),
                TestContext.Current.CancellationToken))
            .ReturnsAsync(cached);
        var handler = CreateHandler(productService.Object, wrapper.Object);

        var result = await handler.Handle(
            new CreateProductCommand("SKU-1", "Fresh", "9.99", "idem-1"),
            TestContext.Current.CancellationToken);

        Assert.Same(cached, result);
        productService.Verify(
            s => s.PostAsync(It.IsAny<ProductServicePostRequest>(), It.IsAny<CancellationToken>()),
            Times.Never);
    }

    [Fact]
    public async Task Handle_RunsThroughIdempotencyWrapper_AndPostsMappedRequestOnSuccess()
    {
        var internalDto = new ProductInternalDto
        {
            Id = Guid.NewGuid(),
            CreatedAtUtc = DateTime.UtcNow,
            UpdatedAtUtc = DateTime.UtcNow,
            Sku = "SKU-1",
            Name = "Widget",
            Price = 9.99m
        };
        ProductServicePostRequest? capturedRequest = null;
        var productService = new Mock<IProductService>();
        productService
            .Setup(s => s.PostAsync(It.IsAny<ProductServicePostRequest>(), TestContext.Current.CancellationToken))
            .Callback<ProductServicePostRequest, CancellationToken>((request, _) => capturedRequest = request)
            .ReturnsAsync(internalDto);
        var wrapper = CreateInvokingWrapper();
        var validator = new Mock<ICoreRequestValidator>();
        var handler = CreateHandler(productService.Object, wrapper.Object, validator.Object);
        var command = new CreateProductCommand("SKU-1", "Widget", "9.99", "idem-1");

        var result = await handler.Handle(command, TestContext.Current.CancellationToken);

        Assert.NotNull(capturedRequest);
        Assert.Equal("SKU-1", capturedRequest!.Sku);
        Assert.Equal("Widget", capturedRequest.Name);
        Assert.Equal(9.99m, capturedRequest.Price);
        Assert.Equal("9.99", result.Price);
        validator.Verify(v => v.ValidateAsync(command, TestContext.Current.CancellationToken), Times.Once);
        productService.Verify(
            s => s.PostAsync(It.IsAny<ProductServicePostRequest>(), TestContext.Current.CancellationToken),
            Times.Once);
        wrapper.Verify(w => w.RunIdempotentlyAsync(
            "idem-1",
            It.IsAny<Func<Task<ProductDto>>>(),
            TestContext.Current.CancellationToken), Times.Once);
    }
}