using RedShirt.Example.Api.Connectors.Common.Http.Exceptions;
using System.Net;
using System.Text.Json;

namespace RedShirt.Example.Api.Connectors.Common.Http.UnitTests.Tests.Exceptions;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class OAuthExceptionTests
{
    [Fact]
    public void OAuthRequestException_InnerExceptionConstructor_PreservesInnerAndStatus()
    {
        var inner = new InvalidOperationException("ssm down");
        var exception = new OAuthRequestException("wrapped", inner, HttpStatusCode.BadGateway)
        {
            StatusCode = HttpStatusCode.BadGateway,
            CredentialStorageProblem = true,
            FreshCredentialCacheResult = false
        };

        Assert.Same(inner, exception.InnerException);
        Assert.Equal("wrapped", exception.Message);
        Assert.Equal(HttpStatusCode.BadGateway, exception.StatusCode);
        Assert.True(exception.CredentialStorageProblem);
        Assert.False(exception.FreshCredentialCacheResult);
    }

    [Fact]
    public void OAuthRequestException_MessageOnly_AllowsRequiredFlagsViaInitializer()
    {
        var exception = new OAuthRequestException("token failed")
        {
            StatusCode = HttpStatusCode.Unauthorized,
            CredentialStorageProblem = false,
            FreshCredentialCacheResult = true
        };

        Assert.Equal("token failed", exception.Message);
        Assert.Equal(HttpStatusCode.Unauthorized, exception.StatusCode);
        Assert.False(exception.CredentialStorageProblem);
        Assert.True(exception.FreshCredentialCacheResult);
        Assert.Null(exception.InnerException);
    }

    [Fact]
    public void OAuthRequestJsonException_MessageOnly_HasNoInnerException()
    {
        var exception = new OAuthRequestJsonException("missing access_token");

        Assert.Equal("missing access_token", exception.Message);
        Assert.Null(exception.InnerException);
    }

    [Fact]
    public void OAuthRequestJsonException_PreservesMessageAndInnerException()
    {
        var inner = new JsonException("bad json");
        var exception = new OAuthRequestJsonException("could not parse", inner);

        Assert.Equal("could not parse", exception.Message);
        Assert.Same(inner, exception.InnerException);
    }
}