using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using Moq;
using RedShirt.Api.Example.Connectors.Bar.Implementation.Exceptions;
using RedShirt.Api.Example.Connectors.Bar.Implementation.Services.Resilience;
using RedShirt.Api.Example.Connectors.Common.Http.Enums;
using RedShirt.Api.Example.Connectors.Common.Http.Exceptions;
using RedShirt.Api.Example.Connectors.Common.Http.Models;
using RedShirt.Api.Example.Connectors.Common.Http.Services;
using System.Net;

namespace RedShirt.Api.Example.Connectors.Bar.Implementation.UnitTests.Tests.Services.Resilience;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class BarApiRequestHandlerRetryWrapperServiceTests
{
    private const string TokenUrl = "https://auth.example/oauth/token";
    private const string ClientIdPath = "/bar/oauth/client-id";
    private const string ClientSecretPath = "/bar/oauth/client-secret";

    private static BarApiRequestHandlerRetryWrapperService CreateSut(
        IOAuthTokenCache tokenCache,
        int? cooldownSeconds = 60)
    {
        return new BarApiRequestHandlerRetryWrapperService(
            tokenCache,
            NullLogger<BarApiRequestHandlerRetryWrapperService>.Instance,
            Options.Create(new BarApiRequestHandlerRetryWrapperService.ConfigurationModel
            {
                TokenUrl = TokenUrl,
                ClientIdPath = ClientIdPath,
                ClientSecretPath = ClientSecretPath,
                ScopeLabel = "audience",
                ScopeValue = "https://bar.example",
                TokenRefreshCooldownSeconds = cooldownSeconds
            }));
    }

    private static OAuthTokenCacheResponse Token(string accessToken, TokenCacheState state) => new()
    {
        AccessToken = accessToken,
        ExpiresAtUtc = DateTimeOffset.UtcNow.AddHours(1),
        TokenCacheState = state
    };

    [Fact]
    public async Task GetAccessTokenAsync_CachesToken_UntilForcedRefreshPath()
    {
        var cache = new Mock<IOAuthTokenCache>(MockBehavior.Strict);
        cache
            .Setup(c => c.GetAsync(
                It.IsAny<OAuthClientCredentialsRequest>(),
                false,
                false,
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(Token("tok-1", TokenCacheState.FreshToken));

        var sut = CreateSut(cache.Object);

        var first = await sut.GetAccessTokenAsync(TestContext.Current.CancellationToken);
        var second = await sut.GetAccessTokenAsync(TestContext.Current.CancellationToken);

        Assert.Equal("tok-1", first);
        Assert.Equal("tok-1", second);
        cache.Verify(
            c => c.GetAsync(It.IsAny<OAuthClientCredentialsRequest>(), false, false, It.IsAny<CancellationToken>()),
            Times.Once);
    }

    [Fact]
    public async Task ExecuteAsync_RefreshesToken_OnBarUnauthorized_WhenOutsideCooldown()
    {
        var cache = new Mock<IOAuthTokenCache>(MockBehavior.Strict);
        cache
            .Setup(c => c.GetAsync(
                It.IsAny<OAuthClientCredentialsRequest>(),
                false,
                false,
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(Token("old-token", TokenCacheState.FreshToken));
        cache
            .Setup(c => c.GetAsync(
                It.IsAny<OAuthClientCredentialsRequest>(),
                true,
                false,
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(Token("new-token", TokenCacheState.FreshToken));

        var sut = CreateSut(cache.Object, cooldownSeconds: 1);
        await sut.GetAccessTokenAsync(TestContext.Current.CancellationToken);
        await Task.Delay(TimeSpan.FromMilliseconds(1100), TestContext.Current.CancellationToken);

        var attempts = 0;
        var result = await sut.ExecuteAsync(async ct =>
        {
            attempts++;
            var token = await sut.GetAccessTokenAsync(ct);
            if (token == "old-token")
            {
                throw new BarUnauthorizedException();
            }

            return token;
        }, TestContext.Current.CancellationToken);

        Assert.Equal("new-token", result);
        Assert.Equal(2, attempts);
        cache.Verify(
            c => c.GetAsync(It.IsAny<OAuthClientCredentialsRequest>(), true, false, It.IsAny<CancellationToken>()),
            Times.Once);
    }

    [Fact]
    public async Task ExecuteAsync_RetriesOAuthUnauthorized_WithForcedCredentials_OnFirstAttempt()
    {
        var cache = new Mock<IOAuthTokenCache>(MockBehavior.Strict);
        cache
            .Setup(c => c.GetAsync(
                It.IsAny<OAuthClientCredentialsRequest>(),
                false,
                false,
                It.IsAny<CancellationToken>()))
            .ThrowsAsync(new OAuthRequestException("bad secret")
            {
                StatusCode = HttpStatusCode.Unauthorized,
                CredentialStorageProblem = false,
                FreshCredentialCacheResult = false
            });
        cache
            .Setup(c => c.GetAsync(
                It.IsAny<OAuthClientCredentialsRequest>(),
                true,
                true,
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(Token("recovered-token", TokenCacheState.ForcedCredentialRetrieval));

        var sut = CreateSut(cache.Object, cooldownSeconds: 1);

        var result = await sut.ExecuteAsync(async ct => await sut.GetAccessTokenAsync(ct),
            TestContext.Current.CancellationToken);

        Assert.Equal("recovered-token", result);
        cache.Verify(
            c => c.GetAsync(It.IsAny<OAuthClientCredentialsRequest>(), true, true, It.IsAny<CancellationToken>()),
            Times.Once);
    }

    [Fact]
    public async Task ExecuteAsync_ThrowsBarUnavailable_WhenTokenRefreshBlockedByAttemptCooldown()
    {
        var cache = new Mock<IOAuthTokenCache>(MockBehavior.Strict);
        cache
            .Setup(c => c.GetAsync(
                It.IsAny<OAuthClientCredentialsRequest>(),
                false,
                false,
                It.IsAny<CancellationToken>()))
            .ThrowsAsync(new OAuthRequestException("unauthorized")
            {
                StatusCode = HttpStatusCode.Unauthorized,
                CredentialStorageProblem = false,
                FreshCredentialCacheResult = true
            });

        var sut = CreateSut(cache.Object, cooldownSeconds: 120);

        // First call records the failed attempt timestamp / status.
        await Assert.ThrowsAsync<OAuthRequestException>(() =>
            sut.GetAccessTokenAsync(TestContext.Current.CancellationToken));

        // Immediate retry without forced credentials should be blocked as unavailable.
        await Assert.ThrowsAsync<BarUnavailableException>(() =>
            sut.GetAccessTokenAsync(TestContext.Current.CancellationToken));
    }

    [Fact]
    public void ConfigurationModel_EffectiveTokenRefreshCooldown_FloorsAtOneSecond()
    {
        var model = new BarApiRequestHandlerRetryWrapperService.ConfigurationModel
        {
            TokenUrl = TokenUrl,
            ClientIdPath = ClientIdPath,
            ClientSecretPath = ClientSecretPath,
            ScopeLabel = null,
            ScopeValue = null,
            TokenRefreshCooldownSeconds = 0
        };

        Assert.Equal(TimeSpan.FromSeconds(1), model.EffectiveTokenRefreshCooldown);
    }
}
