using RedShirt.Api.Example.Connectors.Bar.Core.Exceptions;
using RedShirt.Api.Example.Connectors.Bar.Implementation.Exceptions;
using RedShirt.Api.Example.Connectors.Bar.Implementation.Services.Resilience;
using RedShirt.Api.Example.Connectors.Common.Http.Exceptions;
using RedShirt.Example.Api.Common.SecretManagers.Core.Exceptions;
using System.Net;
using System.Net.Sockets;
using System.Text.Json;

namespace RedShirt.Api.Example.Connectors.Bar.Implementation.UnitTests.Tests.Services.Resilience;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class BarExceptionArbiterServiceTests
{
    private readonly BarExceptionArbiterService _sut = new();

    [Fact]
    public void GetReport_ApiSecretManagerException_IsAlreadyHandled()
    {
        var report = _sut.GetReport(new ApiSecretManagerException(new InvalidOperationException("ssm"))
        {
            IsHandled = true,
            CouldBeTransient = true,
            CouldBeExternallySolvable = true
        });

        Assert.True(report.AlreadyHandled);
        Assert.True(report.IsExpected);
    }

    [Fact]
    public void GetReport_BarConnectorException_IsAlreadyHandled()
    {
        var report = _sut.GetReport(new BarConnectorException("done")
        {
            IsHandled = true,
            CouldBeTransient = false,
            CouldBeExternallySolvable = true
        });

        Assert.True(report.AlreadyHandled);
        Assert.True(report.IsExpected);
        Assert.False(report.CouldBeTransient);
        Assert.True(report.CouldBeExternallySolvable);
    }

    [Fact]
    public void GetReport_BarRecordNotFound_IsExpectedNonTransient()
    {
        var report = _sut.GetReport(new BarRecordNotFoundException(1));

        Assert.False(report.AlreadyHandled);
        Assert.True(report.IsExpected);
        Assert.False(report.CouldBeTransient);
        Assert.False(report.CouldBeExternallySolvable);
    }

    [Fact]
    public void GetReport_BarUnauthorized_IsExpectedExternallySolvable()
    {
        var report = _sut.GetReport(new BarUnauthorizedException());

        Assert.False(report.AlreadyHandled);
        Assert.True(report.IsExpected);
        Assert.False(report.CouldBeTransient);
        Assert.True(report.CouldBeExternallySolvable);
    }

    [Fact]
    public void GetReport_BarUnavailable_IsExpectedExternallySolvable()
    {
        var report = _sut.GetReport(new BarUnavailableException());

        Assert.False(report.AlreadyHandled);
        Assert.True(report.IsExpected);
        Assert.False(report.CouldBeTransient);
        Assert.True(report.CouldBeExternallySolvable);
    }

    [Fact]
    public void GetReport_Http404_IsExpectedNonTransient()
    {
        var report = _sut.GetReport(new HttpRequestException("missing", null, HttpStatusCode.NotFound));

        Assert.True(report.IsExpected);
        Assert.False(report.CouldBeTransient);
        Assert.True(report.CouldBeExternallySolvable);
    }

    [Fact]
    public void GetReport_Http503_IsTransient()
    {
        var report = _sut.GetReport(new HttpRequestException("boom", null, HttpStatusCode.ServiceUnavailable));

        Assert.True(report.IsExpected);
        Assert.True(report.CouldBeTransient);
        Assert.True(report.CouldBeExternallySolvable);
    }

    [Fact]
    public void GetReport_HttpWithoutStatus_IsTransient()
    {
        var report = _sut.GetReport(new HttpRequestException("connection refused"));

        Assert.True(report.IsExpected);
        Assert.True(report.CouldBeTransient);
    }

    [Fact]
    public void GetReport_JsonException_IsExpectedNonTransient()
    {
        var report = _sut.GetReport(new JsonException("bad payload"));

        Assert.True(report.IsExpected);
        Assert.False(report.CouldBeTransient);
    }

    [Fact]
    public void GetReport_OAuthOtherStatus_IsTransient()
    {
        var report = _sut.GetReport(new OAuthRequestException("token unavailable")
        {
            StatusCode = HttpStatusCode.ServiceUnavailable,
            CredentialStorageProblem = false,
            FreshCredentialCacheResult = true
        });

        Assert.True(report.IsExpected);
        Assert.True(report.CouldBeTransient);
    }

    [Fact]
    public void GetReport_OAuthRequestJsonException_IsExpectedNonTransient()
    {
        var report = _sut.GetReport(new OAuthRequestJsonException("bad payload"));

        Assert.True(report.IsExpected);
        Assert.False(report.CouldBeTransient);
    }

    [Fact]
    public void GetReport_OAuthUnauthorized_IsExpectedNonTransient()
    {
        var report = _sut.GetReport(new OAuthRequestException("bad secret")
        {
            StatusCode = HttpStatusCode.Unauthorized,
            CredentialStorageProblem = false,
            FreshCredentialCacheResult = false
        });

        Assert.True(report.IsExpected);
        Assert.False(report.CouldBeTransient);
        Assert.True(report.CouldBeExternallySolvable);
    }

    [Fact]
    public void GetReport_SocketException_IsTransient()
    {
        var report = _sut.GetReport(new SocketException());

        Assert.True(report.IsExpected);
        Assert.True(report.CouldBeTransient);
    }

    [Fact]
    public void GetReport_UnknownException_IsUnexpected()
    {
        var report = _sut.GetReport(new InvalidOperationException("surprise"));

        Assert.False(report.AlreadyHandled);
        Assert.False(report.IsExpected);
        Assert.False(report.CouldBeTransient);
        Assert.False(report.CouldBeExternallySolvable);
    }

    [Fact]
    public void GetReport_UnwrapsSingleAggregateException()
    {
        var report = _sut.GetReport(new AggregateException(new BarUnauthorizedException()));

        Assert.True(report.IsExpected);
        Assert.False(report.CouldBeTransient);
        Assert.True(report.CouldBeExternallySolvable);
    }
}