using Moq;
using RedShirt.Api.Example.Connectors.Bar.Implementation.Clients;
using RedShirt.Api.Example.Connectors.Bar.Implementation.Exceptions;
using RedShirt.Api.Example.Connectors.Bar.Implementation.Services.Resilience;
using System.Net;

namespace RedShirt.Api.Example.Connectors.Bar.Implementation.UnitTests.Tests.Clients;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class BarApiClientHandlerTests
{
    [Fact]
    public async Task SendAsync_AddsBearerToken_FromRetryWrapper()
    {
        var inner = new RecordingInnerHandler();
        var retry = new Mock<IBarApiRequestHandlerRetryWrapperService>(MockBehavior.Strict);
        retry
            .Setup(r => r.GetAccessTokenAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync("access-token");
        retry
            .Setup(r => r.ExecuteAsync(It.IsAny<Func<CancellationToken, Task<HttpResponseMessage>>>(),
                It.IsAny<CancellationToken>()))
            .Returns<Func<CancellationToken, Task<HttpResponseMessage>>,
                CancellationToken>((func, token) => func(token));

        var handler = new BarApiClientHandler(retry.Object)
        {
            InnerHandler = inner
        };
        using var invoker = new HttpMessageInvoker(handler);

        using var response = await invoker.SendAsync(
            new HttpRequestMessage(HttpMethod.Get, "http://bar.test/api/bar/1"),
            TestContext.Current.CancellationToken);

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        Assert.Equal("Bearer", inner.LastRequest!.Headers.Authorization!.Scheme);
        Assert.Equal("access-token", inner.LastRequest.Headers.Authorization.Parameter);
        retry.VerifyAll();
    }

    [Fact]
    public async Task SendAsync_ThrowsBarUnauthorized_On401()
    {
        var inner = new RecordingInnerHandler {StatusCode = HttpStatusCode.Unauthorized};
        var retry = new Mock<IBarApiRequestHandlerRetryWrapperService>(MockBehavior.Strict);
        retry
            .Setup(r => r.GetAccessTokenAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync("access-token");
        retry
            .Setup(r => r.ExecuteAsync(It.IsAny<Func<CancellationToken, Task<HttpResponseMessage>>>(),
                It.IsAny<CancellationToken>()))
            .Returns<Func<CancellationToken, Task<HttpResponseMessage>>,
                CancellationToken>((func, token) => func(token));

        var handler = new BarApiClientHandler(retry.Object)
        {
            InnerHandler = inner
        };
        using var invoker = new HttpMessageInvoker(handler);

        await Assert.ThrowsAsync<BarUnauthorizedException>(() =>
            invoker.SendAsync(
                new HttpRequestMessage(HttpMethod.Get, "http://bar.test/api/bar/1"),
                TestContext.Current.CancellationToken));
    }

    private sealed class RecordingInnerHandler : HttpMessageHandler
    {
        public HttpRequestMessage? LastRequest { get; private set; }
        public HttpStatusCode StatusCode { get; set; } = HttpStatusCode.OK;

        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,
            CancellationToken cancellationToken)
        {
            LastRequest = request;
            return Task.FromResult(new HttpResponseMessage(StatusCode));
        }
    }
}