using RedShirt.Api.Example.Connectors.Bar.Core.Exceptions;
using RedShirt.Api.Example.Connectors.Bar.Core.Models;
using RedShirt.Api.Example.Connectors.Bar.Implementation.Clients;
using System.Net;
using System.Text;

namespace RedShirt.Api.Example.Connectors.Bar.Implementation.UnitTests.Tests.Clients;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class BarApiClientTests
{
    private static BarApiClient CreateClient(StubHandler handler, string baseUrl = "http://bar.test/")
    {
        return new BarApiClient(new HttpClient(handler), baseUrl);
    }

    [Fact]
    public async Task CreateBarAsync_PostsJson_AndMapsResponse()
    {
        var handler = new StubHandler(_ => new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new StringContent("""{"Id":11,"Name":"widget"}""", Encoding.UTF8, "application/json")
        });
        var client = CreateClient(handler);

        var result = await client.CreateBarAsync(
            new CreateBarConnectorRequest {Name = "widget"},
            TestContext.Current.CancellationToken);

        Assert.Equal(11, result.Id);
        Assert.Equal("widget", result.Name);
        Assert.Equal(HttpMethod.Post, handler.LastRequest!.Method);
        Assert.Equal("http://bar.test/api/bar", handler.LastRequest.RequestUri!.ToString());
    }

    [Fact]
    public async Task CreateBarAsync_ThrowsHttpRequestException_OnNonSuccess()
    {
        var handler = new StubHandler(_ => new HttpResponseMessage(HttpStatusCode.BadRequest));
        var client = CreateClient(handler);

        var ex = await Assert.ThrowsAsync<HttpRequestException>(() =>
            client.CreateBarAsync(
                new CreateBarConnectorRequest {Name = "widget"},
                TestContext.Current.CancellationToken));

        Assert.Equal(HttpStatusCode.BadRequest, ex.StatusCode);
    }

    [Fact]
    public async Task GetBarByIdAsync_GetsJson_AndMapsResponse()
    {
        var handler = new StubHandler(_ => new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new StringContent("""{"Id":5,"Name":"Bar-5"}""", Encoding.UTF8, "application/json")
        });
        var client = CreateClient(handler);

        var result = await client.GetBarByIdAsync(5, TestContext.Current.CancellationToken);

        Assert.Equal(5, result.Id);
        Assert.Equal("Bar-5", result.Name);
        Assert.Equal(HttpMethod.Get, handler.LastRequest!.Method);
        Assert.Equal("http://bar.test/api/bar/5", handler.LastRequest.RequestUri!.ToString());
    }

    [Fact]
    public async Task GetBarByIdAsync_ThrowsBarRecordNotFound_On404()
    {
        var handler = new StubHandler(_ => new HttpResponseMessage(HttpStatusCode.NotFound));
        var client = CreateClient(handler);

        var ex = await Assert.ThrowsAsync<BarRecordNotFoundException>(() =>
            client.GetBarByIdAsync(404, TestContext.Current.CancellationToken));

        Assert.Equal(404, ex.Id);
    }

    [Fact]
    public async Task GetBarByIdAsync_ThrowsHttpRequestException_OnOtherErrors()
    {
        var handler = new StubHandler(_ => new HttpResponseMessage(HttpStatusCode.InternalServerError));
        var client = CreateClient(handler);

        var ex = await Assert.ThrowsAsync<HttpRequestException>(() =>
            client.GetBarByIdAsync(1, TestContext.Current.CancellationToken));

        Assert.Equal(HttpStatusCode.InternalServerError, ex.StatusCode);
    }

    private sealed class StubHandler(Func<HttpRequestMessage, HttpResponseMessage> responder) : HttpMessageHandler
    {
        public HttpRequestMessage? LastRequest { get; private set; }

        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,
            CancellationToken cancellationToken)
        {
            LastRequest = request;
            return Task.FromResult(responder(request));
        }
    }
}