using Microsoft.Extensions.DependencyInjection;
using RedShirt.Example.Api.Common.Shared.Core.Services;
using RedShirt.Example.Api.Common.Shared.Implementation.InMemory.Extensions;
using RedShirt.Example.Api.Common.Shared.Implementation.InMemory.Services;

namespace RedShirt.Example.Api.Common.Shared.Implementation.InMemory.UnitTests.Tests.Extensions;

/// <summary>
/// Generated by Cursor (Composer).
/// </summary>
public class ServiceCollectionExtensionsTests
{
    [Fact]
    public void AddInMemorySharedImplementations_RegistersExpectedServices()
    {
        var services = new ServiceCollection();

        services.AddInMemorySharedImplementations();

        using var provider = services.BuildServiceProvider();

        var cache = provider.GetRequiredService<IDataCacheService>();
        var locks = provider.GetRequiredService<IAbstractedLockService>();

        Assert.IsType<InMemoryDataCacheService>(cache);
        Assert.IsType<InMemoryLockService>(locks);
    }

    [Fact]
    public void AddInMemorySharedImplementations_RegistersSingletons()
    {
        var services = new ServiceCollection();

        services.AddInMemorySharedImplementations();

        using var provider = services.BuildServiceProvider();

        var cache1 = provider.GetRequiredService<IDataCacheService>();
        var cache2 = provider.GetRequiredService<IDataCacheService>();
        var lock1 = provider.GetRequiredService<IAbstractedLockService>();
        var lock2 = provider.GetRequiredService<IAbstractedLockService>();

        Assert.Same(cache1, cache2);
        Assert.Same(lock1, lock2);
    }
}
