using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authorization.Infrastructure;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using RedShirt.Example.Api.Authorization;
using RedShirt.Example.Api.Constants;
using RedShirt.Example.Api.Extensions;

namespace RedShirt.Example.Api.UnitTests.Tests.Extensions;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class AuthorizationServiceCollectionExtensionsTests
{
    private static ClaimsPrincipal PrincipalWithRoles(params string[] roles)
    {
        var identity = new ClaimsIdentity(
            roles.Select(role => new Claim("role", role)),
            authenticationType: "test",
            nameType: "preferred_username",
            roleType: "role");

        return new ClaimsPrincipal(identity);
    }

    private static bool HasPermissionClaimRequirement(AuthorizationPolicy policy, string permission)
    {
        return policy.Requirements.OfType<ClaimsAuthorizationRequirement>().Any(requirement =>
            requirement.ClaimType == AuthorizationPermissions.ClaimType
            && requirement.AllowedValues is not null
            && requirement.AllowedValues.Contains(permission));
    }

    [Fact]
    public void AddApiAuthorizationPolicies_RegistersPermissionPoliciesAndTransformation()
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddApiAuthorizationPolicies();

        using var provider = services.BuildServiceProvider();

        Assert.Contains(provider.GetServices<IClaimsTransformation>(),
            transformation => transformation is RolePermissionClaimsTransformation);
        Assert.Contains(provider.GetServices<IAuthorizationHandler>(),
            handler => handler is HttpGetAuthorizationHandler);
        Assert.Contains(provider.GetServices<IAuthorizationHandler>(),
            handler => handler is CustomerScopedResourceAuthorizationHandler);
        Assert.NotNull(provider.GetService<ICustomerScopedResourceAuthorizer>());

        var authorization = provider.GetRequiredService<IOptions<AuthorizationOptions>>().Value;

        var writePolicy = authorization.GetPolicy(AuthorizationPolicies.Write);
        Assert.NotNull(writePolicy);
        Assert.True(HasPermissionClaimRequirement(writePolicy, AuthorizationPermissions.Write));
        Assert.DoesNotContain(writePolicy.Requirements, requirement => requirement is HttpGetRequirement);

        var readPolicy = authorization.GetPolicy(AuthorizationPolicies.ReadApproved);
        Assert.NotNull(readPolicy);
        Assert.True(HasPermissionClaimRequirement(readPolicy, AuthorizationPermissions.Read));
        Assert.Contains(readPolicy.Requirements, requirement => requirement is HttpGetRequirement);

        Assert.Same(writePolicy, authorization.FallbackPolicy);

        var scopedPolicy = authorization.GetPolicy(AuthorizationPolicies.CustomerScoped);
        Assert.NotNull(scopedPolicy);
        Assert.Contains(scopedPolicy.Requirements, requirement => requirement is CustomerScopedResourceRequirement);
    }

    [Fact]
    public async Task AuthorizeAsync_ApiReadOnly_AllowsApprovedGet_DeniesWrite()
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddApiAuthorizationPolicies();

        using var provider = services.BuildServiceProvider();
        var transformation = provider.GetRequiredService<IClaimsTransformation>();
        var authorization = provider.GetRequiredService<IAuthorizationService>();

        var user = await transformation.TransformAsync(PrincipalWithRoles(AuthorizationRoles.ApiReadOnly));
        var httpContext = new DefaultHttpContext();
        httpContext.Request.Method = HttpMethods.Get;

        var read = await authorization.AuthorizeAsync(user, httpContext, AuthorizationPolicies.ReadApproved);
        var write = await authorization.AuthorizeAsync(user, httpContext, AuthorizationPolicies.Write);

        Assert.True(read.Succeeded);
        Assert.False(write.Succeeded);
    }

    [Fact]
    public async Task AuthorizeAsync_ApiUser_AllowsReadGetAndWrite()
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddApiAuthorizationPolicies();

        using var provider = services.BuildServiceProvider();
        var transformation = provider.GetRequiredService<IClaimsTransformation>();
        var authorization = provider.GetRequiredService<IAuthorizationService>();

        var user = await transformation.TransformAsync(PrincipalWithRoles(AuthorizationRoles.ApiUser));
        var httpContext = new DefaultHttpContext();
        httpContext.Request.Method = HttpMethods.Get;

        var read = await authorization.AuthorizeAsync(user, httpContext, AuthorizationPolicies.ReadApproved);
        var write = await authorization.AuthorizeAsync(user, httpContext, AuthorizationPolicies.Write);

        Assert.True(read.Succeeded);
        Assert.True(write.Succeeded);
    }

    [Fact]
    public async Task AuthorizeAsync_ApiReadOnly_DeniesApprovedPolicyOnPost()
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddApiAuthorizationPolicies();

        using var provider = services.BuildServiceProvider();
        var transformation = provider.GetRequiredService<IClaimsTransformation>();
        var authorization = provider.GetRequiredService<IAuthorizationService>();

        var user = await transformation.TransformAsync(PrincipalWithRoles(AuthorizationRoles.ApiReadOnly));
        var httpContext = new DefaultHttpContext();
        httpContext.Request.Method = HttpMethods.Post;

        var read = await authorization.AuthorizeAsync(user, httpContext, AuthorizationPolicies.ReadApproved);

        Assert.False(read.Succeeded);
    }
}
