using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authorization.Infrastructure;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using NSwag;
using NSwag.Generation;
using RedShirt.Example.Api.Authorization;
using RedShirt.Example.Api.Authorization.Constants;
using RedShirt.Example.Api.Authorization.Requirements;
using RedShirt.Example.Api.Extensions;
using ApiAuthenticationOptions = RedShirt.Example.Api.Configuration.AuthenticationOptions;

namespace RedShirt.Example.Api.UnitTests.Tests.Extensions;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class AuthenticationServiceCollectionExtensionsTests
{
    private static IConfiguration BuildConfiguration(Dictionary<string, string?> values)
    {
        return new ConfigurationBuilder()
            .AddInMemoryCollection(values)
            .Build();
    }

    private static IConfiguration DisabledAuthenticationConfiguration()
    {
        return BuildConfiguration(new Dictionary<string, string?>
        {
            ["Authentication:DisableAuthentication"] = "true"
        });
    }

    private static IConfiguration EnabledAuthenticationConfiguration(
        string? authority = "http://localhost:9080/realms/example",
        string? audience = "example-api",
        string? metadataAddress = "http://keycloak:8080/realms/example/.well-known/openid-configuration",
        string? requireHttpsMetadata = "false")
    {
        return BuildConfiguration(new Dictionary<string, string?>
        {
            ["Authentication:DisableAuthentication"] = "false",
            ["Authentication:Authority"] = authority,
            ["Authentication:Audience"] = audience,
            ["Authentication:MetadataAddress"] = metadataAddress,
            ["Authentication:RequireHttpsMetadata"] = requireHttpsMetadata
        });
    }

    [Fact]
    public async Task AddApiSwaggerDocument_WhenDisabled_DoesNotAdvertiseBearerSecurity()
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddControllers();
        services.AddApiSwaggerDocument(DisabledAuthenticationConfiguration());

        using var provider = services.BuildServiceProvider();
        var generators = provider.GetRequiredService<IEnumerable<IOpenApiDocumentGenerator>>();
        var document = await generators.Single().GenerateAsync("v1");

        Assert.Equal("RedShirt.Example.Api", document.Info.Title);
        Assert.Empty(document.SecurityDefinitions);
    }

    [Fact]
    public async Task AddApiSwaggerDocument_WhenEnabled_AdvertisesBearerSecurity()
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddControllers();
        services.AddApiSwaggerDocument(EnabledAuthenticationConfiguration());

        using var provider = services.BuildServiceProvider();
        var generators = provider.GetRequiredService<IEnumerable<IOpenApiDocumentGenerator>>();
        var document = await generators.Single().GenerateAsync("v1");

        Assert.Equal("RedShirt.Example.Api", document.Info.Title);
        Assert.True(document.SecurityDefinitions.ContainsKey("Bearer"));
        Assert.Equal(OpenApiSecuritySchemeType.Http, document.SecurityDefinitions["Bearer"].Type);
        Assert.Equal("bearer", document.SecurityDefinitions["Bearer"].Scheme);
    }

    [Fact]
    public void
        ConsiderAddingAuthentication_WhenConfigurationSectionMissing_ThrowsBecauseNullOptionsAreTreatedAsEnabled()
    {
        var services = new ServiceCollection();
        services.AddLogging();

        // IsAuthenticationEnabled(null) is true (`is not { DisableAuthentication: true }`),
        // so a missing section falls through and fails when Authority is read.
        Assert.ThrowsAny<Exception>(() =>
            services.ConsiderAddingAuthentication(new ConfigurationBuilder().Build()));
    }

    [Fact]
    public void ConsiderAddingAuthentication_WhenDisabled_DoesNotRegisterJwtSchemeOrFallbackPolicy()
    {
        var services = new ServiceCollection();
        services.AddLogging();

        services.ConsiderAddingAuthentication(DisabledAuthenticationConfiguration());

        using var provider = services.BuildServiceProvider();

        Assert.Null(provider.GetService<IAuthenticationSchemeProvider>());

        // IOptions<T> can still resolve via the options factory without Configure(...).
        // A disabled registration must not bind the configured Authority from our section.
        var options = provider.GetService<IOptions<ApiAuthenticationOptions>>()?.Value;
        Assert.True(options is null || string.IsNullOrWhiteSpace(options.Authority));

        var authorization = provider.GetService<IOptions<AuthorizationOptions>>()?.Value;
        Assert.True(authorization is null || authorization.FallbackPolicy is null);
    }

    [Fact]
    public void ConsiderAddingAuthentication_WhenEnabledWithoutAuthority_Throws()
    {
        var configuration = EnabledAuthenticationConfiguration("   ");
        var services = new ServiceCollection();

        var exception = Assert.Throws<InvalidOperationException>(() =>
            services.ConsiderAddingAuthentication(configuration));

        Assert.Contains("Authority", exception.Message, StringComparison.Ordinal);
    }

    [Fact]
    public async Task ConsiderAddingAuthentication_WhenEnabled_RegistersJwtBearerAndAuthorizationPolicies()
    {
        var services = new ServiceCollection();
        services.AddLogging();

        services.ConsiderAddingAuthentication(EnabledAuthenticationConfiguration());

        using var provider = services.BuildServiceProvider();

        var authenticationOptions = provider.GetRequiredService<IOptions<ApiAuthenticationOptions>>().Value;
        Assert.False(authenticationOptions.DisableAuthentication);
        Assert.Equal("http://localhost:9080/realms/example", authenticationOptions.Authority);
        Assert.Equal("example-api", authenticationOptions.Audience);
        Assert.False(authenticationOptions.EffectiveRequireHttpsMetadata);

        var schemes = provider.GetRequiredService<IAuthenticationSchemeProvider>();
        var bearer = await schemes.GetSchemeAsync(JwtBearerDefaults.AuthenticationScheme);
        Assert.NotNull(bearer);
        Assert.Equal(JwtBearerDefaults.AuthenticationScheme, bearer.Name);

        Assert.Contains(provider.GetServices<IClaimsTransformation>(),
            transformation => transformation is BespokeRolePermissionClaimsTransformation);
        Assert.Contains(provider.GetServices<IAuthorizationHandler>(),
            handler => handler is HttpGetAuthorizationHandler);

        var authorization = provider.GetRequiredService<IOptions<AuthorizationOptions>>().Value;
        Assert.NotNull(authorization.FallbackPolicy);
        Assert.Contains(JwtBearerDefaults.AuthenticationScheme, authorization.FallbackPolicy.AuthenticationSchemes);
        Assert.Contains(authorization.FallbackPolicy.Requirements,
            requirement => requirement is ClaimsAuthorizationRequirement);

        var writePolicy = authorization.GetPolicy(BespokeAuthorizationPolicies.Write);
        Assert.NotNull(writePolicy);
        Assert.Contains(writePolicy.Requirements, requirement =>
            requirement is ClaimsAuthorizationRequirement claim
            && claim.ClaimType == BespokeAuthorizationPermissions.ClaimType
            && claim.AllowedValues is not null
            && claim.AllowedValues.Contains(BespokeAuthorizationPermissions.Write));

        var readPolicy = authorization.GetPolicy(BespokeAuthorizationPolicies.ReadApproved);
        Assert.NotNull(readPolicy);
        Assert.Contains(readPolicy.Requirements, requirement =>
            requirement is ClaimsAuthorizationRequirement claim
            && claim.ClaimType == BespokeAuthorizationPermissions.ClaimType
            && claim.AllowedValues is not null
            && claim.AllowedValues.Contains(BespokeAuthorizationPermissions.Read));
        Assert.Contains(readPolicy.Requirements, requirement => requirement is HttpGetRequirement);

        var productReadPolicy = authorization.GetPolicy(BespokeAuthorizationPolicies.ProductReadApproved);
        Assert.NotNull(productReadPolicy);
        Assert.Contains(productReadPolicy.Requirements, requirement =>
            requirement is ClaimsAuthorizationRequirement claim
            && claim.ClaimType == BespokeAuthorizationPermissions.ClaimType
            && claim.AllowedValues is not null
            && claim.AllowedValues.Contains(BespokeAuthorizationPermissions.ProductRead));
    }

    [Fact]
    public void ConsiderUsingAuthentication_WhenDisabled_DoesNotThrow()
    {
        var builder = WebApplication.CreateBuilder();
        builder.Configuration.AddInMemoryCollection(new Dictionary<string, string?>
        {
            ["Authentication:DisableAuthentication"] = "true"
        });
        builder.Services.ConsiderAddingAuthentication(builder.Configuration);

        using var app = builder.Build();

        var returned = app.ConsiderUsingAuthentication();

        Assert.Same(app, returned);
    }

    [Fact]
    public void ConsiderUsingAuthentication_WhenEnabled_DoesNotThrow()
    {
        var builder = WebApplication.CreateBuilder();
        builder.Configuration.AddInMemoryCollection(new Dictionary<string, string?>
        {
            ["Authentication:DisableAuthentication"] = "false",
            ["Authentication:Authority"] = "http://localhost:9080/realms/example",
            ["Authentication:Audience"] = "example-api",
            ["Authentication:RequireHttpsMetadata"] = "false"
        });
        builder.Services.AddLogging();
        builder.Services.ConsiderAddingAuthentication(builder.Configuration);

        using var app = builder.Build();

        var returned = app.ConsiderUsingAuthentication();

        Assert.Same(app, returned);
    }
}