using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authorization.Infrastructure;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using RedShirt.Example.Api.Authorization;
using RedShirt.Example.Api.Authorization.Constants;
using RedShirt.Example.Api.Authorization.Requirements;
using RedShirt.Example.Api.Authorization.ResourceScoping.Customer;
using RedShirt.Example.Api.Extensions;
using System.Security.Claims;

namespace RedShirt.Example.Api.UnitTests.Tests.Extensions;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class AuthorizationServiceCollectionExtensionsTests
{
    private static ClaimsPrincipal PrincipalWithRoles(params string[] roles)
    {
        var identity = new ClaimsIdentity(
            roles.Select(role => new Claim("role", role)),
            "test",
            "preferred_username",
            "role");

        return new ClaimsPrincipal(identity);
    }

    private static bool HasPermissionClaimRequirement(AuthorizationPolicy policy, string permission)
    {
        return policy.Requirements.OfType<ClaimsAuthorizationRequirement>().Any(requirement =>
            requirement.ClaimType == BespokeAuthorizationPermissions.ClaimType
            && requirement.AllowedValues is not null
            && requirement.AllowedValues.Contains(permission));
    }

    [Fact]
    public void AddApiAuthorizationPolicies_RegistersPermissionPoliciesAndTransformation()
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddApiAuthorizationPolicies();

        using var provider = services.BuildServiceProvider();

        Assert.Contains(provider.GetServices<IClaimsTransformation>(),
            transformation => transformation is BespokeRolePermissionClaimsTransformation);
        Assert.Contains(provider.GetServices<IAuthorizationHandler>(),
            handler => handler is HttpGetAuthorizationHandler);
        Assert.Contains(provider.GetServices<IAuthorizationHandler>(),
            handler => handler is CustomerScopedResourceEnforcerHandler);
        Assert.NotNull(provider.GetService<ICustomerScopedResourceEnforcer>());

        var authorization = provider.GetRequiredService<IOptions<AuthorizationOptions>>().Value;

        var writePolicy = authorization.GetPolicy(BespokeAuthorizationPolicies.Write);
        Assert.NotNull(writePolicy);
        Assert.True(HasPermissionClaimRequirement(writePolicy, BespokeAuthorizationPermissions.Write));
        Assert.DoesNotContain(writePolicy.Requirements, requirement => requirement is HttpGetRequirement);

        var readPolicy = authorization.GetPolicy(BespokeAuthorizationPolicies.ReadApproved);
        Assert.NotNull(readPolicy);
        Assert.True(HasPermissionClaimRequirement(readPolicy, BespokeAuthorizationPermissions.Read));
        Assert.Contains(readPolicy.Requirements, requirement => requirement is HttpGetRequirement);

        var productWrite = authorization.GetPolicy(BespokeAuthorizationPolicies.ProductWrite);
        Assert.NotNull(productWrite);
        Assert.True(HasPermissionClaimRequirement(productWrite, BespokeAuthorizationPermissions.ProductWrite));

        var productRead = authorization.GetPolicy(BespokeAuthorizationPolicies.ProductReadApproved);
        Assert.NotNull(productRead);
        Assert.True(HasPermissionClaimRequirement(productRead, BespokeAuthorizationPermissions.ProductRead));
        Assert.Contains(productRead.Requirements, requirement => requirement is HttpGetRequirement);

        var orderWrite = authorization.GetPolicy(BespokeAuthorizationPolicies.OrderWrite);
        Assert.NotNull(orderWrite);
        Assert.True(HasPermissionClaimRequirement(orderWrite, BespokeAuthorizationPermissions.OrderWrite));

        var orderRead = authorization.GetPolicy(BespokeAuthorizationPolicies.OrderReadApproved);
        Assert.NotNull(orderRead);
        Assert.True(HasPermissionClaimRequirement(orderRead, BespokeAuthorizationPermissions.OrderRead));
        Assert.Contains(orderRead.Requirements, requirement => requirement is HttpGetRequirement);

        Assert.Same(writePolicy, authorization.FallbackPolicy);

        var scopedPolicy = authorization.GetPolicy(BespokeAuthorizationPolicies.CustomerScoped);
        Assert.NotNull(scopedPolicy);
        Assert.Contains(scopedPolicy.Requirements, requirement => requirement is CustomerScopedResourceRequirement);
    }

    [Fact]
    public async Task AuthorizeAsync_Analyst_DeniesProductReadApprovedOnPost()
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddApiAuthorizationPolicies();

        using var provider = services.BuildServiceProvider();
        var transformation = provider.GetRequiredService<IClaimsTransformation>();
        var authorization = provider.GetRequiredService<IAuthorizationService>();

        var user = await transformation.TransformAsync(PrincipalWithRoles(BespokeAuthorizationRoles.Analyst));
        var httpContext = new DefaultHttpContext();
        httpContext.Request.Method = HttpMethods.Post;

        var read = await authorization.AuthorizeAsync(user, httpContext,
            BespokeAuthorizationPolicies.ProductReadApproved);

        Assert.False(read.Succeeded);
    }

    [Theory]
    [InlineData(BespokeAuthorizationRoles.Analyst, BespokeAuthorizationPolicies.ProductReadApproved, true)]
    [InlineData(BespokeAuthorizationRoles.Analyst, BespokeAuthorizationPolicies.ProductWrite, false)]
    [InlineData(BespokeAuthorizationRoles.Analyst, BespokeAuthorizationPolicies.OrderReadApproved, false)]
    [InlineData(BespokeAuthorizationRoles.Analyst, BespokeAuthorizationPolicies.Write, false)]
    [InlineData(BespokeAuthorizationRoles.Billing, BespokeAuthorizationPolicies.OrderReadApproved, true)]
    [InlineData(BespokeAuthorizationRoles.Billing, BespokeAuthorizationPolicies.OrderWrite, true)]
    [InlineData(BespokeAuthorizationRoles.Billing, BespokeAuthorizationPolicies.ProductReadApproved, false)]
    [InlineData(BespokeAuthorizationRoles.Billing, BespokeAuthorizationPolicies.Write, false)]
    [InlineData(BespokeAuthorizationRoles.Developer, BespokeAuthorizationPolicies.Write, true)]
    [InlineData(BespokeAuthorizationRoles.Developer, BespokeAuthorizationPolicies.ReadApproved, true)]
    [InlineData(BespokeAuthorizationRoles.Developer, BespokeAuthorizationPolicies.ProductReadApproved, true)]
    [InlineData(BespokeAuthorizationRoles.Developer, BespokeAuthorizationPolicies.ProductWrite, true)]
    [InlineData(BespokeAuthorizationRoles.Developer, BespokeAuthorizationPolicies.OrderReadApproved, true)]
    [InlineData(BespokeAuthorizationRoles.Developer, BespokeAuthorizationPolicies.OrderWrite, true)]
    [InlineData(BespokeAuthorizationRoles.Admin, BespokeAuthorizationPolicies.Write, true)]
    [InlineData(BespokeAuthorizationRoles.Admin, BespokeAuthorizationPolicies.ProductWrite, true)]
    [InlineData(BespokeAuthorizationRoles.UploadValidator, BespokeAuthorizationPolicies.UploadInternalDetailsApproved,
        true)]
    [InlineData(BespokeAuthorizationRoles.Developer, BespokeAuthorizationPolicies.UploadInternalDetailsApproved, false)]
    [InlineData(BespokeAuthorizationRoles.Admin, BespokeAuthorizationPolicies.UploadInternalDetailsApproved, true)]
    public async Task AuthorizeAsync_RolePolicies(string role, string policy, bool expected)
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddApiAuthorizationPolicies();

        using var provider = services.BuildServiceProvider();
        var transformation = provider.GetRequiredService<IClaimsTransformation>();
        var authorization = provider.GetRequiredService<IAuthorizationService>();

        var user = await transformation.TransformAsync(PrincipalWithRoles(role));
        var httpContext = new DefaultHttpContext();
        httpContext.Request.Method = HttpMethods.Get;

        var result = await authorization.AuthorizeAsync(user, httpContext, policy);

        Assert.Equal(expected, result.Succeeded);
    }
}