using Moq;
using RedShirt.Api.Example.Connectors.Foo.Core.Exceptions;
using RedShirt.Api.Example.Connectors.Foo.Implementation.Clients;
using RedShirt.Api.Example.Connectors.Foo.Implementation.Constants;
using RedShirt.Api.Example.Connectors.Foo.Implementation.Services.Resilience;
using System.Net;

namespace RedShirt.Api.Example.Connectors.Foo.Implementation.UnitTests.Tests.Clients;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class FooApiClientHandlerTests
{
    [Fact]
    public async Task SendAsync_AddsApiKeyHeader_FromRetryWrapper()
    {
        var inner = new RecordingInnerHandler();
        var retry = new Mock<IFooApiRequestHandlerRetryWrapperService>(MockBehavior.Strict);
        retry
            .Setup(r => r.GetApiKeyAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync("secret-key");
        retry
            .Setup(r => r.ExecuteAsync(It.IsAny<Func<CancellationToken, Task<HttpResponseMessage>>>(),
                It.IsAny<CancellationToken>()))
            .Returns<Func<CancellationToken, Task<HttpResponseMessage>>,
                CancellationToken>((func, token) => func(token));

        var handler = new FooApiClientHandler(retry.Object)
        {
            InnerHandler = inner
        };
        using var invoker = new HttpMessageInvoker(handler);

        using var response = await invoker.SendAsync(
            new HttpRequestMessage(HttpMethod.Get, "http://foo.test/api/foo/1"),
            TestContext.Current.CancellationToken);

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        Assert.True(inner.LastRequest!.Headers.TryGetValues(FooApiHeaderNames.ApiKey, out var values));
        Assert.Equal(["secret-key"], values);
        retry.VerifyAll();
    }

    [Fact]
    public async Task SendAsync_ThrowsFooUnauthorized_On401()
    {
        var inner = new RecordingInnerHandler {StatusCode = HttpStatusCode.Unauthorized};
        var retry = new Mock<IFooApiRequestHandlerRetryWrapperService>(MockBehavior.Strict);
        retry
            .Setup(r => r.GetApiKeyAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync("secret-key");
        retry
            .Setup(r => r.ExecuteAsync(It.IsAny<Func<CancellationToken, Task<HttpResponseMessage>>>(),
                It.IsAny<CancellationToken>()))
            .Returns<Func<CancellationToken, Task<HttpResponseMessage>>,
                CancellationToken>((func, token) => func(token));

        var handler = new FooApiClientHandler(retry.Object)
        {
            InnerHandler = inner
        };
        using var invoker = new HttpMessageInvoker(handler);

        await Assert.ThrowsAsync<FooUnauthorizedException>(() =>
            invoker.SendAsync(
                new HttpRequestMessage(HttpMethod.Get, "http://foo.test/api/foo/1"),
                TestContext.Current.CancellationToken));
    }

    private sealed class RecordingInnerHandler : HttpMessageHandler
    {
        public HttpRequestMessage? LastRequest { get; private set; }
        public HttpStatusCode StatusCode { get; set; } = HttpStatusCode.OK;

        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,
            CancellationToken cancellationToken)
        {
            LastRequest = request;
            return Task.FromResult(new HttpResponseMessage(StatusCode));
        }
    }
}