using Moq;
using RedShirt.Example.Api.Connectors.Foo.Core.Models;
using RedShirt.Example.Api.Connectors.Foo.Implementation.Clients;
using RedShirt.Example.Api.Connectors.Foo.Implementation.Factories;
using RedShirt.Example.Api.Connectors.Foo.Implementation.Services;
using RedShirt.Example.Api.Connectors.Foo.Implementation.Services.Resilience;

namespace RedShirt.Example.Api.Connectors.Foo.Implementation.UnitTests.Tests.Services;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class FooConnectorTests
{
    [Fact]
    public async Task CreateAsync_RunsThroughRetryWrapper_AndReturnsClientResult()
    {
        var request = new CreateFooConnectorRequest {Name = "widget"};
        var expected = new CreateFooConnectorResponse {Id = 9, Name = "widget"};

        var client = new Mock<IFooApiClient>(MockBehavior.Strict);
        client
            .Setup(c => c.CreateFooAsync(request, It.IsAny<CancellationToken>()))
            .ReturnsAsync(expected);

        var factory = new Mock<IFooApiClientFactory>(MockBehavior.Strict);
        factory.Setup(f => f.CreateFooApiClient()).Returns(client.Object);

        var retry = new Mock<IFooRetryWrapperService>(MockBehavior.Strict);
        retry
            .Setup(r => r.RunAsync(
                It.IsAny<Func<CancellationToken, Task<CreateFooConnectorResponse>>>(),
                It.IsAny<CancellationToken>()))
            .Returns<Func<CancellationToken, Task<CreateFooConnectorResponse>>, CancellationToken>((func, token) =>
                func(token));

        var connector = new FooConnector(factory.Object, retry.Object);

        var result = await connector.CreateAsync(request, TestContext.Current.CancellationToken);

        Assert.Same(expected, result);
        factory.Verify(f => f.CreateFooApiClient(), Times.Once);
        client.VerifyAll();
        retry.VerifyAll();
    }

    [Fact]
    public async Task CreateAsync_ThrowsArgumentNull_WhenRequestIsNull()
    {
        var connector = new FooConnector(
            new Mock<IFooApiClientFactory>().Object,
            new Mock<IFooRetryWrapperService>().Object);

        await Assert.ThrowsAsync<ArgumentNullException>(() =>
            connector.CreateAsync(null!, TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task GetByIdAsync_RunsThroughRetryWrapper_AndReturnsClientResult()
    {
        var expected = new GetFooConnectorResponse {Id = 3, Name = "Foo-3"};

        var client = new Mock<IFooApiClient>(MockBehavior.Strict);
        client
            .Setup(c => c.GetFooByIdAsync(3, It.IsAny<CancellationToken>()))
            .ReturnsAsync(expected);

        var factory = new Mock<IFooApiClientFactory>(MockBehavior.Strict);
        factory.Setup(f => f.CreateFooApiClient()).Returns(client.Object);

        var retry = new Mock<IFooRetryWrapperService>(MockBehavior.Strict);
        retry
            .Setup(r => r.RunAsync(
                It.IsAny<Func<CancellationToken, Task<GetFooConnectorResponse>>>(),
                It.IsAny<CancellationToken>()))
            .Returns<Func<CancellationToken, Task<GetFooConnectorResponse>>, CancellationToken>((func, token) =>
                func(token));

        var connector = new FooConnector(factory.Object, retry.Object);

        var result = await connector.GetByIdAsync(3, TestContext.Current.CancellationToken);

        Assert.Same(expected, result);
        factory.Verify(f => f.CreateFooApiClient(), Times.Once);
        client.VerifyAll();
        retry.VerifyAll();
    }
}