using Microsoft.Extensions.Options;
using Moq;
using RedShirt.Api.Example.Connectors.Bar.Implementation.Clients;
using RedShirt.Api.Example.Connectors.Bar.Implementation.Factories;

namespace RedShirt.Api.Example.Connectors.Bar.Implementation.UnitTests.Tests.Factories;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class BarApiClientFactoryTests
{
    [Fact]
    public void CreateBarApiClient_UsesNamedHttpClient_AndConfiguredBaseUrl()
    {
        using var httpClient = new HttpClient();
        var httpClientFactory = new Mock<IHttpClientFactory>(MockBehavior.Strict);
        httpClientFactory
            .Setup(f => f.CreateClient(nameof(BarApiClient)))
            .Returns(httpClient);

        var sut = new BarApiClientFactory(
            httpClientFactory.Object,
            Options.Create(new BarApiClientFactory.ConfigurationModel
            {
                BaseUrl = "http://bar.example"
            }));

        var client = sut.CreateBarApiClient();

        Assert.IsType<BarApiClient>(client);
        httpClientFactory.Verify(f => f.CreateClient(nameof(BarApiClient)), Times.Once);
        httpClientFactory.VerifyNoOtherCalls();
    }
}