<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AWSSDK.S3" Version="4.0.14.1"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\RedShirt.Example.Api.Common.Aws\RedShirt.Example.Api.Common.Aws.csproj"/>
        <ProjectReference Include="..\RedShirt.Example.Api.Common.FileStorage\RedShirt.Example.Api.Common.FileStorage.csproj"/>
    </ItemGroup>

</Project>
