using RedShirt.Example.Api.Common.Analyzers.Database.Abstractions.Attributes;
using RedShirt.Example.Api.DataStores.Constants;
using RedShirt.Example.Api.DataStores.Order.Models;
using RedShirt.Example.Api.DataStores.Order.Models.Generated;
using System.Reflection;

namespace RedShirt.Example.Api.DataStores.Order.UnitTests.Tests.Models;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class OrderDtoTests
{
    [Fact]
    public void IOrderService_IsPublicContract()
    {
        Assert.True(typeof(IOrderService).IsInterface);
        Assert.True(typeof(IOrderService).IsPublic);

        var methods = typeof(IOrderService)
            .GetMethods()
            .Select(m => m.Name)
            .OrderBy(n => n)
            .ToArray();

        Assert.Equal(
            ["DeleteAsync", "GetByIdAsync", "PatchAsync", "PostAsync", "PutAsync", "SearchAsync"],
            methods);
    }

    [Fact]
    public void OrderDto_HasExpectedTableMetadata()
    {
        var attribute = typeof(OrderDto).GetCustomAttribute<DbTableAttribute>();

        Assert.NotNull(attribute);
        Assert.Equal("Order", attribute!.TableName);
        Assert.Equal(DatabaseConstants.PrimaryDatabaseConnectionStringName, attribute.ConnectionStringName);
    }

    [Fact]
    public void OrderDto_MarksTotalAmountAsStoredAsDecimal()
    {
        var property = typeof(OrderDto).GetProperty(nameof(OrderDto.TotalAmount));

        Assert.NotNull(property);
        Assert.NotNull(property!.GetCustomAttribute<StoredAsDecimalAttribute>());
    }
}