using RedShirt.Example.Api.DataStores.Product.Core.Models;
using RedShirt.Example.Api.DataStores.Product.Core.Services;

namespace RedShirt.Example.Api.DataStores.Product.Core.UnitTests.Tests.Models;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class ProductDtoTests
{
    [Fact]
    public void IProductService_ReturnsInternalDto()
    {
        var getById = typeof(IProductService).GetMethod(nameof(IProductService.GetByIdAsync));

        Assert.NotNull(getById);
        Assert.Equal(typeof(Task<ProductInternalDto>), getById!.ReturnType);
    }

    [Fact]
    public void ProductDto_CanBeConstructedWithRequiredFields()
    {
        var id = Guid.NewGuid();
        var created = DateTime.UtcNow.AddHours(-1);
        var updated = DateTime.UtcNow;

        var dto = new ProductDto
        {
            Id = id,
            CreatedAtUtc = created,
            UpdatedAtUtc = updated,
            Sku = "SKU-1",
            Name = "Widget",
            Price = "12.34"
        };

        Assert.Equal(id, dto.Id);
        Assert.Equal(created, dto.CreatedAtUtc);
        Assert.Equal(updated, dto.UpdatedAtUtc);
        Assert.Equal("SKU-1", dto.Sku);
        Assert.Equal("Widget", dto.Name);
        Assert.Equal("12.34", dto.Price);
    }

    [Fact]
    public void ProductInternalDto_MapsToPublicProductDto()
    {
        var internalDto = new ProductInternalDto
        {
            Id = Guid.NewGuid(),
            CreatedAtUtc = DateTime.UtcNow.AddDays(-1),
            UpdatedAtUtc = DateTime.UtcNow,
            Sku = "SKU-1",
            Name = "Widget",
            Price = 12.34m
        };

        var dto = internalDto.ToDto();

        Assert.Equal(internalDto.Id, dto.Id);
        Assert.Equal(internalDto.Sku, dto.Sku);
        Assert.Equal(internalDto.Name, dto.Name);
        Assert.Equal("12.34", dto.Price);
    }
}