using RedShirt.Example.Api.DataStores.Product.Core.Models;

namespace RedShirt.Example.Api.DataStores.Product.Core.UnitTests.Tests.Models;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class ProductDtoTests
{
    [Fact]
    public void ProductDto_CanBeConstructedWithRequiredFields()
    {
        var id = Guid.NewGuid();
        var created = DateTime.UtcNow.AddHours(-1);
        var updated = DateTime.UtcNow;

        var dto = new ProductDto
        {
            Id = id,
            CreatedAtUtc = created,
            UpdatedAtUtc = updated,
            Sku = "SKU-1",
            Name = "Widget",
            Price = "12.34"
        };

        Assert.Equal(id, dto.Id);
        Assert.Equal(created, dto.CreatedAtUtc);
        Assert.Equal(updated, dto.UpdatedAtUtc);
        Assert.Equal("SKU-1", dto.Sku);
        Assert.Equal("Widget", dto.Name);
        Assert.Equal("12.34", dto.Price);
    }
}