using RedShirt.Example.Api.Common.Analyzers.Database.Abstractions.Attributes;
using RedShirt.Example.Api.DataStores.Constants;
using RedShirt.Example.Api.DataStores.Product.Core.Models;
using System.Reflection;

namespace RedShirt.Example.Api.DataStores.Product.Core.UnitTests.Tests.Models;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class ProductDtoTests
{
    [Fact]
    public void ProductDto_CanBeConstructedWithRequiredFields()
    {
        var id = Guid.NewGuid();
        var created = DateTime.UtcNow.AddHours(-1);
        var updated = DateTime.UtcNow;

        var dto = new ProductDto
        {
            Id = id,
            CreatedAtUtc = created,
            UpdatedAtUtc = updated,
            Sku = "SKU-1",
            Name = "Widget",
            Price = "12.34"
        };

        Assert.Equal(id, dto.Id);
        Assert.Equal(created, dto.CreatedAtUtc);
        Assert.Equal(updated, dto.UpdatedAtUtc);
        Assert.Equal("SKU-1", dto.Sku);
        Assert.Equal("Widget", dto.Name);
        Assert.Equal("12.34", dto.Price);
    }

    [Fact]
    public void ProductDto_HasExpectedTableMetadata()
    {
        var attribute = typeof(ProductDto).GetCustomAttribute<DbTableAttribute>();

        Assert.NotNull(attribute);
        Assert.Equal("Product", attribute!.TableName);
        Assert.Equal(DatabaseConstants.PrimaryDatabaseConnectionStringName, attribute.ConnectionStringName);
    }

    [Fact]
    public void ProductDto_MarksKeyAndTimestamps()
    {
        Assert.NotNull(typeof(ProductDto).GetProperty(nameof(ProductDto.Id))!
            .GetCustomAttribute<DbKeyAttribute>());
        Assert.NotNull(typeof(ProductDto).GetProperty(nameof(ProductDto.CreatedAtUtc))!
            .GetCustomAttribute<CreatedAtPropertyAttribute>());
        Assert.NotNull(typeof(ProductDto).GetProperty(nameof(ProductDto.UpdatedAtUtc))!
            .GetCustomAttribute<UpdatedAtPropertyAttribute>());
    }

    [Fact]
    public void ProductDto_MarksPriceAsStoredAsDecimal()
    {
        var property = typeof(ProductDto).GetProperty(nameof(ProductDto.Price));

        Assert.NotNull(property);
        Assert.NotNull(property!.GetCustomAttribute<StoredAsDecimalAttribute>());
    }
}