using Moq;
using RedShirt.Api.Example.Connectors.Bar.Core.Models;
using RedShirt.Api.Example.Connectors.Bar.Implementation.Clients;
using RedShirt.Api.Example.Connectors.Bar.Implementation.Factories;
using RedShirt.Api.Example.Connectors.Bar.Implementation.Services;
using RedShirt.Api.Example.Connectors.Bar.Implementation.Services.Resilience;

namespace RedShirt.Api.Example.Connectors.Bar.Implementation.UnitTests.Tests.Services;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class BarConnectorTests
{
    [Fact]
    public async Task CreateAsync_RunsThroughRetryWrapper_AndReturnsClientResult()
    {
        var request = new CreateBarConnectorRequest {Name = "widget"};
        var expected = new CreateBarConnectorResponse {Id = 9, Name = "widget"};

        var client = new Mock<IBarApiClient>(MockBehavior.Strict);
        client
            .Setup(c => c.CreateBarAsync(request, It.IsAny<CancellationToken>()))
            .ReturnsAsync(expected);

        var factory = new Mock<IBarApiClientFactory>(MockBehavior.Strict);
        factory.Setup(f => f.CreateBarApiClient()).Returns(client.Object);

        var retry = new Mock<IBarRetryWrapperService>(MockBehavior.Strict);
        retry
            .Setup(r => r.RunAsync(
                It.IsAny<Func<CancellationToken, Task<CreateBarConnectorResponse>>>(),
                It.IsAny<CancellationToken>()))
            .Returns<Func<CancellationToken, Task<CreateBarConnectorResponse>>, CancellationToken>((func, token) =>
                func(token));

        var connector = new BarConnector(factory.Object, retry.Object);

        var result = await connector.CreateAsync(request, TestContext.Current.CancellationToken);

        Assert.Same(expected, result);
        factory.Verify(f => f.CreateBarApiClient(), Times.Once);
        client.VerifyAll();
        retry.VerifyAll();
    }

    [Fact]
    public async Task CreateAsync_ThrowsArgumentNull_WhenRequestIsNull()
    {
        var connector = new BarConnector(
            new Mock<IBarApiClientFactory>().Object,
            new Mock<IBarRetryWrapperService>().Object);

        await Assert.ThrowsAsync<ArgumentNullException>(() =>
            connector.CreateAsync(null!, TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task GetByIdAsync_RunsThroughRetryWrapper_AndReturnsClientResult()
    {
        var expected = new GetBarConnectorResponse {Id = 3, Name = "Bar-3"};

        var client = new Mock<IBarApiClient>(MockBehavior.Strict);
        client
            .Setup(c => c.GetBarByIdAsync(3, It.IsAny<CancellationToken>()))
            .ReturnsAsync(expected);

        var factory = new Mock<IBarApiClientFactory>(MockBehavior.Strict);
        factory.Setup(f => f.CreateBarApiClient()).Returns(client.Object);

        var retry = new Mock<IBarRetryWrapperService>(MockBehavior.Strict);
        retry
            .Setup(r => r.RunAsync(
                It.IsAny<Func<CancellationToken, Task<GetBarConnectorResponse>>>(),
                It.IsAny<CancellationToken>()))
            .Returns<Func<CancellationToken, Task<GetBarConnectorResponse>>, CancellationToken>((func, token) =>
                func(token));

        var connector = new BarConnector(factory.Object, retry.Object);

        var result = await connector.GetByIdAsync(3, TestContext.Current.CancellationToken);

        Assert.Same(expected, result);
        factory.Verify(f => f.CreateBarApiClient(), Times.Once);
        client.VerifyAll();
        retry.VerifyAll();
    }
}
