using RedShirt.Example.Api.Connectors.Foo.Core.Exceptions;
using RedShirt.Example.Api.Connectors.Foo.Core.Models;
using RedShirt.Example.Api.Connectors.Foo.Implementation.Clients;
using System.Net;
using System.Text;

namespace RedShirt.Example.Api.Connectors.Foo.Implementation.UnitTests.Tests.Clients;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class FooApiClientTests
{
    private static FooApiClient CreateClient(StubHandler handler, string baseUrl = "http://foo.test/")
    {
        return new FooApiClient(new HttpClient(handler), baseUrl);
    }

    [Fact]
    public async Task CreateFooAsync_PostsJson_AndMapsResponse()
    {
        var handler = new StubHandler(_ => new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new StringContent("""{"Id":11,"Name":"widget"}""", Encoding.UTF8, "application/json")
        });
        var client = CreateClient(handler);

        var result = await client.CreateFooAsync(
            new CreateFooConnectorRequest {Name = "widget"},
            TestContext.Current.CancellationToken);

        Assert.Equal(11, result.Id);
        Assert.Equal("widget", result.Name);
        Assert.Equal(HttpMethod.Post, handler.LastRequest!.Method);
        Assert.Equal("http://foo.test/api/foo", handler.LastRequest.RequestUri!.ToString());
    }

    [Fact]
    public async Task CreateFooAsync_ThrowsHttpRequestException_OnNonSuccess()
    {
        var handler = new StubHandler(_ => new HttpResponseMessage(HttpStatusCode.BadRequest));
        var client = CreateClient(handler);

        var ex = await Assert.ThrowsAsync<HttpRequestException>(() =>
            client.CreateFooAsync(
                new CreateFooConnectorRequest {Name = "widget"},
                TestContext.Current.CancellationToken));

        Assert.Equal(HttpStatusCode.BadRequest, ex.StatusCode);
    }

    [Fact]
    public async Task GetFooByIdAsync_GetsJson_AndMapsResponse()
    {
        var handler = new StubHandler(_ => new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new StringContent("""{"Id":5,"Name":"Foo-5"}""", Encoding.UTF8, "application/json")
        });
        var client = CreateClient(handler);

        var result = await client.GetFooByIdAsync(5, TestContext.Current.CancellationToken);

        Assert.Equal(5, result.Id);
        Assert.Equal("Foo-5", result.Name);
        Assert.Equal(HttpMethod.Get, handler.LastRequest!.Method);
        Assert.Equal("http://foo.test/api/foo/5", handler.LastRequest.RequestUri!.ToString());
    }

    [Fact]
    public async Task GetFooByIdAsync_ThrowsFooRecordNotFound_On404()
    {
        var handler = new StubHandler(_ => new HttpResponseMessage(HttpStatusCode.NotFound));
        var client = CreateClient(handler);

        var ex = await Assert.ThrowsAsync<FooRecordNotFoundException>(() =>
            client.GetFooByIdAsync(404, TestContext.Current.CancellationToken));

        Assert.Equal(404, ex.Id);
    }

    [Fact]
    public async Task GetFooByIdAsync_ThrowsHttpRequestException_OnOtherErrors()
    {
        var handler = new StubHandler(_ => new HttpResponseMessage(HttpStatusCode.InternalServerError));
        var client = CreateClient(handler);

        var ex = await Assert.ThrowsAsync<HttpRequestException>(() =>
            client.GetFooByIdAsync(1, TestContext.Current.CancellationToken));

        Assert.Equal(HttpStatusCode.InternalServerError, ex.StatusCode);
    }

    private sealed class StubHandler(Func<HttpRequestMessage, HttpResponseMessage> responder) : HttpMessageHandler
    {
        public HttpRequestMessage? LastRequest { get; private set; }

        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,
            CancellationToken cancellationToken)
        {
            LastRequest = request;
            return Task.FromResult(responder(request));
        }
    }
}