using Moq;
using RedShirt.Example.Api.Common.Distributed.Services.Abstractions;
using RedShirt.Example.Api.DataStores.Common.DapperMySql.Factories;
using RedShirt.Example.Api.DataStores.Common.DapperMySql.Services;
using RedShirt.Example.Api.DataStores.Common.DapperMySql.Services.Resilience;
using RedShirt.Example.Api.DataStores.Constants;
using RedShirt.Example.Api.DataStores.Order.Models.Generated;
using System.Data;
using System.Text.Json;

namespace RedShirt.Example.Api.DataStores.Order.UnitTests.Tests.Repositories;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class MariaDbOrderRepositoryTests
{
    private static OrderInternalDto CreateDto(
        Guid? id = null,
        DateTime? updatedAtUtc = null)
    {
        var updated = updatedAtUtc ?? DateTime.UtcNow;
        return new OrderInternalDto
        {
            Id = id ?? Guid.NewGuid(),
            CreatedAtUtc = updated.AddDays(-1),
            UpdatedAtUtc = updated,
            CustomerId = Guid.NewGuid(),
            Status = "Pending",
            TotalAmount = 10.00m,
            TotalPrice = null
        };
    }

    private static OrderEntity CreateEntity(
        Guid? id = null,
        DateTime? updatedAtUtc = null)
    {
        var dto = CreateDto(id, updatedAtUtc);
        return new OrderEntity
        {
            Id = dto.Id,
            CreatedAtUtc = dto.CreatedAtUtc,
            UpdatedAtUtc = dto.UpdatedAtUtc,
            CustomerId = dto.CustomerId,
            Status = dto.Status,
            TotalAmount = dto.TotalAmount,
            TotalPrice = dto.TotalPrice
        };
    }

    private static OrderServiceSearchRequest CreateSearchRequest(
        int pageSize = 10,
        Guid? customerId = null,
        string? status = null,
        decimal? totalAmount = null)
    {
        return new OrderServiceSearchRequest
        {
            PageSize = pageSize,
            CreatedBeforeUtc = null,
            CreatedAfterUtc = null,
            UpdatedBeforeUtc = null,
            UpdatedAfterUtc = null,
            CustomerId = customerId,
            Status = status,
            StatusContains = null,
            TotalAmount = totalAmount,
            TotalAmountGreaterThan = null,
            TotalAmountLessThan = null,
            TotalPrice = null,
            TotalPriceGreaterThan = null,
            TotalPriceLessThan = null,
            TotalPriceIsNull = false
        };
    }

    private static MariaDbOrderRepository CreateRepository(
        IRemoteCacheService? cacheService = null,
        IGenericMySqlDtoStorage<OrderEntity, Guid>? storage = null,
        ISqlConnectionFactory? sqlConnectionFactory = null,
        IMySqlRetryWrapperService? retryWrapperService = null)
    {
        var storageMock = storage is null ? new Mock<IGenericMySqlDtoStorage<OrderEntity, Guid>>() : null;
        storageMock?.Setup(s => s.GetTableName()).Returns("Order");

        var factoryMock = sqlConnectionFactory is null ? new Mock<ISqlConnectionFactory>() : null;
        factoryMock?
            .Setup(f => f.GetMySqlConnectionAsync(
                DatabaseConstants.PrimaryDatabaseConnectionStringName,
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(new Mock<IDbConnection>().Object);

        return new MariaDbOrderRepository(
            cacheService ?? new Mock<IRemoteCacheService>().Object,
            storage ?? storageMock!.Object,
            sqlConnectionFactory ?? factoryMock!.Object,
            retryWrapperService ?? new Mock<IMySqlRetryWrapperService>().Object);
    }

    private static Mock<IMySqlRetryWrapperService> CreateRetryReturning(IEnumerable<OrderEntity> records)
    {
        var retry = new Mock<IMySqlRetryWrapperService>();
        retry
            .Setup(r => r.RunAsync(
                It.IsAny<Func<CancellationToken, Task<IEnumerable<OrderEntity>>>>(),
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(records);
        return retry;
    }

    [Fact]
    public async Task DeleteAsync_DelegatesToStorage_WithPrimaryConnection()
    {
        var id = Guid.NewGuid();
        var storage = new Mock<IGenericMySqlDtoStorage<OrderEntity, Guid>>();
        storage
            .Setup(s => s.DeleteByKeyAsync(
                DatabaseConstants.PrimaryDatabaseConnectionStringName,
                id,
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(true);
        var repository = CreateRepository(storage: storage.Object);

        var result = await repository.DeleteAsync(id, TestContext.Current.CancellationToken);

        Assert.True(result);
        storage.Verify(s => s.DeleteByKeyAsync(
            DatabaseConstants.PrimaryDatabaseConnectionStringName,
            id,
            TestContext.Current.CancellationToken), Times.Once);
    }

    [Fact]
    public async Task GetByIdAsync_DelegatesToStorage_AndReturnsDto()
    {
        var entity = CreateEntity();
        var storage = new Mock<IGenericMySqlDtoStorage<OrderEntity, Guid>>();
        storage
            .Setup(s => s.GetByKeyAsync(
                DatabaseConstants.PrimaryDatabaseConnectionStringName,
                entity.Id,
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(entity);
        var repository = CreateRepository(storage: storage.Object);

        var result = await repository.GetByIdAsync(entity.Id, TestContext.Current.CancellationToken);

        Assert.NotNull(result);
        Assert.Equal(entity.Id, result.Id);
        Assert.Equal(entity.Status, result.Status);
        Assert.Equal(entity.TotalAmount, result.TotalAmount);
        storage.Verify(s => s.GetByKeyAsync(
            DatabaseConstants.PrimaryDatabaseConnectionStringName,
            entity.Id,
            TestContext.Current.CancellationToken), Times.Once);
    }

    [Fact]
    public async Task SearchAsync_ReturnsRecords_WithoutContinuation_WhenPageNotFull()
    {
        var records = new List<OrderEntity> {CreateEntity(), CreateEntity()};
        var repository = CreateRepository(retryWrapperService: CreateRetryReturning(records).Object);

        var result = await repository.SearchAsync(
            CreateSearchRequest(),
            null,
            TestContext.Current.CancellationToken);

        Assert.Equal(2, result.Records.Count);
        Assert.Null(result.ContinuationToken);
    }

    [Fact]
    public async Task SearchAsync_StoresContinuation_WhenPageIsFull()
    {
        var records = Enumerable.Range(0, 10).Select(_ => CreateEntity()).ToList();
        var cache = new Mock<IRemoteCacheService>();
        string? storedKey = null;
        string? storedValue = null;
        cache
            .Setup(c => c.SetStringAsync(
                It.IsAny<string>(),
                It.IsAny<string>(),
                It.IsAny<TimeSpan>(),
                It.IsAny<CancellationToken>()))
            .Callback<string, string, TimeSpan, CancellationToken>((key, value, _, _) =>
            {
                storedKey = key;
                storedValue = value;
            })
            .Returns(Task.CompletedTask);
        var repository = CreateRepository(
            cache.Object,
            retryWrapperService: CreateRetryReturning(records).Object);

        var result = await repository.SearchAsync(
            CreateSearchRequest(status: "Pending"),
            null,
            TestContext.Current.CancellationToken);

        Assert.Equal(10, result.Records.Count);
        Assert.NotNull(result.ContinuationToken);
        Assert.Equal($"continuation:{result.ContinuationToken}", storedKey);
        Assert.False(string.IsNullOrWhiteSpace(storedValue));
        using var document = JsonDocument.Parse(storedValue!);
        Assert.Equal("Pending", document.RootElement.GetProperty("SearchParameters").GetProperty("Status").GetString());
        Assert.Equal(records[^1].Id, document.RootElement.GetProperty("LastId").GetGuid());
    }

    [Fact]
    public async Task SearchAsync_UsesCachedParameters_WhenContinuationTokenProvided()
    {
        var continuationToken = Guid.NewGuid();
        var lastId = Guid.NewGuid();
        var lastUpdatedAtUtc = DateTime.UtcNow.AddMinutes(-5);
        var cachedJson = JsonSerializer.Serialize(new
        {
            OrderBys = new List<string> {"`UpdatedAtUtc` DESC"},
            SearchParameters = CreateSearchRequest(5, status: "Shipped"),
            LastId = lastId,
            LastUpdatedAtUtc = lastUpdatedAtUtc
        });
        var cache = new Mock<IRemoteCacheService>();
        cache
            .Setup(c => c.GetStringAsync($"continuation:{continuationToken}", It.IsAny<CancellationToken>()))
            .ReturnsAsync(cachedJson);
        var repository = CreateRepository(
            cache.Object,
            retryWrapperService: CreateRetryReturning([CreateEntity()]).Object);

        var result = await repository.SearchAsync(
            CreateSearchRequest(99, status: "Ignored"),
            continuationToken,
            TestContext.Current.CancellationToken);

        Assert.Single(result.Records);
        Assert.Null(result.ContinuationToken);
        cache.Verify(c => c.GetStringAsync(
            $"continuation:{continuationToken}",
            TestContext.Current.CancellationToken), Times.Once);
    }

    [Fact]
    public async Task UpsertAsync_DelegatesToStorage_AndReturnsDto()
    {
        var dto = CreateDto();
        var entity = CreateEntity(dto.Id, dto.UpdatedAtUtc);
        var storage = new Mock<IGenericMySqlDtoStorage<OrderEntity, Guid>>();
        storage
            .Setup(s => s.UpsertAsync(
                DatabaseConstants.PrimaryDatabaseConnectionStringName,
                It.IsAny<OrderEntity>(),
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(entity);
        var repository = CreateRepository(storage: storage.Object);

        var result = await repository.UpsertAsync(dto, TestContext.Current.CancellationToken);

        Assert.Equal(dto.Id, result.Id);
        Assert.Equal(dto.Status, result.Status);
        Assert.Equal(dto.TotalAmount, result.TotalAmount);
        storage.Verify(s => s.UpsertAsync(
            DatabaseConstants.PrimaryDatabaseConnectionStringName,
            It.Is<OrderEntity>(e =>
                e.Id == dto.Id
                && e.Status == dto.Status
                && e.TotalAmount == dto.TotalAmount),
            TestContext.Current.CancellationToken), Times.Once);
    }
}