using RedShirt.Example.Api.DataStores.Product.Core.Models;
using RedShirt.Example.Api.DataStores.Product.Core.Services;

namespace RedShirt.Example.Api.DataStores.Product.Core.UnitTests.Tests.Services;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class IProductServiceContractTests
{
    [Fact]
    public void IProductService_ExposesExpectedOperations()
    {
        var methods = typeof(IProductService)
            .GetMethods()
            .Select(m => m.Name)
            .OrderBy(n => n)
            .ToArray();

        Assert.Equal(
            ["DeleteAsync", "GetByIdAsync", "PatchAsync", "PostAsync", "PutAsync", "SearchAsync"],
            methods);
    }

    [Fact]
    public void RequestModels_CanBeConstructed()
    {
        var id = Guid.NewGuid();

        var post = new ProductServicePostRequest
        {
            Sku = "SKU-1",
            Name = "Widget",
            Price = "1.00"
        };
        var put = new ProductServicePutRequest
        {
            Id = id,
            Sku = "SKU-1",
            Name = "Widget",
            Price = "1.00"
        };
        var patch = new ProductServicePatchRequest
        {
            Id = id,
            Sku = null,
            Name = "Renamed",
            Price = null
        };
        var search = new ProductServiceSearchRequest
        {
            PageSize = 25,
            CreatedBeforeUtc = null,
            CreatedAfterUtc = null,
            UpdatedBeforeUtc = null,
            UpdatedAfterUtc = null,
            Sku = "SKU-1",
            SkuContains = null,
            Name = null,
            NameContains = null,
            Price = null,
            PriceGreaterThan = null,
            PriceLessThan = null
        };
        var response = new ProductSearchResponse
        {
            ContinuationToken = id,
            Records = []
        };

        Assert.Equal("SKU-1", post.Sku);
        Assert.Equal(id, put.Id);
        Assert.Equal("Renamed", patch.Name);
        Assert.Equal(25, search.PageSize);
        Assert.Equal(id, response.ContinuationToken);
        Assert.Empty(response.Records);
    }
}