using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.DataModel;
using Amazon.DynamoDBv2.DocumentModel;
using Amazon.DynamoDBv2.Model;
using Microsoft.Extensions.Options;
using Moq;
using RedShirt.Example.Api.Core.UseCases.ExampleItem.Models;
using RedShirt.Example.Api.DataStores.ExampleItem.Domain;
using RedShirt.Example.Api.DataStores.ExampleItem.Repositories;
using System.Text.Json;
using BadRequestException = RedShirt.Example.Api.Common.Exceptions.Responses.BadRequestException;
using ResourceNotFoundException = RedShirt.Example.Api.Common.Exceptions.Responses.ResourceNotFoundException;

namespace RedShirt.Example.Api.Implementations.ExampleItem.UnitTests.Tests.Repositories;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class DynamoExampleItemRepositoryTests
{
    private const string TableName = "example-items";

    private static DynamoExampleItemRepository CreateRepository(
        IAmazonDynamoDB? client = null,
        IDynamoDBContext? context = null)
    {
        return new DynamoExampleItemRepository(
            client ?? new Mock<IAmazonDynamoDB>().Object,
            context ?? new Mock<IDynamoDBContext>().Object,
            Options.Create(new DynamoExampleItemRepository.ConfigurationModel
            {
                TableName = TableName
            }));
    }

    [Fact]
    public async Task DeleteByName_DoesNotDelete_WhenItemIsMissing()
    {
        var context = new Mock<IDynamoDBContext>();
        context
            .Setup(c => c.LoadAsync<ExampleItemMapping>(
                It.IsAny<object>(),
                It.IsAny<LoadConfig>(),
                It.IsAny<CancellationToken>()))
            .Returns(Task.FromResult<ExampleItemMapping?>(null)!);
        var repository = CreateRepository(context: context.Object);

        await Assert.ThrowsAsync<ResourceNotFoundException>(() =>
            repository.DeleteByName("missing", TestContext.Current.CancellationToken));

        context.Verify(c => c.DeleteAsync(
            It.IsAny<ExampleItemModel>(),
            It.IsAny<DeleteConfig>(),
            It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task DeleteByName_LoadsThenDeletes_WhenItemExists()
    {
        var context = new Mock<IDynamoDBContext>();
        context
            .Setup(c => c.LoadAsync<ExampleItemMapping>(
                "widget",
                It.Is<LoadConfig>(cfg => cfg.OverrideTableName == TableName),
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(new ExampleItemMapping {Name = "widget"});
        context
            .Setup(c => c.DeleteAsync(
                It.IsAny<ExampleItemModel>(),
                It.IsAny<DeleteConfig>(),
                It.IsAny<CancellationToken>()))
            .Returns(Task.CompletedTask);
        var repository = CreateRepository(context: context.Object);

        await repository.DeleteByName("widget", TestContext.Current.CancellationToken);

        context.Verify(c => c.LoadAsync<ExampleItemMapping>(
            "widget",
            It.Is<LoadConfig>(cfg => cfg.OverrideTableName == TableName),
            TestContext.Current.CancellationToken), Times.Once);
        context.Verify(c => c.DeleteAsync(
            It.Is<ExampleItemModel>(m => m.Name == "widget"),
            It.Is<DeleteConfig>(cfg => cfg.OverrideTableName == TableName),
            TestContext.Current.CancellationToken), Times.Once);
    }

    [Fact]
    public async Task GetByName_ReturnsMappedModel_WhenItemExists()
    {
        var context = new Mock<IDynamoDBContext>();
        context
            .Setup(c => c.LoadAsync<ExampleItemMapping>(
                "widget",
                It.Is<LoadConfig>(cfg => cfg.OverrideTableName == TableName),
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(new ExampleItemMapping {Name = "widget"});
        var repository = CreateRepository(context: context.Object);

        var result = await repository.GetByName("widget", TestContext.Current.CancellationToken);

        Assert.Equal("widget", result.Name);
        context.Verify(c => c.LoadAsync<ExampleItemMapping>(
            "widget",
            It.Is<LoadConfig>(cfg => cfg.OverrideTableName == TableName),
            TestContext.Current.CancellationToken), Times.Once);
    }

    [Fact]
    public async Task GetByName_ThrowsResourceNotFound_WhenItemIsMissing()
    {
        var context = new Mock<IDynamoDBContext>();
        context
            .Setup(c => c.LoadAsync<ExampleItemMapping>(
                It.IsAny<object>(),
                It.IsAny<LoadConfig>(),
                It.IsAny<CancellationToken>()))
            .Returns(Task.FromResult<ExampleItemMapping?>(null)!);
        var repository = CreateRepository(context: context.Object);

        await Assert.ThrowsAsync<ResourceNotFoundException>(() =>
            repository.GetByName("missing", TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task GetListAsync_MapsItemsAndEncodesContinuationToken()
    {
        var client = new Mock<IAmazonDynamoDB>();
        var context = new Mock<IDynamoDBContext>();
        var lastKey = new Dictionary<string, AttributeValue>
        {
            ["Name"] = new() {S = "next"}
        };
        client
            .Setup(c => c.ScanAsync(It.IsAny<ScanRequest>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(new ScanResponse
            {
                Items =
                [
                    new Dictionary<string, AttributeValue>
                    {
                        ["Name"] = new() {S = "widget"}
                    }
                ],
                LastEvaluatedKey = lastKey
            });
        context
            .Setup(c => c.FromDocument<ExampleItemModel>(It.IsAny<Document>()))
            .Returns(new ExampleItemModel {Name = "widget"});
        var repository = CreateRepository(client.Object, context.Object);

        var result = await repository.GetListAsync(null, TestContext.Current.CancellationToken);

        Assert.Single(result.Items);
        Assert.Equal("widget", result.Items[0].Name);
        Assert.Equal(
            Convert.ToBase64String(JsonSerializer.SerializeToUtf8Bytes(lastKey)),
            result.ContinuationToken);
        context.Verify(c => c.FromDocument<ExampleItemModel>(It.IsAny<Document>()), Times.Once);
    }

    [Fact]
    public async Task GetListAsync_PassesDecodedExclusiveStartKey_WhenContinuationTokenIsProvided()
    {
        var startKey = new Dictionary<string, AttributeValue>
        {
            ["Name"] = new() {S = "cursor"}
        };
        var continuationToken = Convert.ToBase64String(JsonSerializer.SerializeToUtf8Bytes(startKey));
        var client = new Mock<IAmazonDynamoDB>();
        var context = new Mock<IDynamoDBContext>();
        ScanRequest? capturedRequest = null;
        client
            .Setup(c => c.ScanAsync(It.IsAny<ScanRequest>(), It.IsAny<CancellationToken>()))
            .Callback<ScanRequest, CancellationToken>((request, _) => capturedRequest = request)
            .ReturnsAsync(new ScanResponse
            {
                Items = [],
                LastEvaluatedKey = new Dictionary<string, AttributeValue>()
            });
        var repository = CreateRepository(client.Object, context.Object);

        var result = await repository.GetListAsync(continuationToken, TestContext.Current.CancellationToken);

        Assert.Null(result.ContinuationToken);
        Assert.NotNull(capturedRequest);
        Assert.NotNull(capturedRequest.ExclusiveStartKey);
        Assert.Equal("cursor", capturedRequest.ExclusiveStartKey["Name"].S);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    public async Task GetListAsync_ScansWithoutExclusiveStartKey_WhenContinuationTokenIsMissing(
        string? continuationToken)
    {
        var client = new Mock<IAmazonDynamoDB>();
        var context = new Mock<IDynamoDBContext>();
        ScanRequest? capturedRequest = null;
        client
            .Setup(c => c.ScanAsync(It.IsAny<ScanRequest>(), It.IsAny<CancellationToken>()))
            .Callback<ScanRequest, CancellationToken>((request, _) => capturedRequest = request)
            .ReturnsAsync(new ScanResponse
            {
                Items = [],
                LastEvaluatedKey = null
            });
        var repository = CreateRepository(client.Object, context.Object);

        var result = await repository.GetListAsync(continuationToken, TestContext.Current.CancellationToken);

        Assert.Null(result.ContinuationToken);
        Assert.Empty(result.Items);
        Assert.NotNull(capturedRequest);
        Assert.Equal(TableName, capturedRequest.TableName);
        Assert.Null(capturedRequest.ExclusiveStartKey);
    }

    [Theory]
    [InlineData("not-base64!")]
    [InlineData("abc")]
    public async Task GetListAsync_ThrowsBadRequest_WhenContinuationTokenIsNotValidBase64(
        string continuationToken)
    {
        var client = new Mock<IAmazonDynamoDB>();
        var repository = CreateRepository(client.Object);

        var exception = await Assert.ThrowsAsync<BadRequestException>(() =>
            repository.GetListAsync(continuationToken, TestContext.Current.CancellationToken));

        Assert.Equal("Continuation token must be a valid base64-encoded string", exception.Message);
        client.Verify(c => c.ScanAsync(It.IsAny<ScanRequest>(), It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task GetListAsync_ThrowsBadRequest_WhenContinuationTokenIsValidBase64ButNotValidJson()
    {
        var continuationToken = Convert.ToBase64String("{not-valid-json"u8.ToArray());
        var client = new Mock<IAmazonDynamoDB>();
        var repository = CreateRepository(client.Object);

        var exception = await Assert.ThrowsAsync<BadRequestException>(() =>
            repository.GetListAsync(continuationToken, TestContext.Current.CancellationToken));

        Assert.Equal("Continuation token is not valid", exception.Message);
        client.Verify(c => c.ScanAsync(It.IsAny<ScanRequest>(), It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task Put_SavesMappedItem_WithConfiguredTableName()
    {
        var context = new Mock<IDynamoDBContext>();
        context
            .Setup(c => c.SaveAsync(
                It.IsAny<ExampleItemMapping>(),
                It.IsAny<SaveConfig>(),
                It.IsAny<CancellationToken>()))
            .Returns(Task.CompletedTask);
        var repository = CreateRepository(context: context.Object);

        await repository.Put(new ExampleItemModel {Name = "widget"}, TestContext.Current.CancellationToken);

        context.Verify(c => c.SaveAsync(
            It.Is<ExampleItemMapping>(m => m.Name == "widget"),
            It.Is<SaveConfig>(cfg => cfg.OverrideTableName == TableName),
            TestContext.Current.CancellationToken), Times.Once);
    }
}