using RedShirt.Example.Api.Connectors.Foo.Implementation.Exceptions;

namespace RedShirt.Example.Api.Connectors.Foo.Implementation.UnitTests.Tests.Exceptions;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class FooImplementationExceptionTests
{
    [Fact]
    public void FooUnauthorizedException_UsesStableMessage()
    {
        var exception = new FooUnauthorizedException();

        Assert.Equal("Foo API rejected the API key.", exception.Message);
        Assert.Null(exception.InnerException);
    }

    [Fact]
    public void FooUnavailableException_UsesStableMessage()
    {
        var exception = new FooUnavailableException();

        Assert.Equal("Foo is assumed to be unavailable for the time being.", exception.Message);
        Assert.Null(exception.InnerException);
    }
}