using RedShirt.Example.Api.Common.Analyzers.Database.Abstractions.Attributes;
using RedShirt.Example.Api.DataStores.Constants;
using RedShirt.Example.Api.DataStores.Product.Implementation.Entities;
using System.Reflection;

namespace RedShirt.Example.Api.DataStores.Product.Implementation.UnitTests.Tests.Entities;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class ProductEntityTests
{
    [Fact]
    public void ProductEntity_HasExpectedTableMetadata()
    {
        var attribute = typeof(ProductEntity).GetCustomAttribute<DbTableAttribute>();

        Assert.NotNull(attribute);
        Assert.Equal("Product", attribute!.TableName);
        Assert.Equal(DatabaseConstants.PrimaryDatabaseConnectionStringName, attribute.ConnectionStringName);
    }

    [Fact]
    public void ProductEntity_MarksKeyAndTimestamps()
    {
        Assert.NotNull(typeof(ProductEntity).GetProperty(nameof(ProductEntity.Id))!
            .GetCustomAttribute<DbKeyAttribute>());
        Assert.NotNull(typeof(ProductEntity).GetProperty(nameof(ProductEntity.CreatedAtUtc))!
            .GetCustomAttribute<CreatedAtPropertyAttribute>());
        Assert.NotNull(typeof(ProductEntity).GetProperty(nameof(ProductEntity.UpdatedAtUtc))!
            .GetCustomAttribute<UpdatedAtPropertyAttribute>());
    }

    [Fact]
    public void ProductEntity_StoresPriceAsDecimal()
    {
        var property = typeof(ProductEntity).GetProperty(nameof(ProductEntity.Price));

        Assert.NotNull(property);
        Assert.Equal(typeof(decimal), property!.PropertyType);
    }
}
