using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Moq;
using RedShirt.Example.Api.Core.Exceptions;
using RedShirt.Example.Api.Core.Exceptions.Responses;
using RedShirt.Example.Api.ExceptionHandlers;

namespace RedShirt.Example.Api.UnitTests.Tests.ExceptionHandlers;

/// <summary>
/// Code generated by Cursor (Composer).
/// </summary>
public class ApiExceptionHandlerTests
{
    [Fact]
    public async Task TryHandleAsync_MapsBadRequestException_To400ProblemDetails()
    {
        var written = await HandleAsync(new BadRequestException("Name is required"));

        Assert.True(written.Handled);
        Assert.Equal(StatusCodes.Status400BadRequest, written.StatusCode);
        Assert.Equal("Bad Request", written.ProblemDetails?.Title);
        Assert.Equal("Name is required", written.ProblemDetails?.Detail);
        Assert.Equal(StatusCodes.Status400BadRequest, written.ProblemDetails?.Status);
    }

    [Fact]
    public async Task TryHandleAsync_MapsResourceNotFoundException_To404ProblemDetails()
    {
        var written = await HandleAsync(new ResourceNotFoundException());

        Assert.True(written.Handled);
        Assert.Equal(StatusCodes.Status404NotFound, written.StatusCode);
        Assert.Equal("Not Found", written.ProblemDetails?.Title);
        Assert.Null(written.ProblemDetails?.Detail);
        Assert.Equal(StatusCodes.Status404NotFound, written.ProblemDetails?.Status);
    }

    [Fact]
    public async Task TryHandleAsync_MapsIdempotentConcurrencyException_To409ProblemDetails()
    {
        var written = await HandleAsync(new IdempotentConcurrencyException());

        Assert.True(written.Handled);
        Assert.Equal(StatusCodes.Status409Conflict, written.StatusCode);
        Assert.Equal("Conflict", written.ProblemDetails?.Title);
        Assert.Null(written.ProblemDetails?.Detail);
        Assert.Equal(StatusCodes.Status409Conflict, written.ProblemDetails?.Status);
    }

    [Fact]
    public async Task TryHandleAsync_DoesNotHandleUnknownExceptions()
    {
        ProblemDetails? captured = null;
        var problemDetailsService = new Mock<IProblemDetailsService>();
        problemDetailsService
            .Setup(s => s.TryWriteAsync(It.IsAny<ProblemDetailsContext>()))
            .Callback<ProblemDetailsContext>(context => captured = context.ProblemDetails)
            .ReturnsAsync(true);

        var handler = new ApiExceptionHandler(problemDetailsService.Object);
        var httpContext = new DefaultHttpContext();

        var handled = await handler.TryHandleAsync(httpContext, new InvalidOperationException("boom"),
            TestContext.Current.CancellationToken);

        Assert.False(handled);
        Assert.Null(captured);
        problemDetailsService.Verify(s => s.TryWriteAsync(It.IsAny<ProblemDetailsContext>()), Times.Never);
    }

    private static async Task<(bool Handled, int StatusCode, ProblemDetails? ProblemDetails)> HandleAsync(
        Exception exception)
    {
        ProblemDetails? captured = null;
        var problemDetailsService = new Mock<IProblemDetailsService>();
        problemDetailsService
            .Setup(s => s.TryWriteAsync(It.IsAny<ProblemDetailsContext>()))
            .Callback<ProblemDetailsContext>(context => captured = context.ProblemDetails)
            .ReturnsAsync(true);

        var handler = new ApiExceptionHandler(problemDetailsService.Object);
        var httpContext = new DefaultHttpContext();

        var handled = await handler.TryHandleAsync(httpContext, exception, TestContext.Current.CancellationToken);

        return (handled, httpContext.Response.StatusCode, captured);
    }
}
