using Microsoft.Extensions.Options;
using RedShirt.Example.Api.Common.Shared.Core.Abstractions;
using RedShirt.Example.Api.Common.Shared.Core.Services;
using RedShirt.Example.Api.Core.Services;
using System.Text.Json;

namespace RedShirt.Example.Api.Core.UnitTests.Tests.Services;

/// <summary>
///     Generated by Cursor (Auto / Composer).
/// </summary>
public class CacheBasedIdempotencyServiceTests
{
    private static CacheBasedIdempotencyService CreateService(
        IDataCacheService? dataCacheService = null,
        IAbstractedLockService? lockService = null,
        int idempotencyTimeMinutes = 10)
    {
        return new CacheBasedIdempotencyService(
            dataCacheService ?? new FakeDataCacheService(),
            lockService ?? new FakeLockService(),
            Options.Create(new CacheBasedIdempotencyService.ConfigurationModel
            {
                IdempotencyTrackingTimeMinutes = idempotencyTimeMinutes
            }));
    }

    [Theory]
    [InlineData(0, 1)]
    [InlineData(-10, 1)]
    [InlineData(1, 1)]
    [InlineData(30, 30)]
    public void ConfigurationModel_EffectiveIdempotencyTimeMinutes_EnforcesMinimumOfOne(
        int configuredMinutes,
        int expectedEffectiveMinutes)
    {
        var config = new CacheBasedIdempotencyService.ConfigurationModel
        {
            IdempotencyTrackingTimeMinutes = configuredMinutes
        };

        Assert.Equal(expectedEffectiveMinutes, config.EffectiveIdempotencyTimeMinutes);
    }

    [Fact]
    public async Task GetLockAsync_PrefixesKey_AndReturnsLockFromLockService()
    {
        var expectedLock = new FakeLock(true);
        var lockService = new FakeLockService {LockToReturn = expectedLock};
        var service = CreateService(lockService: lockService);

        var result = await service.GetLockAsync("submission-1", TestContext.Current.CancellationToken);

        Assert.Same(expectedLock, result);
        Assert.Equal("idempotent-concurrency:submission-1", lockService.LastKey);
    }

    [Fact]
    public async Task GetRecordAsync_DeserializesStoredJson()
    {
        var payload = new SampleRecord("alpha", 3);
        var cache = new FakeDataCacheService
        {
            GetResult = JsonSerializer.Serialize(payload)
        };
        var service = CreateService(cache);

        var result = await service.GetRecordAsync<SampleRecord>("key", TestContext.Current.CancellationToken);

        Assert.Equal(payload, result);
    }

    [Fact]
    public async Task GetRecordAsync_ReturnsDefault_WhenCacheMisses()
    {
        var cache = new FakeDataCacheService {GetResult = null};
        var service = CreateService(cache);

        var result = await service.GetRecordAsync<SampleRecord>("missing", TestContext.Current.CancellationToken);

        Assert.Null(result);
        Assert.Equal("missing", cache.LastGetKey);
    }

    [Fact]
    public async Task GetRecordAsync_ReturnsDefault_WhenStoredJsonIsInvalid()
    {
        var cache = new FakeDataCacheService {GetResult = "{not-json"};
        var service = CreateService(cache);

        var result = await service.GetRecordAsync<SampleRecord>("key", TestContext.Current.CancellationToken);

        Assert.Null(result);
    }

    [Fact]
    public async Task SetRecordAsync_SerializesValue_AndUsesConfiguredExpiration()
    {
        var cache = new FakeDataCacheService();
        var service = CreateService(cache, idempotencyTimeMinutes: 15);
        var payload = new SampleRecord("beta", 9);

        await service.SetRecordAsync("key", payload, TestContext.Current.CancellationToken);

        Assert.Equal("key", cache.LastSetKey);
        Assert.Equal(JsonSerializer.Serialize(payload), cache.LastSetValue);
        Assert.Equal(TimeSpan.FromMinutes(15), cache.LastSetExpiration);
    }

    [Theory]
    [InlineData(0)]
    [InlineData(-5)]
    public async Task SetRecordAsync_UsesMinimumOneMinuteExpiration_WhenConfiguredBelowOne(
        int idempotencyTimeMinutes)
    {
        var cache = new FakeDataCacheService();
        var service = CreateService(cache, idempotencyTimeMinutes: idempotencyTimeMinutes);

        await service.SetRecordAsync("key", new SampleRecord("gamma", 1), TestContext.Current.CancellationToken);

        Assert.Equal(TimeSpan.FromMinutes(1), cache.LastSetExpiration);
    }

    private sealed record SampleRecord(string Name, int Count);

    private sealed class FakeDataCacheService : IDataCacheService
    {
        public string? GetResult { get; init; }
        public string? LastGetKey { get; private set; }
        public string? LastSetKey { get; private set; }
        public string? LastSetValue { get; private set; }
        public TimeSpan? LastSetExpiration { get; private set; }

        public Task<string?> GetStringAsync(string key)
        {
            LastGetKey = key;
            return Task.FromResult(GetResult);
        }

        public Task SetStringAsync(string key, string value, TimeSpan expiration)
        {
            LastSetKey = key;
            LastSetValue = value;
            LastSetExpiration = expiration;
            return Task.CompletedTask;
        }
    }

    private sealed class FakeLockService : IAbstractedLockService
    {
        public string? LastKey { get; private set; }
        public IAbstractedLock LockToReturn { get; init; } = new FakeLock(true);

        public Task<IAbstractedLock> GetLockAsync(string key)
        {
            LastKey = key;
            return Task.FromResult(LockToReturn);
        }
    }

    private sealed class FakeLock(bool isAcquired) : IAbstractedLock
    {
        public bool IsAcquired { get; } = isAcquired;

        public void Unlock()
        {
        }
    }
}