using Moq;
using RedShirt.Example.Api.Common.Abstractions;
using RedShirt.Example.Api.Core.Exceptions;
using RedShirt.Example.Api.Core.Services;

namespace RedShirt.Example.Api.Core.UnitTests.Tests.Services;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class CacheBasedIdempotencyWrapperServiceTests
{
    private static Mock<IAbstractedLock> CreateLock(bool isAcquired)
    {
        var lockHandle = new Mock<IAbstractedLock>();
        lockHandle.SetupGet(l => l.IsAcquired).Returns(isAcquired);
        return lockHandle;
    }

    [Fact]
    public async Task RunIdempotentlyAsync_DoesNotCache_WhenCallbackThrows()
    {
        var lockHandle = CreateLock(true);
        var idempotency = new Mock<ICacheBasedIdempotencyService>();
        idempotency
            .Setup(s => s.GetRecordAsync<SampleResult>("idem-1", TestContext.Current.CancellationToken))
            .ReturnsAsync((SampleResult?) null);
        idempotency
            .Setup(s => s.GetLockAsync("idem-1", TestContext.Current.CancellationToken))
            .ReturnsAsync(lockHandle.Object);
        var service = new CacheBasedIdempotencyWrapperService(idempotency.Object);

        await Assert.ThrowsAsync<InvalidOperationException>(() =>
            service.RunIdempotentlyAsync<SampleResult>("idem-1", () =>
                    throw new InvalidOperationException("callback failed"),
                TestContext.Current.CancellationToken));

        idempotency.Verify(
            s => s.SetRecordAsync(It.IsAny<string>(), It.IsAny<SampleResult>(), It.IsAny<CancellationToken>()),
            Times.Never);
        lockHandle.Verify(l => l.Unlock(), Times.Once);
    }

    [Fact]
    public async Task RunIdempotentlyAsync_InvokesCallbackCachesAndUnlocks_OnSuccess()
    {
        var produced = new SampleResult("fresh");
        var lockHandle = CreateLock(true);
        var idempotency = new Mock<ICacheBasedIdempotencyService>();
        idempotency
            .Setup(s => s.GetRecordAsync<SampleResult>("idem-1", TestContext.Current.CancellationToken))
            .ReturnsAsync((SampleResult?) null);
        idempotency
            .Setup(s => s.GetLockAsync("idem-1", TestContext.Current.CancellationToken))
            .ReturnsAsync(lockHandle.Object);
        idempotency
            .Setup(s => s.SetRecordAsync("idem-1", produced, TestContext.Current.CancellationToken))
            .Returns(Task.CompletedTask);
        var callbackInvoked = false;
        var service = new CacheBasedIdempotencyWrapperService(idempotency.Object);

        var result = await service.RunIdempotentlyAsync("idem-1", () =>
        {
            callbackInvoked = true;
            return Task.FromResult(produced);
        }, TestContext.Current.CancellationToken);

        Assert.True(callbackInvoked);
        Assert.Same(produced, result);
        idempotency.Verify(
            s => s.SetRecordAsync("idem-1", produced, TestContext.Current.CancellationToken),
            Times.Once);
        lockHandle.Verify(l => l.Unlock(), Times.Once);
    }

    [Fact]
    public async Task RunIdempotentlyAsync_ReturnsCachedResponse_AndUnlocks()
    {
        var lockHandle = CreateLock(true);
        var cached = new SampleResult("cached");
        var idempotency = new Mock<ICacheBasedIdempotencyService>();
        idempotency
            .Setup(s => s.GetRecordAsync<SampleResult>("idem-1", TestContext.Current.CancellationToken))
            .ReturnsAsync(cached);
        idempotency
            .Setup(s => s.GetLockAsync("idem-1", TestContext.Current.CancellationToken))
            .ReturnsAsync(lockHandle.Object);
        var callbackInvoked = false;
        var service = new CacheBasedIdempotencyWrapperService(idempotency.Object);

        var result = await service.RunIdempotentlyAsync("idem-1", () =>
        {
            callbackInvoked = true;
            return Task.FromResult(new SampleResult("fresh"));
        }, TestContext.Current.CancellationToken);

        Assert.Same(cached, result);
        Assert.False(callbackInvoked);
        idempotency.Verify(s => s.GetLockAsync("idem-1", TestContext.Current.CancellationToken), Times.Once);
        idempotency.Verify(
            s => s.SetRecordAsync(It.IsAny<string>(), It.IsAny<SampleResult>(), It.IsAny<CancellationToken>()),
            Times.Never);
        lockHandle.Verify(l => l.Unlock(), Times.Once);
    }

    [Fact]
    public async Task RunIdempotentlyAsync_ThrowsIdempotentConcurrency_WhenLockIsNotAcquired()
    {
        var lockHandle = CreateLock(false);
        var idempotency = new Mock<ICacheBasedIdempotencyService>();
        idempotency
            .Setup(s => s.GetRecordAsync<SampleResult>("idem-1", TestContext.Current.CancellationToken))
            .ReturnsAsync((SampleResult?) null);
        idempotency
            .Setup(s => s.GetLockAsync("idem-1", TestContext.Current.CancellationToken))
            .ReturnsAsync(lockHandle.Object);
        var callbackInvoked = false;
        var service = new CacheBasedIdempotencyWrapperService(idempotency.Object);

        await Assert.ThrowsAsync<IdempotentConcurrencyException>(() =>
            service.RunIdempotentlyAsync("idem-1", () =>
            {
                callbackInvoked = true;
                return Task.FromResult(new SampleResult("fresh"));
            }, TestContext.Current.CancellationToken));

        Assert.False(callbackInvoked);
        idempotency.Verify(s => s.GetLockAsync("idem-1", TestContext.Current.CancellationToken), Times.Once);
        idempotency.Verify(
            s => s.SetRecordAsync(It.IsAny<string>(), It.IsAny<SampleResult>(), It.IsAny<CancellationToken>()),
            Times.Never);
        lockHandle.Verify(l => l.Unlock(), Times.Never);
    }

    private sealed class SampleResult(string value)
    {
        public string Value { get; } = value;
    }
}