using Moq;
using RedShirt.Example.Api.Core.Cqrs;
using RedShirt.Example.Api.Core.UseCases.Product.Commands.Update;
using RedShirt.Example.Api.DataStores.Product.Core.Models;
using RedShirt.Example.Api.DataStores.Product.Core.Services;

namespace RedShirt.Example.Api.Core.UnitTests.Tests.UseCases.Product.Commands.Update;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class UpdateProductCommandHandlerTests
{
    [Fact]
    public async Task Handle_ValidatesAndMapsCommandToPutRequest()
    {
        var id = Guid.NewGuid();
        var internalDto = new ProductInternalDto
        {
            Id = id,
            CreatedAtUtc = DateTime.UtcNow.AddDays(-1),
            UpdatedAtUtc = DateTime.UtcNow,
            Sku = "SKU-2",
            Name = "Gadget",
            Price = 29.95m
        };
        ProductServicePutRequest? capturedRequest = null;
        var productService = new Mock<IProductService>();
        productService
            .Setup(s => s.PutAsync(It.IsAny<ProductServicePutRequest>(), TestContext.Current.CancellationToken))
            .Callback<ProductServicePutRequest, CancellationToken>((request, _) => capturedRequest = request)
            .ReturnsAsync(internalDto);
        var validator = new Mock<ICoreRequestValidator>();
        var handler = new UpdateProductCommandHandler(productService.Object, validator.Object);
        var command = new UpdateProductCommand(id, "SKU-2", "Gadget", "29.95");

        var result = await handler.Handle(command, TestContext.Current.CancellationToken);

        Assert.NotNull(capturedRequest);
        Assert.Equal(id, capturedRequest!.Id);
        Assert.Equal("SKU-2", capturedRequest.Sku);
        Assert.Equal("Gadget", capturedRequest.Name);
        Assert.Equal(29.95m, capturedRequest.Price);
        Assert.Equal("29.95", result.Price);
        validator.Verify(v => v.ValidateAsync(command, TestContext.Current.CancellationToken), Times.Once);
        productService.Verify(
            s => s.PutAsync(It.IsAny<ProductServicePutRequest>(), TestContext.Current.CancellationToken),
            Times.Once);
    }
}