using RedShirt.Example.Api.Core.UseCases.ExampleItem.Commands.Create;
using RedShirt.Example.Api.Core.UseCases.ExampleItem.Models;

namespace RedShirt.Example.Api.Core.UnitTests.Tests.UseCases.ExampleItem.Commands.Create;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class CreateExampleItemCommandValidatorTests
{
    private readonly CreateExampleItemCommandValidator _validator = new();

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    public async Task Validate_Fails_WhenNameIsMissing(string? name)
    {
        var result = await _validator.ValidateAsync(
            new CreateExampleItemCommand(new ExampleItemModel {Name = name!}, "idem-1"),
            TestContext.Current.CancellationToken);

        Assert.False(result.IsValid);
        Assert.Contains(result.Errors, error => error.ErrorMessage == "Name is required");
    }

    [Fact]
    public async Task Validate_Succeeds_WhenNameIsPresent()
    {
        var result = await _validator.ValidateAsync(
            new CreateExampleItemCommand(new ExampleItemModel {Name = "widget"}, "idem-1"),
            TestContext.Current.CancellationToken);

        Assert.True(result.IsValid);
    }
}