using Moq;
using RedShirt.Example.Api.Core.Cqrs;
using RedShirt.Example.Api.Core.Services;
using RedShirt.Example.Api.Core.UseCases.ExampleItem.Commands.Create;
using RedShirt.Example.Api.Core.UseCases.ExampleItem.Models;
using RedShirt.Example.Api.Core.UseCases.ExampleItem.Services;

namespace RedShirt.Example.Api.Core.UnitTests.Tests.UseCases.ExampleItem.Commands.Create;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class CreateExampleItemCommandHandlerTests
{
    private static CreateExampleItemCommandHandler CreateHandler(
        IExampleItemRepository? repository = null,
        ICacheBasedIdempotencyWrapperService? idempotencyWrapperService = null,
        ICoreRequestValidator? requestValidator = null)
    {
        return new CreateExampleItemCommandHandler(
            repository ?? new Mock<IExampleItemRepository>().Object,
            idempotencyWrapperService ?? CreateInvokingWrapper().Object,
            requestValidator ?? new Mock<ICoreRequestValidator>().Object);
    }

    private static Mock<ICacheBasedIdempotencyWrapperService> CreateInvokingWrapper()
    {
        var wrapper = new Mock<ICacheBasedIdempotencyWrapperService>();
        wrapper
            .Setup(w => w.RunIdempotentlyAsync(
                It.IsAny<string>(),
                It.IsAny<Func<Task<ExampleItemModel>>>(),
                It.IsAny<CancellationToken>()))
            .Returns((string _, Func<Task<ExampleItemModel>> callback, CancellationToken _) => callback());
        return wrapper;
    }

    [Fact]
    public async Task Handle_ReturnsWrapperResult_WithoutCallingRepository_WhenCallbackIsSkipped()
    {
        var cached = new ExampleItemModel {Name = "cached"};
        var repository = new Mock<IExampleItemRepository>();
        var wrapper = new Mock<ICacheBasedIdempotencyWrapperService>();
        wrapper
            .Setup(w => w.RunIdempotentlyAsync(
                "idem-1",
                It.IsAny<Func<Task<ExampleItemModel>>>(),
                TestContext.Current.CancellationToken))
            .ReturnsAsync(cached);
        var handler = CreateHandler(repository.Object, wrapper.Object);

        var result = await handler.Handle(
            new CreateExampleItemCommand(new ExampleItemModel {Name = "fresh"}, "idem-1"),
            TestContext.Current.CancellationToken);

        Assert.Same(cached, result);
        repository.Verify(
            r => r.Put(It.IsAny<ExampleItemModel>(), It.IsAny<CancellationToken>()),
            Times.Never);
    }

    [Fact]
    public async Task Handle_RunsThroughIdempotencyWrapper_AndPersistsOnSuccess()
    {
        var repository = new Mock<IExampleItemRepository>();
        repository
            .Setup(r => r.Put(It.IsAny<ExampleItemModel>(), TestContext.Current.CancellationToken))
            .Returns(Task.CompletedTask);
        var wrapper = CreateInvokingWrapper();
        var handler = CreateHandler(repository.Object, wrapper.Object);
        var model = new ExampleItemModel {Name = "widget"};

        var result = await handler.Handle(
            new CreateExampleItemCommand(model, "idem-1"),
            TestContext.Current.CancellationToken);

        Assert.Same(model, result);
        repository.Verify(r => r.Put(model, TestContext.Current.CancellationToken), Times.Once);
        wrapper.Verify(w => w.RunIdempotentlyAsync(
            "idem-1",
            It.IsAny<Func<Task<ExampleItemModel>>>(),
            TestContext.Current.CancellationToken), Times.Once);
    }
}