using Moq;
using RedShirt.Example.Api.Common.Exceptions.Responses;
using RedShirt.Example.Api.DataStores.Product.Core.Models;
using RedShirt.Example.Api.DataStores.Product.Implementation.Repositories;
using RedShirt.Example.Api.DataStores.Product.Implementation.Services;

namespace RedShirt.Example.Api.DataStores.Product.Implementation.UnitTests.Tests.Services;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class ProductServiceTests
{
    private static ProductDto CreateDto(
        Guid? id = null,
        string sku = "SKU-1",
        string name = "Widget",
        string price = "9.99",
        DateTime? createdAtUtc = null,
        DateTime? updatedAtUtc = null)
    {
        var created = createdAtUtc ?? DateTime.UtcNow.AddDays(-1);
        return new ProductDto
        {
            Id = id ?? Guid.NewGuid(),
            CreatedAtUtc = created,
            UpdatedAtUtc = updatedAtUtc ?? created,
            Sku = sku,
            Name = name,
            Price = price
        };
    }

    private static ProductService CreateService(IProductRepository? repository = null)
    {
        return new ProductService(repository ?? new Mock<IProductRepository>().Object);
    }

    [Fact]
    public async Task DeleteAsync_ThrowsResourceNotFound_WhenRepositoryReturnsFalse()
    {
        var id = Guid.NewGuid();
        var repository = new Mock<IProductRepository>();
        repository
            .Setup(r => r.DeleteAsync(id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(false);
        var service = CreateService(repository.Object);

        await Assert.ThrowsAsync<ResourceNotFoundException>(() =>
            service.DeleteAsync(id, TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task DeleteAsync_Completes_WhenRepositoryReturnsTrue()
    {
        var id = Guid.NewGuid();
        var repository = new Mock<IProductRepository>();
        repository
            .Setup(r => r.DeleteAsync(id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(true);
        var service = CreateService(repository.Object);

        await service.DeleteAsync(id, TestContext.Current.CancellationToken);

        repository.Verify(r => r.DeleteAsync(id, TestContext.Current.CancellationToken), Times.Once);
    }

    [Fact]
    public async Task GetByIdAsync_ThrowsResourceNotFound_WhenMissing()
    {
        var id = Guid.NewGuid();
        var repository = new Mock<IProductRepository>();
        repository
            .Setup(r => r.GetByIdAsync(id, It.IsAny<CancellationToken>()))
            .ReturnsAsync((ProductDto?) null);
        var service = CreateService(repository.Object);

        await Assert.ThrowsAsync<ResourceNotFoundException>(() =>
            service.GetByIdAsync(id, TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task GetByIdAsync_ReturnsDto_WhenFound()
    {
        var dto = CreateDto();
        var repository = new Mock<IProductRepository>();
        repository
            .Setup(r => r.GetByIdAsync(dto.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(dto);
        var service = CreateService(repository.Object);

        var result = await service.GetByIdAsync(dto.Id, TestContext.Current.CancellationToken);

        Assert.Same(dto, result);
    }

    [Fact]
    public async Task PostAsync_ThrowsBadRequest_WhenSkuEmpty()
    {
        var service = CreateService();

        var exception = await Assert.ThrowsAsync<BadRequestException>(() =>
            service.PostAsync(new ProductServicePostRequest
            {
                Sku = " ",
                Name = "Widget",
                Price = "1.00"
            }, TestContext.Current.CancellationToken));

        Assert.Equal("Sku cannot be empty.", exception.Message);
    }

    [Fact]
    public async Task PostAsync_ThrowsBadRequest_WhenNameEmpty()
    {
        var service = CreateService();

        var exception = await Assert.ThrowsAsync<BadRequestException>(() =>
            service.PostAsync(new ProductServicePostRequest
            {
                Sku = "SKU-1",
                Name = "",
                Price = "1.00"
            }, TestContext.Current.CancellationToken));

        Assert.Equal("Name cannot be empty.", exception.Message);
    }

    [Fact]
    public async Task PostAsync_UpsertsNewDto()
    {
        var repository = new Mock<IProductRepository>();
        ProductDto? upserted = null;
        repository
            .Setup(r => r.UpsertAsync(It.IsAny<ProductDto>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((ProductDto item, CancellationToken _) =>
            {
                upserted = item;
                return item;
            });
        var service = CreateService(repository.Object);

        var result = await service.PostAsync(new ProductServicePostRequest
        {
            Sku = "SKU-1",
            Name = "Widget",
            Price = "12.50"
        }, TestContext.Current.CancellationToken);

        Assert.NotEqual(Guid.Empty, result.Id);
        Assert.Equal("SKU-1", result.Sku);
        Assert.Equal("Widget", result.Name);
        Assert.Equal("12.50", result.Price);
        Assert.Same(upserted, result);
    }

    [Fact]
    public async Task PutAsync_ThrowsNoChanges_WhenExistingMatches()
    {
        var existing = CreateDto(sku: "SKU-1", name: "Widget", price: "9.99");
        var repository = new Mock<IProductRepository>();
        repository
            .Setup(r => r.GetByIdAsync(existing.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(existing);
        var service = CreateService(repository.Object);

        await Assert.ThrowsAsync<NoChangesToModifyException>(() =>
            service.PutAsync(new ProductServicePutRequest
            {
                Id = existing.Id,
                Sku = existing.Sku,
                Name = existing.Name,
                Price = existing.Price
            }, TestContext.Current.CancellationToken));

        repository.Verify(r => r.UpsertAsync(It.IsAny<ProductDto>(), It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task PutAsync_PreservesCreatedAt_WhenUpdatingExisting()
    {
        var createdAt = DateTime.UtcNow.AddDays(-3);
        var existing = CreateDto(createdAtUtc: createdAt, updatedAtUtc: createdAt);
        var repository = new Mock<IProductRepository>();
        repository
            .Setup(r => r.GetByIdAsync(existing.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(existing);
        repository
            .Setup(r => r.UpsertAsync(It.IsAny<ProductDto>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((ProductDto item, CancellationToken _) => item);
        var service = CreateService(repository.Object);

        var result = await service.PutAsync(new ProductServicePutRequest
        {
            Id = existing.Id,
            Sku = "SKU-2",
            Name = "Gadget",
            Price = "19.99"
        }, TestContext.Current.CancellationToken);

        Assert.Equal(createdAt, result.CreatedAtUtc);
        Assert.Equal("SKU-2", result.Sku);
        Assert.Equal("Gadget", result.Name);
        Assert.Equal("19.99", result.Price);
    }

    [Fact]
    public async Task PatchAsync_ThrowsNoChanges_WhenNoFieldsProvided()
    {
        var service = CreateService();

        await Assert.ThrowsAsync<NoChangesToModifyException>(() =>
            service.PatchAsync(new ProductServicePatchRequest
            {
                Id = Guid.NewGuid(),
                Sku = null,
                Name = null,
                Price = null
            }, TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task PatchAsync_ThrowsResourceNotFound_WhenMissing()
    {
        var id = Guid.NewGuid();
        var repository = new Mock<IProductRepository>();
        repository
            .Setup(r => r.GetByIdAsync(id, It.IsAny<CancellationToken>()))
            .ReturnsAsync((ProductDto?) null);
        var service = CreateService(repository.Object);

        await Assert.ThrowsAsync<ResourceNotFoundException>(() =>
            service.PatchAsync(new ProductServicePatchRequest
            {
                Id = id,
                Sku = "SKU-2",
                Name = null,
                Price = null
            }, TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task PatchAsync_MergesFields_AndUpserts()
    {
        var existing = CreateDto(sku: "SKU-1", name: "Widget", price: "9.99");
        var repository = new Mock<IProductRepository>();
        repository
            .Setup(r => r.GetByIdAsync(existing.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(existing);
        repository
            .Setup(r => r.UpsertAsync(It.IsAny<ProductDto>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((ProductDto item, CancellationToken _) => item);
        var service = CreateService(repository.Object);

        var result = await service.PatchAsync(new ProductServicePatchRequest
        {
            Id = existing.Id,
            Sku = "SKU-2",
            Name = null,
            Price = null
        }, TestContext.Current.CancellationToken);

        Assert.Equal("SKU-2", result.Sku);
        Assert.Equal(existing.Name, result.Name);
        Assert.Equal(existing.Price, result.Price);
        Assert.Equal(existing.CreatedAtUtc, result.CreatedAtUtc);
    }

    [Fact]
    public async Task SearchAsync_DelegatesToRepository()
    {
        var parameters = new ProductServiceSearchRequest
        {
            PageSize = 10,
            CreatedBeforeUtc = null,
            CreatedAfterUtc = null,
            UpdatedBeforeUtc = null,
            UpdatedAfterUtc = null,
            Sku = "SKU-1",
            SkuContains = null,
            Name = null,
            NameContains = null,
            Price = null,
            PriceGreaterThan = null,
            PriceLessThan = null
        };
        var continuation = Guid.NewGuid();
        var expected = new ProductSearchResponse
        {
            ContinuationToken = null,
            Records = [CreateDto()]
        };
        var repository = new Mock<IProductRepository>();
        repository
            .Setup(r => r.SearchAsync(parameters, continuation, It.IsAny<CancellationToken>()))
            .ReturnsAsync(expected);
        var service = CreateService(repository.Object);

        var result = await service.SearchAsync(parameters, continuation, TestContext.Current.CancellationToken);

        Assert.Same(expected, result);
    }
}
