using RedShirt.Example.Api.Core.UseCases.Order.Commands.Create;

namespace RedShirt.Example.Api.Core.UnitTests.Tests.UseCases.Order.Commands.Create;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class CreateOrderCommandValidatorTests
{
    private readonly CreateOrderCommandValidator _validator = new();

    [Theory]
    [InlineData("not-a-decimal")]
    [InlineData("12.34.56")]
    public async Task Validate_Fails_WhenTotalAmountIsNotAValidDecimal(string totalAmount)
    {
        var result = await _validator.ValidateAsync(
            new CreateOrderCommand(Guid.NewGuid(), "Pending", totalAmount, "idem-1"),
            TestContext.Current.CancellationToken);

        Assert.False(result.IsValid);
        Assert.Contains(result.Errors,
            error => error.ErrorMessage == "'Total Amount' must be a valid decimal number");
    }

    [Fact]
    public async Task Validate_Succeeds_WhenTotalAmountIsAValidDecimal()
    {
        var result = await _validator.ValidateAsync(
            new CreateOrderCommand(Guid.NewGuid(), "Pending", "42.00", "idem-1"),
            TestContext.Current.CancellationToken);

        Assert.True(result.IsValid);
    }
}
