using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using RedShirt.Example.Api.Authorization;
using RedShirt.Example.Api.Constants;

namespace RedShirt.Example.Api.UnitTests.Tests.Authorization;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class ApiAccessAuthorizationHandlerTests
{
    private static AuthorizationHandlerContext CreateContext(
        ClaimsPrincipal user,
        ApiAccessRequirement requirement,
        object? resource)
    {
        return new AuthorizationHandlerContext([requirement], user, resource);
    }

    private static ClaimsPrincipal PrincipalWithRoles(params string[] roles)
    {
        var identity = new ClaimsIdentity("test");
        foreach (var role in roles)
        {
            identity.AddClaim(new Claim("role", role));
        }

        // Match JWT RoleClaimType = "role" used by the API.
        identity = new ClaimsIdentity(
            identity.Claims,
            authenticationType: "test",
            nameType: "preferred_username",
            roleType: "role");

        return new ClaimsPrincipal(identity);
    }

    [Fact]
    public async Task HandleAsync_ApiUser_SucceedsOnWriteRequirement()
    {
        var requirement = new ApiAccessRequirement {ReadOnlyApprovedEndpoint = false};
        var context = CreateContext(PrincipalWithRoles(AuthorizationRoles.ApiUser), requirement, null);
        var handler = new ApiAccessAuthorizationHandler();

        await handler.HandleAsync(context);

        Assert.True(context.HasSucceeded);
    }

    [Fact]
    public async Task HandleAsync_ApiReadOnly_FailsOnWriteRequirement()
    {
        var requirement = new ApiAccessRequirement {ReadOnlyApprovedEndpoint = false};
        var httpContext = new DefaultHttpContext();
        httpContext.Request.Method = HttpMethods.Get;
        var context = CreateContext(
            PrincipalWithRoles(AuthorizationRoles.ApiReadOnly),
            requirement,
            httpContext);
        var handler = new ApiAccessAuthorizationHandler();

        await handler.HandleAsync(context);

        Assert.False(context.HasSucceeded);
    }

    [Fact]
    public async Task HandleAsync_ApiReadOnly_SucceedsOnApprovedGet()
    {
        var requirement = new ApiAccessRequirement {ReadOnlyApprovedEndpoint = true};
        var httpContext = new DefaultHttpContext();
        httpContext.Request.Method = HttpMethods.Get;
        var context = CreateContext(
            PrincipalWithRoles(AuthorizationRoles.ApiReadOnly),
            requirement,
            httpContext);
        var handler = new ApiAccessAuthorizationHandler();

        await handler.HandleAsync(context);

        Assert.True(context.HasSucceeded);
    }

    [Fact]
    public async Task HandleAsync_ApiReadOnly_FailsOnApprovedEndpointWhenNotGet()
    {
        var requirement = new ApiAccessRequirement {ReadOnlyApprovedEndpoint = true};
        var httpContext = new DefaultHttpContext();
        httpContext.Request.Method = HttpMethods.Post;
        var context = CreateContext(
            PrincipalWithRoles(AuthorizationRoles.ApiReadOnly),
            requirement,
            httpContext);
        var handler = new ApiAccessAuthorizationHandler();

        await handler.HandleAsync(context);

        Assert.False(context.HasSucceeded);
    }

    [Fact]
    public async Task HandleAsync_ApiUser_SucceedsOnApprovedGet()
    {
        var requirement = new ApiAccessRequirement {ReadOnlyApprovedEndpoint = true};
        var httpContext = new DefaultHttpContext();
        httpContext.Request.Method = HttpMethods.Get;
        var context = CreateContext(
            PrincipalWithRoles(AuthorizationRoles.ApiUser),
            requirement,
            httpContext);
        var handler = new ApiAccessAuthorizationHandler();

        await handler.HandleAsync(context);

        Assert.True(context.HasSucceeded);
    }

    [Fact]
    public async Task HandleAsync_Unauthenticated_DoesNotSucceed()
    {
        var requirement = new ApiAccessRequirement {ReadOnlyApprovedEndpoint = true};
        var httpContext = new DefaultHttpContext();
        httpContext.Request.Method = HttpMethods.Get;
        var context = CreateContext(new ClaimsPrincipal(new ClaimsIdentity()), requirement, httpContext);
        var handler = new ApiAccessAuthorizationHandler();

        await handler.HandleAsync(context);

        Assert.False(context.HasSucceeded);
    }
}
