using RedShirt.Example.Api.Authorization;
using RedShirt.Example.Api.Authorization.Constants;

namespace RedShirt.Example.Api.UnitTests.Tests.Authorization;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class BespokeRolePermissionMapTests
{
    private static readonly string[] FullAccessPermissions =
    [
        BespokeAuthorizationPermissions.Read,
        BespokeAuthorizationPermissions.Write,
        BespokeAuthorizationPermissions.CustomerRead,
        BespokeAuthorizationPermissions.CustomerWrite,
        BespokeAuthorizationPermissions.OrderRead,
        BespokeAuthorizationPermissions.OrderWrite,
        BespokeAuthorizationPermissions.ProductRead,
        BespokeAuthorizationPermissions.ProductWrite,
        BespokeAuthorizationPermissions.UploadRead,
        BespokeAuthorizationPermissions.UploadWrite
    ];

    private static readonly string[] AdminPermissions =
    [
        BespokeAuthorizationPermissions.Read,
        BespokeAuthorizationPermissions.Unrestricted,
        BespokeAuthorizationPermissions.Write,
        BespokeAuthorizationPermissions.CustomerRead,
        BespokeAuthorizationPermissions.CustomerWrite,
        BespokeAuthorizationPermissions.OrderRead,
        BespokeAuthorizationPermissions.OrderWrite,
        BespokeAuthorizationPermissions.ProductRead,
        BespokeAuthorizationPermissions.ProductWrite,
        BespokeAuthorizationPermissions.UploadRead,
        BespokeAuthorizationPermissions.UploadWrite
    ];

    [Fact]
    public void GetPermissions_Admin_GrantsFullAccessIncludingUnrestricted()
    {
        var permissions = BespokeRolePermissionMap.GetPermissions([BespokeAuthorizationRoles.Admin]);

        Assert.Equal(AdminPermissions.Order(StringComparer.Ordinal), permissions.Order(StringComparer.Ordinal));
    }

    [Fact]
    public void GetPermissions_Analyst_GrantsProductReadOnly()
    {
        var permissions = BespokeRolePermissionMap.GetPermissions([BespokeAuthorizationRoles.Analyst]);

        Assert.Equal([BespokeAuthorizationPermissions.ProductRead], permissions.Order(StringComparer.Ordinal));
    }

    [Fact]
    public void GetPermissions_Billing_GrantsOrderReadAndWrite()
    {
        var permissions = BespokeRolePermissionMap.GetPermissions([BespokeAuthorizationRoles.Billing]);

        Assert.Equal(
            [BespokeAuthorizationPermissions.OrderRead, BespokeAuthorizationPermissions.OrderWrite],
            permissions.Order(StringComparer.Ordinal));
    }

    [Fact]
    public void GetPermissions_CombinedRoles_UnionsWithoutDuplicates()
    {
        var permissions = BespokeRolePermissionMap.GetPermissions(
            [BespokeAuthorizationRoles.Analyst, BespokeAuthorizationRoles.Billing]);

        Assert.Equal(
            [
                BespokeAuthorizationPermissions.OrderRead,
                BespokeAuthorizationPermissions.OrderWrite,
                BespokeAuthorizationPermissions.ProductRead
            ],
            permissions.Order(StringComparer.Ordinal));
    }

    [Fact]
    public void GetPermissions_Developer_GrantsFullAccessWithoutUnrestricted()
    {
        var permissions = BespokeRolePermissionMap.GetPermissions([BespokeAuthorizationRoles.Developer]);

        Assert.Equal(FullAccessPermissions, permissions.Order(StringComparer.Ordinal));
        Assert.DoesNotContain(BespokeAuthorizationPermissions.Unrestricted, permissions);
    }

    [Fact]
    public void GetPermissions_UnknownRole_GrantsNothing()
    {
        Assert.Empty(BespokeRolePermissionMap.GetPermissions(["not-a-role"]));
    }
}