using RedShirt.Example.Api.Authorization;
using RedShirt.Example.Api.Authorization.Constants;
using RedShirt.Example.Api.Constants;

namespace RedShirt.Example.Api.UnitTests.Tests.Authorization;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class BespokeRolePermissionMapTests
{
    [Fact]
    public void GetPermissions_ApiReadOnly_GrantsReadOnly()
    {
        var permissions = BespokeRolePermissionMap.GetPermissions([BespokeAuthorizationRoles.ApiReadOnly]);

        Assert.Equal([BespokeAuthorizationPermissions.Read], permissions.Order(StringComparer.Ordinal));
    }

    [Fact]
    public void GetPermissions_ApiUser_GrantsReadAndWrite()
    {
        var permissions = BespokeRolePermissionMap.GetPermissions([BespokeAuthorizationRoles.ApiUser]);

        Assert.Equal(
            [BespokeAuthorizationPermissions.Read, BespokeAuthorizationPermissions.Write],
            permissions.Order(StringComparer.Ordinal));
    }

    [Fact]
    public void GetPermissions_UnknownRole_GrantsNothing()
    {
        Assert.Empty(BespokeRolePermissionMap.GetPermissions(["not-a-role"]));
    }

    [Fact]
    public void GetPermissions_CombinedRoles_UnionsWithoutDuplicates()
    {
        var permissions = BespokeRolePermissionMap.GetPermissions(
            [BespokeAuthorizationRoles.ApiUser, BespokeAuthorizationRoles.ApiReadOnly]);

        Assert.Equal(
            [BespokeAuthorizationPermissions.Read, BespokeAuthorizationPermissions.Write],
            permissions.Order(StringComparer.Ordinal));
    }
}
