using RedShirt.Example.Api.Authorization;
using RedShirt.Example.Api.Authorization.Constants;
using System.Security.Claims;

namespace RedShirt.Example.Api.UnitTests.Tests.Authorization;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class BespokeRolePermissionClaimsTransformationTests
{
    private static ClaimsPrincipal PrincipalWithRoles(params string[] roles)
    {
        var identity = new ClaimsIdentity(
            roles.Select(role => new Claim("role", role)),
            "test",
            "preferred_username",
            "role");

        return new ClaimsPrincipal(identity);
    }

    [Fact]
    public async Task TransformAsync_Admin_AddsUnrestrictedPermissionClaim()
    {
        var transformation = new BespokeRolePermissionClaimsTransformation();

        var principal = await transformation.TransformAsync(PrincipalWithRoles(BespokeAuthorizationRoles.Admin));

        Assert.Contains(
            BespokeAuthorizationPermissions.Unrestricted,
            principal.FindAll(BespokeAuthorizationPermissions.ClaimType).Select(claim => claim.Value));
    }

    [Fact]
    public async Task TransformAsync_AlreadyHasPermissionClaim_DoesNotAddAgain()
    {
        var identity = new ClaimsIdentity("test", "preferred_username", "role");
        identity.AddClaim(new Claim("role", BespokeAuthorizationRoles.Admin));
        identity.AddClaim(new Claim(BespokeAuthorizationPermissions.ClaimType, "preexisting"));
        var transformation = new BespokeRolePermissionClaimsTransformation();

        var principal = await transformation.TransformAsync(new ClaimsPrincipal(identity));

        Assert.Equal(
            ["preexisting"],
            principal.FindAll(BespokeAuthorizationPermissions.ClaimType).Select(claim => claim.Value));
    }

    [Fact]
    public async Task TransformAsync_Analyst_AddsProductReadPermissionClaim()
    {
        var transformation = new BespokeRolePermissionClaimsTransformation();

        var principal = await transformation.TransformAsync(PrincipalWithRoles(BespokeAuthorizationRoles.Analyst));

        Assert.Equal(
            [BespokeAuthorizationPermissions.ProductRead],
            principal.FindAll(BespokeAuthorizationPermissions.ClaimType).Select(claim => claim.Value));
    }

    [Fact]
    public async Task TransformAsync_Developer_AddsFullAccessPermissionClaimsWithoutUnrestricted()
    {
        var transformation = new BespokeRolePermissionClaimsTransformation();

        var principal = await transformation.TransformAsync(PrincipalWithRoles(BespokeAuthorizationRoles.Developer));

        var permissions = principal.FindAll(BespokeAuthorizationPermissions.ClaimType)
            .Select(claim => claim.Value)
            .ToList();
        Assert.Equal(
            [
                BespokeAuthorizationPermissions.Read,
                BespokeAuthorizationPermissions.Write,
                BespokeAuthorizationPermissions.CustomerRead,
                BespokeAuthorizationPermissions.CustomerWrite,
                BespokeAuthorizationPermissions.OrderRead,
                BespokeAuthorizationPermissions.OrderWrite,
                BespokeAuthorizationPermissions.ProductRead,
                BespokeAuthorizationPermissions.ProductWrite,
                BespokeAuthorizationPermissions.UploadRead,
                BespokeAuthorizationPermissions.UploadWrite
            ],
            permissions.Order(StringComparer.Ordinal));
        Assert.DoesNotContain(BespokeAuthorizationPermissions.Unrestricted, permissions);
    }

    [Fact]
    public async Task TransformAsync_Unauthenticated_DoesNotAddClaims()
    {
        var transformation = new BespokeRolePermissionClaimsTransformation();
        var principal = new ClaimsPrincipal(new ClaimsIdentity());

        var result = await transformation.TransformAsync(principal);

        Assert.Empty(result.FindAll(BespokeAuthorizationPermissions.ClaimType));
    }
}