using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using RedShirt.Example.Api.Authorization;
using RedShirt.Example.Api.Authorization.Constants;
using RedShirt.Example.Api.Authorization.ResourceScoping;
using RedShirt.Example.Api.Authorization.ResourceScoping.Customer;
using RedShirt.Example.Api.Constants;

namespace RedShirt.Example.Api.UnitTests.Tests.Authorization;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class CustomerScopedResourceEnforcerHandlerTests
{
    private static readonly Guid CustomerId = Guid.Parse("11111111-1111-1111-1111-111111111111");

    private static AuthorizationHandlerContext CreateContext(ClaimsPrincipal user, Guid resourceCustomerId)
    {
        return new AuthorizationHandlerContext(
            [new CustomerScopedResourceRequirement()],
            user,
            new CustomerScopedResource(resourceCustomerId));
    }

    private static ClaimsPrincipal Principal(params Claim[] claims)
    {
        var identity = new ClaimsIdentity(
            claims,
            authenticationType: "test",
            nameType: "preferred_username",
            roleType: "role");
        return new ClaimsPrincipal(identity);
    }

    [Fact]
    public async Task HandleAsync_WritePermission_SucceedsForAnyCustomer()
    {
        var user = Principal(new Claim(BespokeAuthorizationPermissions.ClaimType, BespokeAuthorizationPermissions.Write));
        var context = CreateContext(user, Guid.NewGuid());
        var handler = new CustomerScopedResourceEnforcerHandler();

        await handler.HandleAsync(context);

        Assert.True(context.HasSucceeded);
    }

    [Fact]
    public async Task HandleAsync_MatchingCustomerId_Succeeds()
    {
        var user = Principal(
            new Claim(BespokeAuthorizationPermissions.ClaimType, BespokeAuthorizationPermissions.Read),
            new Claim(BespokeAuthorizationClaims.CustomerId, CustomerId.ToString()));
        var context = CreateContext(user, CustomerId);
        var handler = new CustomerScopedResourceEnforcerHandler();

        await handler.HandleAsync(context);

        Assert.True(context.HasSucceeded);
    }

    [Fact]
    public async Task HandleAsync_MismatchedCustomerId_DoesNotSucceed()
    {
        var user = Principal(
            new Claim(BespokeAuthorizationPermissions.ClaimType, BespokeAuthorizationPermissions.Read),
            new Claim(BespokeAuthorizationClaims.CustomerId, CustomerId.ToString()));
        var context = CreateContext(user, Guid.NewGuid());
        var handler = new CustomerScopedResourceEnforcerHandler();

        await handler.HandleAsync(context);

        Assert.False(context.HasSucceeded);
    }

    [Fact]
    public async Task HandleAsync_ReadWithoutCustomerClaim_DoesNotSucceed()
    {
        var user = Principal(new Claim(BespokeAuthorizationPermissions.ClaimType, BespokeAuthorizationPermissions.Read));
        var context = CreateContext(user, CustomerId);
        var handler = new CustomerScopedResourceEnforcerHandler();

        await handler.HandleAsync(context);

        Assert.False(context.HasSucceeded);
    }
}
