using System.Security.Claims;
using Microsoft.Extensions.DependencyInjection;
using RedShirt.Example.Api.Authorization;
using RedShirt.Example.Api.Authorization.Constants;
using RedShirt.Example.Api.Authorization.ResourceScoping;
using RedShirt.Example.Api.Authorization.ResourceScoping.Customer;
using RedShirt.Example.Api.Common.Exceptions.Responses;
using RedShirt.Example.Api.Constants;
using RedShirt.Example.Api.Extensions;

namespace RedShirt.Example.Api.UnitTests.Tests.Authorization;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class CustomerScopedResourceAuthorizerTests
{
    private static readonly Guid CustomerId = Guid.Parse("11111111-1111-1111-1111-111111111111");

    private static ClaimsPrincipal Principal(params Claim[] claims)
    {
        var identity = new ClaimsIdentity(
            claims,
            authenticationType: "test",
            nameType: "preferred_username",
            roleType: "role");
        return new ClaimsPrincipal(identity);
    }

    private static ICustomerScopedResourceAuthorizer CreateAuthorizer()
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddApiAuthorizationPolicies();
        return services.BuildServiceProvider().GetRequiredService<ICustomerScopedResourceAuthorizer>();
    }

    [Fact]
    public async Task EnsureCanAccessAsync_WriteUser_AllowsAnyCustomer()
    {
        var authorizer = CreateAuthorizer();
        var user = Principal(new Claim(BespokeAuthorizationPermissions.ClaimType, BespokeAuthorizationPermissions.Write));

        await authorizer.EnsureCanAccessAsync(user, Guid.NewGuid());
    }

    [Fact]
    public async Task EnsureCanAccessAsync_MismatchedCustomer_ThrowsNotFound()
    {
        var authorizer = CreateAuthorizer();
        var user = Principal(
            new Claim(BespokeAuthorizationPermissions.ClaimType, BespokeAuthorizationPermissions.Read),
            new Claim(BespokeAuthorizationClaims.CustomerId, CustomerId.ToString()));

        await Assert.ThrowsAsync<ResourceNotFoundException>(() =>
            authorizer.EnsureCanAccessAsync(user, Guid.NewGuid()));
    }

    [Fact]
    public void ConstrainSearchCustomerId_Unrestricted_KeepsRequestedFilter()
    {
        var authorizer = CreateAuthorizer();
        var user = Principal(new Claim(BespokeAuthorizationPermissions.ClaimType, BespokeAuthorizationPermissions.Write));
        var requested = Guid.NewGuid();

        Assert.Equal(requested, authorizer.ConstrainSearchCustomerId(user, requested));
        Assert.Null(authorizer.ConstrainSearchCustomerId(user, null));
    }

    [Fact]
    public void ConstrainSearchCustomerId_Scoped_ForcesOwnCustomerId()
    {
        var authorizer = CreateAuthorizer();
        var user = Principal(
            new Claim(BespokeAuthorizationPermissions.ClaimType, BespokeAuthorizationPermissions.Read),
            new Claim(BespokeAuthorizationClaims.CustomerId, CustomerId.ToString()));

        Assert.Equal(CustomerId, authorizer.ConstrainSearchCustomerId(user, null));
        Assert.Equal(CustomerId, authorizer.ConstrainSearchCustomerId(user, CustomerId));
        Assert.Equal(Guid.Empty, authorizer.ConstrainSearchCustomerId(user, Guid.NewGuid()));
    }

    [Fact]
    public void ConstrainSearchCustomerId_ScopedWithoutClaim_MatchesNothing()
    {
        var authorizer = CreateAuthorizer();
        var user = Principal(new Claim(BespokeAuthorizationPermissions.ClaimType, BespokeAuthorizationPermissions.Read));

        Assert.Equal(Guid.Empty, authorizer.ConstrainSearchCustomerId(user, null));
    }
}
