using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using RedShirt.Example.Api.Authorization;
using RedShirt.Example.Api.Authorization.Requirements;

namespace RedShirt.Example.Api.UnitTests.Tests.Authorization;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class HttpGetAuthorizationHandlerTests
{
    private static AuthorizationHandlerContext CreateContext(object? resource)
    {
        var user = new ClaimsPrincipal(new ClaimsIdentity("test"));
        return new AuthorizationHandlerContext([new HttpGetRequirement()], user, resource);
    }

    [Fact]
    public async Task HandleAsync_Get_Succeeds()
    {
        var httpContext = new DefaultHttpContext();
        httpContext.Request.Method = HttpMethods.Get;
        var context = CreateContext(httpContext);
        var handler = new HttpGetAuthorizationHandler();

        await handler.HandleAsync(context);

        Assert.True(context.HasSucceeded);
    }

    [Fact]
    public async Task HandleAsync_Post_DoesNotSucceed()
    {
        var httpContext = new DefaultHttpContext();
        httpContext.Request.Method = HttpMethods.Post;
        var context = CreateContext(httpContext);
        var handler = new HttpGetAuthorizationHandler();

        await handler.HandleAsync(context);

        Assert.False(context.HasSucceeded);
    }

    [Fact]
    public void IsHttpGet_HttpRequest_UsesMethod()
    {
        var httpContext = new DefaultHttpContext();
        httpContext.Request.Method = HttpMethods.Get;

        Assert.True(HttpGetAuthorizationHandler.IsHttpGet(httpContext.Request));
        httpContext.Request.Method = HttpMethods.Put;
        Assert.False(HttpGetAuthorizationHandler.IsHttpGet(httpContext.Request));
    }
}
