using RedShirt.Example.Api.Authorization;
using RedShirt.Example.Api.Constants;

namespace RedShirt.Example.Api.UnitTests.Tests.Authorization;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class RolePermissionMapTests
{
    [Fact]
    public void GetPermissions_ApiReadOnly_GrantsReadOnly()
    {
        var permissions = RolePermissionMap.GetPermissions([AuthorizationRoles.ApiReadOnly]);

        Assert.Equal([AuthorizationPermissions.Read], permissions.Order(StringComparer.Ordinal));
    }

    [Fact]
    public void GetPermissions_ApiUser_GrantsReadAndWrite()
    {
        var permissions = RolePermissionMap.GetPermissions([AuthorizationRoles.ApiUser]);

        Assert.Equal(
            [AuthorizationPermissions.Read, AuthorizationPermissions.Write],
            permissions.Order(StringComparer.Ordinal));
    }

    [Fact]
    public void GetPermissions_UnknownRole_GrantsNothing()
    {
        Assert.Empty(RolePermissionMap.GetPermissions(["not-a-role"]));
    }

    [Fact]
    public void GetPermissions_CombinedRoles_UnionsWithoutDuplicates()
    {
        var permissions = RolePermissionMap.GetPermissions(
            [AuthorizationRoles.ApiUser, AuthorizationRoles.ApiReadOnly]);

        Assert.Equal(
            [AuthorizationPermissions.Read, AuthorizationPermissions.Write],
            permissions.Order(StringComparer.Ordinal));
    }
}
