using System.Security.Claims;
using RedShirt.Example.Api.Authorization;
using RedShirt.Example.Api.Constants;

namespace RedShirt.Example.Api.UnitTests.Tests.Authorization;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class RolePermissionClaimsTransformationTests
{
    private static ClaimsPrincipal PrincipalWithRoles(params string[] roles)
    {
        var identity = new ClaimsIdentity(
            roles.Select(role => new Claim("role", role)),
            authenticationType: "test",
            nameType: "preferred_username",
            roleType: "role");

        return new ClaimsPrincipal(identity);
    }

    [Fact]
    public async Task TransformAsync_ApiUser_AddsReadAndWritePermissionClaims()
    {
        var transformation = new RolePermissionClaimsTransformation();

        var principal = await transformation.TransformAsync(PrincipalWithRoles(AuthorizationRoles.ApiUser));

        var permissions = principal.FindAll(AuthorizationPermissions.ClaimType).Select(claim => claim.Value);
        Assert.Equal(
            [AuthorizationPermissions.Read, AuthorizationPermissions.Write],
            permissions.Order(StringComparer.Ordinal));
    }

    [Fact]
    public async Task TransformAsync_ApiReadOnly_AddsReadPermissionClaim()
    {
        var transformation = new RolePermissionClaimsTransformation();

        var principal = await transformation.TransformAsync(PrincipalWithRoles(AuthorizationRoles.ApiReadOnly));

        Assert.Equal(
            [AuthorizationPermissions.Read],
            principal.FindAll(AuthorizationPermissions.ClaimType).Select(claim => claim.Value));
    }

    [Fact]
    public async Task TransformAsync_AlreadyHasPermissionClaim_DoesNotAddAgain()
    {
        var identity = new ClaimsIdentity("test", "preferred_username", "role");
        identity.AddClaim(new Claim("role", AuthorizationRoles.ApiUser));
        identity.AddClaim(new Claim(AuthorizationPermissions.ClaimType, "preexisting"));
        var transformation = new RolePermissionClaimsTransformation();

        var principal = await transformation.TransformAsync(new ClaimsPrincipal(identity));

        Assert.Equal(
            ["preexisting"],
            principal.FindAll(AuthorizationPermissions.ClaimType).Select(claim => claim.Value));
    }

    [Fact]
    public async Task TransformAsync_Unauthenticated_DoesNotAddClaims()
    {
        var transformation = new RolePermissionClaimsTransformation();
        var principal = new ClaimsPrincipal(new ClaimsIdentity());

        var result = await transformation.TransformAsync(principal);

        Assert.Empty(result.FindAll(AuthorizationPermissions.ClaimType));
    }
}
