using Moq;
using RedShirt.Example.Api.Core.Cqrs;
using RedShirt.Example.Api.Core.UseCases.ExampleItem.Commands.Delete;
using RedShirt.Example.Api.Core.UseCases.ExampleItem.Services;

namespace RedShirt.Example.Api.Core.UnitTests.Tests.UseCases.ExampleItem.Commands.Delete;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class DeleteExampleItemCommandHandlerTests
{
    [Fact]
    public async Task Handle_DelegatesToRepository()
    {
        var repository = new Mock<IExampleItemRepository>();
        repository
            .Setup(r => r.DeleteByName("widget", TestContext.Current.CancellationToken))
            .Returns(Task.CompletedTask);
        var handler = new DeleteExampleItemCommandHandler(
            repository.Object,
            new Mock<ICoreRequestValidator>().Object);

        await handler.Handle(new DeleteExampleItemCommand("widget"), TestContext.Current.CancellationToken);

        repository.Verify(r => r.DeleteByName("widget", TestContext.Current.CancellationToken), Times.Once);
    }
}