using RedShirt.Example.Api.Core.UseCases.Order.Queries.SearchRecords;
using RedShirt.Example.Api.DataStores.Order.Models.Generated;

namespace RedShirt.Example.Api.Core.UnitTests.Tests.UseCases.Order.Queries.SearchRecords;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class SearchOrderRecordsQueryValidatorTests
{
    private readonly SearchOrderRecordsQueryValidator _validator = new();

    [Fact]
    public async Task Validate_Succeeds_ForValidSearchRequest()
    {
        var query = new SearchOrderRecordsQuery(
            new OrderServiceSearchRequest
            {
                PageSize = 10,
                CreatedBeforeUtc = null,
                CreatedAfterUtc = null,
                UpdatedBeforeUtc = null,
                UpdatedAfterUtc = null,
                CustomerId = null,
                Status = null,
                StatusContains = null,
                TotalAmount = 42.00m,
                TotalAmountGreaterThan = null,
                TotalAmountLessThan = null,
                TotalPrice = null,
                TotalPriceGreaterThan = null,
                TotalPriceLessThan = null,
                TotalPriceIsNull = false
            },
            null);

        var result = await _validator.ValidateAsync(query, TestContext.Current.CancellationToken);

        Assert.True(result.IsValid);
    }
}