using RedShirt.Example.Api.Core.UseCases.Order.Queries.SearchRecords;
using RedShirt.Example.Api.DataStores.Order.Models.Generated;

namespace RedShirt.Example.Api.Core.UnitTests.Tests.UseCases.Order.Queries.SearchRecords;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class SearchOrderRecordsQueryValidatorTests
{
    private readonly SearchOrderRecordsQueryValidator _validator = new();

    [Theory]
    [InlineData(nameof(OrderServiceSearchRequest.TotalAmount), "not-a-decimal")]
    [InlineData(nameof(OrderServiceSearchRequest.TotalAmountGreaterThan), "12.34.56")]
    [InlineData(nameof(OrderServiceSearchRequest.TotalAmountLessThan), "abc")]
    [InlineData(nameof(OrderServiceSearchRequest.TotalPrice), "nope")]
    [InlineData(nameof(OrderServiceSearchRequest.TotalPriceGreaterThan), "1.2.3")]
    [InlineData(nameof(OrderServiceSearchRequest.TotalPriceLessThan), "xyz")]
    public async Task Validate_Fails_WhenDecimalFilterIsInvalid(string propertyName, string value)
    {
        var result = await _validator.ValidateAsync(
            CreateQuery(propertyName, value),
            TestContext.Current.CancellationToken);

        Assert.False(result.IsValid);
        Assert.Contains(result.Errors,
            error => error.ErrorMessage.Contains("must be a valid decimal number", StringComparison.Ordinal));
    }

    [Theory]
    [InlineData(nameof(OrderServiceSearchRequest.TotalAmount), null)]
    [InlineData(nameof(OrderServiceSearchRequest.TotalAmount), "42.00")]
    [InlineData(nameof(OrderServiceSearchRequest.TotalAmountGreaterThan), "0")]
    [InlineData(nameof(OrderServiceSearchRequest.TotalAmountLessThan), "100")]
    [InlineData(nameof(OrderServiceSearchRequest.TotalPrice), null)]
    [InlineData(nameof(OrderServiceSearchRequest.TotalPrice), "9.99")]
    [InlineData(nameof(OrderServiceSearchRequest.TotalPriceGreaterThan), "-1.5")]
    [InlineData(nameof(OrderServiceSearchRequest.TotalPriceLessThan), "1000")]
    public async Task Validate_Succeeds_WhenDecimalFilterIsNullOrValid(string propertyName, string? value)
    {
        var result = await _validator.ValidateAsync(
            CreateQuery(propertyName, value),
            TestContext.Current.CancellationToken);

        Assert.True(result.IsValid);
    }

    private static SearchOrderRecordsQuery CreateQuery(string propertyName, string? value)
    {
        return new SearchOrderRecordsQuery(
            new OrderServiceSearchRequest
            {
                PageSize = 10,
                CreatedBeforeUtc = null,
                CreatedAfterUtc = null,
                UpdatedBeforeUtc = null,
                UpdatedAfterUtc = null,
                CustomerId = null,
                Status = null,
                StatusContains = null,
                TotalAmount = propertyName == nameof(OrderServiceSearchRequest.TotalAmount) ? value : null,
                TotalAmountGreaterThan =
                    propertyName == nameof(OrderServiceSearchRequest.TotalAmountGreaterThan) ? value : null,
                TotalAmountLessThan =
                    propertyName == nameof(OrderServiceSearchRequest.TotalAmountLessThan) ? value : null,
                TotalPrice = propertyName == nameof(OrderServiceSearchRequest.TotalPrice) ? value : null,
                TotalPriceGreaterThan =
                    propertyName == nameof(OrderServiceSearchRequest.TotalPriceGreaterThan) ? value : null,
                TotalPriceLessThan =
                    propertyName == nameof(OrderServiceSearchRequest.TotalPriceLessThan) ? value : null,
                TotalPriceIsNull = false
            },
            null);
    }
}
