using RedShirt.Api.Example.Connectors.Bar.Implementation.Exceptions;

namespace RedShirt.Api.Example.Connectors.Bar.Implementation.UnitTests.Tests.Exceptions;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class BarImplementationExceptionTests
{
    [Fact]
    public void BarUnauthorizedException_UsesStableMessage()
    {
        var exception = new BarUnauthorizedException();

        Assert.Equal("Bar API rejected the bearer token.", exception.Message);
        Assert.Null(exception.InnerException);
    }

    [Fact]
    public void BarUnavailableException_UsesStableMessage()
    {
        var exception = new BarUnavailableException();

        Assert.Equal("Bar is assumed to be unavailable for the time being.", exception.Message);
        Assert.Null(exception.InnerException);
    }
}
