using Moq;
using RedShirt.Example.Api.Core.Cqrs;
using RedShirt.Example.Api.Core.UseCases.Product.Queries.GetRecord;
using RedShirt.Example.Api.DataStores.Product.Core.Models;
using RedShirt.Example.Api.DataStores.Product.Core.Services;

namespace RedShirt.Example.Api.Core.UnitTests.Tests.UseCases.Product.Queries.GetRecord;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class GetProductRecordQueryHandlerTests
{
    [Fact]
    public async Task Handle_ValidatesAndReturnsMappedDto()
    {
        var id = Guid.NewGuid();
        var created = DateTime.UtcNow.AddDays(-2);
        var internalDto = new ProductInternalDto
        {
            Id = id,
            CreatedAtUtc = created,
            UpdatedAtUtc = created,
            Sku = "SKU-1",
            Name = "Widget",
            Price = 19.99m
        };
        var productService = new Mock<IProductService>();
        productService
            .Setup(s => s.GetByIdAsync(id, TestContext.Current.CancellationToken))
            .ReturnsAsync(internalDto);
        var validator = new Mock<ICoreRequestValidator>();
        var handler = new GetProductRecordQueryHandler(productService.Object, validator.Object);
        var query = new GetProductRecordQuery(id);

        var result = await handler.Handle(query, TestContext.Current.CancellationToken);

        Assert.Equal(id, result.Id);
        Assert.Equal("SKU-1", result.Sku);
        Assert.Equal("Widget", result.Name);
        Assert.Equal("19.99", result.Price);
        validator.Verify(v => v.ValidateAsync(query, TestContext.Current.CancellationToken), Times.Once);
        productService.Verify(s => s.GetByIdAsync(id, TestContext.Current.CancellationToken), Times.Once);
    }
}