using FluentValidation;
using Microsoft.Extensions.DependencyInjection;
using RedShirt.Example.Api.Core.Cqrs;
using RedShirt.Example.Api.Core.UseCases.Order.Commands.Create;

namespace RedShirt.Example.Api.Core.UnitTests.Tests.Cqrs;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class CqrsValidatorLifetimeTests
{
    [Fact]
    public async Task RootProvider_CanResolveValidators_ThroughSingletonCoreRequestValidator()
    {
        var services = new ServiceCollection();
        services.AddSingleton<ICoreRequestValidator, CoreRequestValidator>();
        services.AddCqrsHandlers(typeof(CoreRequestValidator).Assembly);

        // Scoped validators would fail here when resolved via the singleton CoreRequestValidator.
        await using var provider = services.BuildServiceProvider(new ServiceProviderOptions
        {
            ValidateScopes = true
        });

        var validators = provider.GetServices<IValidator<CreateOrderCommand>>().ToArray();
        Assert.NotEmpty(validators);

        var coreRequestValidator = provider.GetRequiredService<ICoreRequestValidator>();
        await coreRequestValidator.ValidateAsync(
            new CreateOrderCommand(Guid.NewGuid(), "Pending", "12.34", null, "idem-1"),
            TestContext.Current.CancellationToken);
    }

    [Fact]
    public async Task RootProvider_Throws_WhenValidatorsAreRegisteredAsScoped()
    {
        var services = new ServiceCollection();
        services.AddSingleton<ICoreRequestValidator, CoreRequestValidator>();
        services.AddValidatorsFromAssembly(
            typeof(CreateOrderCommandValidator).Assembly,
            ServiceLifetime.Scoped);

        await using var provider = services.BuildServiceProvider(new ServiceProviderOptions
        {
            ValidateScopes = true
        });

        var coreRequestValidator = provider.GetRequiredService<ICoreRequestValidator>();

        var exception = await Assert.ThrowsAsync<InvalidOperationException>(() =>
            coreRequestValidator.ValidateAsync(
                new CreateOrderCommand(Guid.NewGuid(), "Pending", "12.34", null, "idem-1"),
                TestContext.Current.CancellationToken));

        Assert.Contains("Cannot resolve scoped service", exception.Message);
        Assert.Contains("IValidator", exception.Message);
    }
}
