using FluentValidation;
using Microsoft.Extensions.DependencyInjection;
using RedShirt.Example.Api.Core.Cqrs;
using RedShirt.Example.Api.Core.UnitTests.Tests.Cqrs.Fixtures;
using RedShirt.Example.Api.Core.UseCases.ExampleItem.Commands.Create;
using RedShirt.Example.Api.Core.UseCases.ExampleItem.Commands.Delete;
using RedShirt.Example.Api.Core.UseCases.ExampleItem.Queries.GetRecord;
using RedShirt.Example.Api.Core.UseCases.ExampleItem.Queries.ListRecords;

namespace RedShirt.Example.Api.Core.UnitTests.Tests.Cqrs;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class CqrsServiceCollectionExtensionsTests
{
    /// <summary>
    /// Silly little manual test to address a warning in sample fixtures.
    /// A little testing-your-tests-y, but it's a 2-liner. It's fine.
    /// </summary>
    [Fact]
    public void TestSampleCqrsResult()
    {
        var result = new SampleResult("foo");
        Assert.Equal("foo", result.Name);
    }
    
    [Fact]
    public void AddCqrsHandlers_ThrowsArgumentNullException_WhenServicesIsNull()
    {
        Assert.Throws<ArgumentNullException>(() =>
            CqrsServiceCollectionExtensions.AddCqrsHandlers(null!, typeof(CqrsServiceCollectionExtensions).Assembly));
    }

    [Fact]
    public void AddCqrsHandlers_ThrowsArgumentNullException_WhenAssemblyIsNull()
    {
        var services = new ServiceCollection();

        Assert.Throws<ArgumentNullException>(() => services.AddCqrsHandlers(null!));
    }

    [Fact]
    public void AddCqrsHandlers_RegistersIntermediateCqrsHandlerInterfaces_FromAssembly()
    {
        var services = new ServiceCollection();

        services.AddCqrsHandlers(typeof(SampleCommandHandler).Assembly);

        AssertRegisteredTransient<ISampleCommandHandler, SampleCommandHandler>(services);
        AssertRegisteredTransient<ISampleVoidCommandHandler, SampleVoidCommandHandler>(services);
    }

    [Fact]
    public void AddCqrsHandlers_DoesNotRegisterDirectICqrsHandlerInterfaces()
    {
        var services = new ServiceCollection();

        services.AddCqrsHandlers(typeof(DirectCqrsHandler).Assembly);

        Assert.DoesNotContain(services,
            descriptor => descriptor.ServiceType == typeof(ICqrsHandler<SampleCommand>));
        Assert.DoesNotContain(services,
            descriptor => descriptor.ServiceType == typeof(ICqrsHandler<SampleCommand, SampleResult>));
    }

    [Fact]
    public void AddCqrsHandlers_SkipsAbstractClasses()
    {
        var services = new ServiceCollection();

        services.AddCqrsHandlers(typeof(AbstractSampleCommandHandler).Assembly);

        Assert.DoesNotContain(services,
            descriptor => descriptor.ImplementationType == typeof(AbstractSampleCommandHandler));
    }

    [Fact]
    public void AddCqrsHandlers_RegistersKnownHandlers_FromCoreAssembly()
    {
        var services = new ServiceCollection();

        services.AddCqrsHandlers(typeof(CqrsServiceCollectionExtensions).Assembly);

        AssertRegisteredTransient<ICreateExampleItemCommandHandler, CreateExampleItemCommandHandler>(services);
        AssertRegisteredTransient<IDeleteExampleItemCommandHandler, DeleteExampleItemCommandHandler>(services);
        AssertRegisteredTransient<IGetExampleItemRecordQueryHandler, GetExampleItemRecordQueryHandler>(services);
        AssertRegisteredTransient<IListExampleItemRecordsQueryHandler, ListExampleItemRecordsQueryHandler>(
            services);
    }

    [Fact]
    public void AddCqrsHandlers_RegistersFluentValidationValidators_FromCoreAssembly()
    {
        var services = new ServiceCollection();

        services.AddCqrsHandlers(typeof(SampleCommandHandler).Assembly);

        Assert.Contains(services,
            descriptor => descriptor.ServiceType == typeof(IValidator<CreateExampleItemCommand>));
        Assert.Contains(services,
            descriptor => descriptor.ServiceType == typeof(IValidator<DeleteExampleItemCommand>));
        Assert.Contains(services,
            descriptor => descriptor.ServiceType == typeof(IValidator<GetExampleItemRecordQuery>));
    }

    [Fact]
    public void AddCqrsHandlers_ReturnsSameServiceCollection()
    {
        var services = new ServiceCollection();

        var result = services.AddCqrsHandlers(typeof(SampleCommandHandler).Assembly);

        Assert.Same(services, result);
    }

    [Fact]
    public void AddCqrsHandlers_ResolvesRegisteredFixtureHandler()
    {
        var services = new ServiceCollection();
        services.AddCqrsHandlers(typeof(SampleCommandHandler).Assembly);
        var provider = services.BuildServiceProvider();

        var handler = provider.GetRequiredService<ISampleCommandHandler>();

        Assert.IsType<SampleCommandHandler>(handler);
    }

    private static void AssertRegisteredTransient<TService, TImplementation>(IServiceCollection services)
    {
        Assert.Contains(services, descriptor =>
            descriptor.ServiceType == typeof(TService)
            && descriptor.ImplementationType == typeof(TImplementation)
            && descriptor.Lifetime == ServiceLifetime.Transient);
    }
}
