using Moq;
using RedShirt.Example.Api.Core.UseCases.ExampleItem.Models;
using RedShirt.Example.Api.Core.UseCases.ExampleItem.Queries.ListRecords;
using RedShirt.Example.Api.Core.UseCases.ExampleItem.Services;

namespace RedShirt.Example.Api.Core.UnitTests.Tests.UseCases.ExampleItem.Queries.ListRecords;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class ListExampleItemRecordsQueryHandlerTests
{
    [Fact]
    public async Task Handle_ReturnsRepositoryResult()
    {
        var expected = new ExampleItemListModel
        {
            ContinuationToken = "next",
            Items = [new ExampleItemModel {Name = "a"}]
        };
        var repository = new Mock<IExampleItemRepository>();
        repository
            .Setup(r => r.GetListAsync("token", TestContext.Current.CancellationToken))
            .ReturnsAsync(expected);
        var handler = new ListExampleItemRecordsQueryHandler(repository.Object);

        var result = await handler.Handle(
            new ListExampleItemRecordsQuery("token"),
            TestContext.Current.CancellationToken);

        Assert.Same(expected, result);
        repository.Verify(r => r.GetListAsync("token", TestContext.Current.CancellationToken), Times.Once);
    }
}