using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using Moq;
using RedShirt.Api.Example.Connectors.Common.Http.Exceptions;
using RedShirt.Api.Example.Connectors.Common.Http.Models;
using RedShirt.Api.Example.Connectors.Common.Http.Services;
using RedShirt.Example.Api.Common.SecretManagers.Core.Exceptions;
using RedShirt.Example.Api.Common.SecretManagers.Core.Models;
using RedShirt.Example.Api.Common.SecretManagers.Core.Services;
using System.Net;
using System.Text;

namespace RedShirt.Api.Example.Connectors.Common.Http.UnitTests.Tests.Services;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class OAuthTokenSourceTests
{
    private const string ClientIdPath = "/oauth/client-id";
    private const string ClientSecretPath = "/oauth/client-secret";

    private static OAuthClientCredentialsRequest Request()
    {
        return new OAuthClientCredentialsRequest
        {
            TokenUrl = "https://auth.example/oauth/token",
            ClientIdPath = ClientIdPath,
            ClientSecretPath = ClientSecretPath,
            ScopeLabel = "audience",
            ScopeValue = "https://api.example"
        };
    }

    private static OAuthTokenSource CreateSut(
        ISecretManagerCacheService secrets,
        HttpMessageHandler handler,
        int? fallbackMinutes = 30)
    {
        var httpClient = new HttpClient(handler);
        var factory = new Mock<IHttpClientFactory>(MockBehavior.Strict);
        factory.Setup(f => f.CreateClient(nameof(OAuthTokenSource))).Returns(httpClient);

        return new OAuthTokenSource(
            factory.Object,
            secrets,
            NullLogger<OAuthTokenSource>.Instance,
            Options.Create(new OAuthTokenSource.ConfigurationModel
            {
                FallbackJwtExpiryTimeMinutes = fallbackMinutes
            }));
    }

    [Fact]
    public void ConfigurationModel_EffectiveFallback_FloorsAtOneMinute()
    {
        var model = new OAuthTokenSource.ConfigurationModel
        {
            FallbackJwtExpiryTimeMinutes = 0
        };

        Assert.Equal(TimeSpan.FromMinutes(1), model.EffectiveFallbackJwtExpiryTimeMinutes);
    }

    [Fact]
    public async Task GetTokenAsync_PostsForm_AndReturnsAccessToken()
    {
        var secrets = new Mock<ISecretManagerCacheService>(MockBehavior.Strict);
        secrets
            .Setup(s => s.GetSecretsAsync(
                It.Is<List<string>>(keys => keys.SequenceEqual(new[] {ClientIdPath, ClientSecretPath})),
                null,
                false,
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(new SecretManagerCacheSecretsResponse
            {
                Values = new Dictionary<string, string>
                {
                    [ClientIdPath] = "client-id",
                    [ClientSecretPath] = "client-secret"
                },
                QueriedSecretManager = true
            });

        string? body = null;
        var handler = new StubHandler(async request =>
        {
            body = await request.Content!.ReadAsStringAsync(TestContext.Current.CancellationToken);
            return new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new StringContent(
                    """{"access_token":"access-xyz","expires_in":3600}""",
                    Encoding.UTF8,
                    "application/json")
            };
        });

        var sut = CreateSut(secrets.Object, handler);
        var result = await sut.GetTokenAsync(Request(), cancellationToken: TestContext.Current.CancellationToken);

        Assert.Equal("access-xyz", result.AccessToken);
        Assert.True(result.ExpiresAtUtc > DateTimeOffset.UtcNow.AddMinutes(30));
        Assert.Contains("grant_type=client_credentials", body);
        Assert.Contains("client_id=client-id", body);
        Assert.Contains("client_secret=client-secret", body);
        Assert.Contains("audience=https%3A%2F%2Fapi.example", body);
        secrets.VerifyAll();
    }

    [Fact]
    public async Task GetTokenAsync_ThrowsArgumentNull_WhenRequestIsNull()
    {
        var sut = CreateSut(
            new Mock<ISecretManagerCacheService>(MockBehavior.Strict).Object,
            new StubHandler(_ => new HttpResponseMessage(HttpStatusCode.OK)));

        await Assert.ThrowsAsync<ArgumentNullException>(() =>
            sut.GetTokenAsync(null!, cancellationToken: TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task GetTokenAsync_ThrowsOAuthRequestException_OnNonSuccessStatus()
    {
        var secrets = new Mock<ISecretManagerCacheService>(MockBehavior.Strict);
        secrets
            .Setup(s => s.GetSecretsAsync(It.IsAny<List<string>>(), null, false, It.IsAny<CancellationToken>()))
            .ReturnsAsync(new SecretManagerCacheSecretsResponse
            {
                Values = new Dictionary<string, string>
                {
                    [ClientIdPath] = "id",
                    [ClientSecretPath] = "secret"
                },
                QueriedSecretManager = false
            });

        var sut = CreateSut(secrets.Object,
            new StubHandler(_ => new HttpResponseMessage(HttpStatusCode.Unauthorized)));

        var ex = await Assert.ThrowsAsync<OAuthRequestException>(() =>
            sut.GetTokenAsync(Request(), cancellationToken: TestContext.Current.CancellationToken));

        Assert.Equal(HttpStatusCode.Unauthorized, ex.StatusCode);
        Assert.False(ex.CredentialStorageProblem);
        Assert.False(ex.FreshCredentialCacheResult);
    }

    [Fact]
    public async Task GetTokenAsync_ThrowsOAuthRequestJsonException_WhenAccessTokenMissing()
    {
        var secrets = new Mock<ISecretManagerCacheService>(MockBehavior.Strict);
        secrets
            .Setup(s => s.GetSecretsAsync(It.IsAny<List<string>>(), null, false, It.IsAny<CancellationToken>()))
            .ReturnsAsync(new SecretManagerCacheSecretsResponse
            {
                Values = new Dictionary<string, string>
                {
                    [ClientIdPath] = "id",
                    [ClientSecretPath] = "secret"
                },
                QueriedSecretManager = true
            });

        var sut = CreateSut(secrets.Object, new StubHandler(_ => new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new StringContent("""{"expires_in":60}""", Encoding.UTF8, "application/json")
        }));

        await Assert.ThrowsAsync<OAuthRequestJsonException>(() =>
            sut.GetTokenAsync(Request(), cancellationToken: TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task GetTokenAsync_UsesFallbackExpiry_WhenExpiresInMissing()
    {
        var secrets = new Mock<ISecretManagerCacheService>(MockBehavior.Strict);
        secrets
            .Setup(s => s.GetSecretsAsync(It.IsAny<List<string>>(), null, false, It.IsAny<CancellationToken>()))
            .ReturnsAsync(new SecretManagerCacheSecretsResponse
            {
                Values = new Dictionary<string, string>
                {
                    [ClientIdPath] = "id",
                    [ClientSecretPath] = "secret"
                },
                QueriedSecretManager = false
            });

        var handler = new StubHandler(_ => new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new StringContent("""{"access_token":"tok"}""", Encoding.UTF8, "application/json")
        });

        var before = DateTimeOffset.UtcNow;
        var sut = CreateSut(secrets.Object, handler, 15);
        var result = await sut.GetTokenAsync(Request(), cancellationToken: TestContext.Current.CancellationToken);

        Assert.Equal("tok", result.AccessToken);
        Assert.InRange(result.ExpiresAtUtc, before.AddMinutes(14), before.AddMinutes(16).AddSeconds(5));
    }

    [Fact]
    public async Task GetTokenAsync_WrapsSecretManagerFailure_AsOAuthRequestException()
    {
        var secrets = new Mock<ISecretManagerCacheService>(MockBehavior.Strict);
        secrets
            .Setup(s => s.GetSecretsAsync(It.IsAny<List<string>>(), null, true, It.IsAny<CancellationToken>()))
            .ThrowsAsync(new ApiSecretManagerException("ssm boom")
            {
                IsHandled = false,
                CouldBeTransient = true,
                CouldBeExternallySolvable = true
            });

        var sut = CreateSut(secrets.Object, new StubHandler(_ => new HttpResponseMessage(HttpStatusCode.OK)));

        var ex = await Assert.ThrowsAsync<OAuthRequestException>(() =>
            sut.GetTokenAsync(Request(), true, TestContext.Current.CancellationToken));

        Assert.True(ex.CredentialStorageProblem);
        Assert.True(ex.FreshCredentialCacheResult);
        Assert.Null(ex.StatusCode);
        Assert.IsType<ApiSecretManagerException>(ex.InnerException);
    }

    private sealed class StubHandler(Func<HttpRequestMessage, Task<HttpResponseMessage>> responder)
        : HttpMessageHandler
    {
        public StubHandler(Func<HttpRequestMessage, HttpResponseMessage> sync)
            : this(request => Task.FromResult(sync(request)))
        {
        }

        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,
            CancellationToken cancellationToken)
        {
            return responder(request);
        }
    }
}