using RedShirt.Example.Api.Common.Analyzers.Database.Abstractions.Attributes;
using RedShirt.Example.Api.DataStores.Constants;
using RedShirt.Example.Api.DataStores.Order.Models.Generated;
using System.Reflection;

namespace RedShirt.Example.Api.DataStores.Order.UnitTests.Tests.Entities;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class OrderEntityTests
{
    [Fact]
    public void OrderEntity_HasExpectedTableMetadata()
    {
        var attribute = typeof(OrderEntity).GetCustomAttribute<DbTableAttribute>();

        Assert.NotNull(attribute);
        Assert.Equal("Order", attribute!.TableName);
        Assert.Equal(DatabaseConstants.PrimaryDatabaseConnectionStringName, attribute.ConnectionStringName);
    }

    [Fact]
    public void OrderEntity_MarksKeyAndTimestamps()
    {
        Assert.NotNull(typeof(OrderEntity).GetProperty(nameof(OrderEntity.Id))!
            .GetCustomAttribute<DbKeyAttribute>());
        Assert.NotNull(typeof(OrderEntity).GetProperty(nameof(OrderEntity.CreatedAtUtc))!
            .GetCustomAttribute<CreatedAtPropertyAttribute>());
        Assert.NotNull(typeof(OrderEntity).GetProperty(nameof(OrderEntity.UpdatedAtUtc))!
            .GetCustomAttribute<UpdatedAtPropertyAttribute>());
    }

    [Fact]
    public void OrderEntity_StoresDecimalFieldsAsDecimal()
    {
        Assert.Equal(typeof(decimal), typeof(OrderEntity).GetProperty(nameof(OrderEntity.TotalAmount))!.PropertyType);
        Assert.Equal(typeof(decimal?), typeof(OrderEntity).GetProperty(nameof(OrderEntity.TotalPrice))!.PropertyType);
    }
}