using Moq;
using RedShirt.Example.Api.Connectors.Common.Http.Enums;
using RedShirt.Example.Api.Connectors.Common.Http.Models;
using RedShirt.Example.Api.Connectors.Common.Http.Services;

namespace RedShirt.Example.Api.Connectors.Common.Http.UnitTests.Tests.Services;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class OAuthTokenCacheTests
{
    private static OAuthClientCredentialsRequest Request(string audience = "https://api.example")
    {
        return new OAuthClientCredentialsRequest
        {
            TokenUrl = "https://auth.example/oauth/token",
            ClientIdPath = "/oauth/client-id",
            ClientSecretPath = "/oauth/client-secret",
            ScopeLabel = "audience",
            ScopeValue = audience
        };
    }

    [Fact]
    public async Task GetAsync_ForceFreshCredentials_MarksForcedCredentialRetrieval()
    {
        var request = Request();
        var source = new Mock<IOAuthTokenSource>(MockBehavior.Strict);
        source
            .Setup(s => s.GetTokenAsync(request, true, It.IsAny<CancellationToken>()))
            .ReturnsAsync(new OAuthTokenResponse
            {
                AccessToken = "tok-forced",
                ExpiresAtUtc = DateTimeOffset.UtcNow.AddHours(1)
            });

        var cache = new OAuthTokenCache(source.Object);

        var result = await cache.GetAsync(request, false, true, TestContext.Current.CancellationToken);

        Assert.Equal("tok-forced", result.AccessToken);
        Assert.Equal(TokenCacheState.ForcedCredentialRetrieval, result.TokenCacheState);
        source.Verify(s => s.GetTokenAsync(request, true, It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task GetAsync_ForceFreshToken_BypassesCache()
    {
        var request = Request();
        var source = new Mock<IOAuthTokenSource>(MockBehavior.Strict);
        source
            .SetupSequence(s => s.GetTokenAsync(request, false, It.IsAny<CancellationToken>()))
            .ReturnsAsync(new OAuthTokenResponse
            {
                AccessToken = "tok-1",
                ExpiresAtUtc = DateTimeOffset.UtcNow.AddHours(1)
            })
            .ReturnsAsync(new OAuthTokenResponse
            {
                AccessToken = "tok-2",
                ExpiresAtUtc = DateTimeOffset.UtcNow.AddHours(1)
            });

        var cache = new OAuthTokenCache(source.Object);

        _ = await cache.GetAsync(request, false, false, TestContext.Current.CancellationToken);
        var forced = await cache.GetAsync(request, true, false, TestContext.Current.CancellationToken);

        Assert.Equal("tok-2", forced.AccessToken);
        Assert.Equal(TokenCacheState.FreshToken, forced.TokenCacheState);
        source.Verify(s => s.GetTokenAsync(request, false, It.IsAny<CancellationToken>()), Times.Exactly(2));
    }

    [Fact]
    public async Task GetAsync_ReturnsCachedToken_WhenStillValid()
    {
        var request = Request();
        var source = new Mock<IOAuthTokenSource>(MockBehavior.Strict);
        source
            .Setup(s => s.GetTokenAsync(request, false, It.IsAny<CancellationToken>()))
            .ReturnsAsync(new OAuthTokenResponse
            {
                AccessToken = "tok-1",
                ExpiresAtUtc = DateTimeOffset.UtcNow.AddHours(1)
            });

        var cache = new OAuthTokenCache(source.Object);

        var first = await cache.GetAsync(request, false, false, TestContext.Current.CancellationToken);
        var second = await cache.GetAsync(request, false, false, TestContext.Current.CancellationToken);

        Assert.Equal("tok-1", first.AccessToken);
        Assert.Equal(TokenCacheState.FreshToken, first.TokenCacheState);
        Assert.Equal("tok-1", second.AccessToken);
        Assert.Equal(TokenCacheState.CachedToken, second.TokenCacheState);
        source.Verify(s => s.GetTokenAsync(request, false, It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task GetAsync_ThrowsArgumentNull_WhenRequestIsNull()
    {
        var source = new Mock<IOAuthTokenSource>(MockBehavior.Strict);
        var cache = new OAuthTokenCache(source.Object);

        await Assert.ThrowsAsync<ArgumentNullException>(() =>
            cache.GetAsync(null!, false, false, TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task GetAsync_UsesSeparateCacheEntries_ForDifferentRequests()
    {
        var firstRequest = Request("aud-a");
        var secondRequest = Request("aud-b");
        var source = new Mock<IOAuthTokenSource>(MockBehavior.Strict);
        source
            .Setup(s => s.GetTokenAsync(firstRequest, false, It.IsAny<CancellationToken>()))
            .ReturnsAsync(new OAuthTokenResponse
            {
                AccessToken = "tok-a",
                ExpiresAtUtc = DateTimeOffset.UtcNow.AddHours(1)
            });
        source
            .Setup(s => s.GetTokenAsync(secondRequest, false, It.IsAny<CancellationToken>()))
            .ReturnsAsync(new OAuthTokenResponse
            {
                AccessToken = "tok-b",
                ExpiresAtUtc = DateTimeOffset.UtcNow.AddHours(1)
            });

        var cache = new OAuthTokenCache(source.Object);

        var a = await cache.GetAsync(firstRequest, false, false, TestContext.Current.CancellationToken);
        var b = await cache.GetAsync(secondRequest, false, false, TestContext.Current.CancellationToken);

        Assert.Equal("tok-a", a.AccessToken);
        Assert.Equal("tok-b", b.AccessToken);
        source.VerifyAll();
    }
}