using RedShirt.Example.Api.Core.UseCases.Product.Commands.Patch;

namespace RedShirt.Example.Api.Core.UnitTests.Tests.UseCases.Product.Commands.Patch;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class PatchProductCommandValidatorTests
{
    private readonly PatchProductCommandValidator _validator = new();

    [Fact]
    public async Task Validate_Fails_WhenPriceIsPresentButInvalid()
    {
        var result = await _validator.ValidateAsync(
            new PatchProductCommand(Guid.NewGuid(), null, null, "nope"),
            TestContext.Current.CancellationToken);

        Assert.False(result.IsValid);
        Assert.Contains(result.Errors,
            error => error.ErrorMessage == "'Price' must be a valid decimal number");
    }

    [Fact]
    public async Task Validate_Succeeds_WhenPriceIsOmitted()
    {
        var result = await _validator.ValidateAsync(
            new PatchProductCommand(Guid.NewGuid(), null, "Renamed", null),
            TestContext.Current.CancellationToken);

        Assert.True(result.IsValid);
    }
}