using Moq;
using RedShirt.Example.Api.Core.Cqrs;
using RedShirt.Example.Api.Core.UseCases.Product.Commands.Patch;
using RedShirt.Example.Api.DataStores.Product.Core.Models;
using RedShirt.Example.Api.DataStores.Product.Core.Services;

namespace RedShirt.Example.Api.Core.UnitTests.Tests.UseCases.Product.Commands.Patch;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class PatchProductCommandHandlerTests
{
    private static ProductInternalDto CreateInternalDto(Guid id, decimal price = 9.99m)
    {
        var created = DateTime.UtcNow.AddDays(-1);
        return new ProductInternalDto
        {
            Id = id,
            CreatedAtUtc = created,
            UpdatedAtUtc = created,
            Sku = "SKU-1",
            Name = "Widget",
            Price = price
        };
    }

    [Fact]
    public async Task Handle_MapsNullPrice_WhenNotProvided()
    {
        var id = Guid.NewGuid();
        ProductServicePatchRequest? capturedRequest = null;
        var productService = new Mock<IProductService>();
        productService
            .Setup(s => s.PatchAsync(It.IsAny<ProductServicePatchRequest>(), TestContext.Current.CancellationToken))
            .Callback<ProductServicePatchRequest, CancellationToken>((request, _) => capturedRequest = request)
            .ReturnsAsync(CreateInternalDto(id));
        var handler = new PatchProductCommandHandler(
            productService.Object,
            new Mock<ICoreRequestValidator>().Object);
        var command = new PatchProductCommand(id, null, "Renamed", null);

        await handler.Handle(command, TestContext.Current.CancellationToken);

        Assert.NotNull(capturedRequest);
        Assert.Null(capturedRequest!.Sku);
        Assert.Equal("Renamed", capturedRequest.Name);
        Assert.Null(capturedRequest.Price);
    }

    [Fact]
    public async Task Handle_MapsOptionalPrice_WhenProvided()
    {
        var id = Guid.NewGuid();
        ProductServicePatchRequest? capturedRequest = null;
        var productService = new Mock<IProductService>();
        productService
            .Setup(s => s.PatchAsync(It.IsAny<ProductServicePatchRequest>(), TestContext.Current.CancellationToken))
            .Callback<ProductServicePatchRequest, CancellationToken>((request, _) => capturedRequest = request)
            .ReturnsAsync(CreateInternalDto(id, 15.50m));
        var validator = new Mock<ICoreRequestValidator>();
        var handler = new PatchProductCommandHandler(productService.Object, validator.Object);
        var command = new PatchProductCommand(id, "SKU-2", null, "15.50");

        var result = await handler.Handle(command, TestContext.Current.CancellationToken);

        Assert.NotNull(capturedRequest);
        Assert.Equal(id, capturedRequest!.Id);
        Assert.Equal("SKU-2", capturedRequest.Sku);
        Assert.Null(capturedRequest.Name);
        Assert.Equal(15.50m, capturedRequest.Price);
        Assert.Equal("15.50", result.Price);
        validator.Verify(v => v.ValidateAsync(command, TestContext.Current.CancellationToken), Times.Once);
    }
}