using Microsoft.Extensions.Options;
using Moq;
using RedShirt.Api.Example.Connectors.Foo.Implementation.Clients;
using RedShirt.Api.Example.Connectors.Foo.Implementation.Factories;

namespace RedShirt.Api.Example.Connectors.Foo.Implementation.UnitTests.Tests.Factories;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class FooApiClientFactoryTests
{
    [Fact]
    public void CreateFooApiClient_UsesNamedHttpClient_AndConfiguredBaseUrl()
    {
        using var httpClient = new HttpClient();
        var httpClientFactory = new Mock<IHttpClientFactory>(MockBehavior.Strict);
        httpClientFactory
            .Setup(f => f.CreateClient(nameof(FooApiClient)))
            .Returns(httpClient);

        var sut = new FooApiClientFactory(
            httpClientFactory.Object,
            Options.Create(new FooApiClientFactory.ConfigurationModel
            {
                BaseUrl = "http://foo.example"
            }));

        var client = sut.CreateFooApiClient();

        Assert.IsType<FooApiClient>(client);
        httpClientFactory.Verify(f => f.CreateClient(nameof(FooApiClient)), Times.Once);
        httpClientFactory.VerifyNoOtherCalls();
    }
}