using Moq;
using RedShirt.Example.Api.Common.Shared.Core.Abstractions;
using RedShirt.Example.Api.Core.Exceptions;
using RedShirt.Example.Api.Core.Exceptions.Responses;
using RedShirt.Example.Api.Core.Models;
using RedShirt.Example.Api.Core.Repositories;
using RedShirt.Example.Api.Core.Services;
using RedShirt.Example.Api.Core.Services.Topics.ExampleItem;

namespace RedShirt.Example.Api.Core.UnitTests.Tests.Services.Topics.ExampleItem;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class ExampleItemServiceTests
{
    private static ExampleItemService CreateService(
        IExampleItemRepository? repository = null,
        ISubmissionIdempotencyService? idempotencyService = null)
    {
        return new ExampleItemService(
            repository ?? new Mock<IExampleItemRepository>().Object,
            idempotencyService ?? new Mock<ISubmissionIdempotencyService>().Object);
    }

    private static Mock<IAbstractedLock> CreateLock(bool isAcquired)
    {
        var lockHandle = new Mock<IAbstractedLock>();
        lockHandle.SetupGet(l => l.IsAcquired).Returns(isAcquired);
        return lockHandle;
    }

    [Fact]
    public async Task DeleteAsync_DelegatesToRepository()
    {
        var repository = new Mock<IExampleItemRepository>();
        repository
            .Setup(r => r.DeleteByName("widget", TestContext.Current.CancellationToken))
            .Returns(Task.CompletedTask);
        var service = CreateService(repository.Object);

        await service.DeleteAsync("widget", TestContext.Current.CancellationToken);

        repository.Verify(r => r.DeleteByName("widget", TestContext.Current.CancellationToken), Times.Once);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    public async Task DeleteAsync_ThrowsBadRequest_WhenNameIsMissing(string? name)
    {
        var service = CreateService();

        var exception = await Assert.ThrowsAsync<BadRequestException>(() =>
            service.DeleteAsync(name!, TestContext.Current.CancellationToken));

        Assert.Equal("Name is required", exception.Message);
    }

    [Fact]
    public async Task GetAsync_ReturnsRepositoryResult()
    {
        var expected = new ExampleItemModel {Name = "widget"};
        var repository = new Mock<IExampleItemRepository>();
        repository
            .Setup(r => r.GetByName("widget", TestContext.Current.CancellationToken))
            .ReturnsAsync(expected);
        var service = CreateService(repository.Object);

        var result = await service.GetAsync("widget", TestContext.Current.CancellationToken);

        Assert.Same(expected, result);
        repository.Verify(r => r.GetByName("widget", TestContext.Current.CancellationToken), Times.Once);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    public async Task GetAsync_ThrowsBadRequest_WhenNameIsMissing(string? name)
    {
        var service = CreateService();

        var exception = await Assert.ThrowsAsync<BadRequestException>(() =>
            service.GetAsync(name!, TestContext.Current.CancellationToken));

        Assert.Equal("Name is required", exception.Message);
    }

    [Fact]
    public async Task GetListAsync_ReturnsRepositoryResult()
    {
        var expected = new ExampleItemListModel
        {
            ContinuationToken = "next",
            Items = [new ExampleItemModel {Name = "a"}]
        };
        var repository = new Mock<IExampleItemRepository>();
        repository
            .Setup(r => r.GetListAsync("token", TestContext.Current.CancellationToken))
            .ReturnsAsync(expected);
        var service = CreateService(repository.Object);

        var result = await service.GetListAsync("token", TestContext.Current.CancellationToken);

        Assert.Same(expected, result);
        repository.Verify(r => r.GetListAsync("token", TestContext.Current.CancellationToken), Times.Once);
    }

    [Fact]
    public async Task PutAsync_PersistsCachesAndUnlocks_OnSuccess()
    {
        var repository = new Mock<IExampleItemRepository>();
        var lockHandle = CreateLock(true);
        var idempotency = new Mock<ISubmissionIdempotencyService>();
        idempotency
            .Setup(s => s.GetRecordAsync<ExampleItemModel>("idem-1", TestContext.Current.CancellationToken))
            .ReturnsAsync((ExampleItemModel?) null);
        idempotency
            .Setup(s => s.GetLockAsync("idem-1", TestContext.Current.CancellationToken))
            .ReturnsAsync(lockHandle.Object);
        repository
            .Setup(r => r.Put(It.IsAny<ExampleItemModel>(), TestContext.Current.CancellationToken))
            .Returns(Task.CompletedTask);
        idempotency
            .Setup(s => s.SetRecordAsync("idem-1", It.IsAny<ExampleItemModel>(),
                TestContext.Current.CancellationToken))
            .Returns(Task.CompletedTask);
        var service = CreateService(repository.Object, idempotency.Object);
        var model = new ExampleItemModel {Name = "widget"};

        var result = await service.PutAsync(model, "idem-1", TestContext.Current.CancellationToken);

        Assert.Same(model, result);
        repository.Verify(r => r.Put(model, TestContext.Current.CancellationToken), Times.Once);
        idempotency.Verify(
            s => s.SetRecordAsync("idem-1", model, TestContext.Current.CancellationToken),
            Times.Once);
        lockHandle.Verify(l => l.Unlock(), Times.Once);
    }

    [Fact]
    public async Task PutAsync_ReturnsCachedResponse_WithoutCallingRepositoryOrLock()
    {
        var cached = new ExampleItemModel {Name = "cached"};
        var repository = new Mock<IExampleItemRepository>();
        var idempotency = new Mock<ISubmissionIdempotencyService>();
        idempotency
            .Setup(s => s.GetRecordAsync<ExampleItemModel>("idem-1", TestContext.Current.CancellationToken))
            .ReturnsAsync(cached);
        var service = CreateService(repository.Object, idempotency.Object);
        var model = new ExampleItemModel {Name = "fresh"};

        var result = await service.PutAsync(model, "idem-1", TestContext.Current.CancellationToken);

        Assert.Same(cached, result);
        idempotency.Verify(
            s => s.GetRecordAsync<ExampleItemModel>("idem-1", TestContext.Current.CancellationToken),
            Times.Once);
        idempotency.Verify(
            s => s.GetLockAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()),
            Times.Never);
        repository.Verify(
            r => r.Put(It.IsAny<ExampleItemModel>(), It.IsAny<CancellationToken>()),
            Times.Never);
        idempotency.Verify(
            s => s.SetRecordAsync(It.IsAny<string>(), It.IsAny<ExampleItemModel>(), It.IsAny<CancellationToken>()),
            Times.Never);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    public async Task PutAsync_ThrowsBadRequest_WhenNameIsMissing_AfterLockIsAcquired(string? name)
    {
        var repository = new Mock<IExampleItemRepository>();
        var lockHandle = CreateLock(true);
        var idempotency = new Mock<ISubmissionIdempotencyService>();
        idempotency
            .Setup(s => s.GetRecordAsync<ExampleItemModel>("idem-1", TestContext.Current.CancellationToken))
            .ReturnsAsync((ExampleItemModel?) null);
        idempotency
            .Setup(s => s.GetLockAsync("idem-1", TestContext.Current.CancellationToken))
            .ReturnsAsync(lockHandle.Object);
        var service = CreateService(repository.Object, idempotency.Object);

        var exception = await Assert.ThrowsAsync<BadRequestException>(() =>
            service.PutAsync(new ExampleItemModel {Name = name!}, "idem-1",
                TestContext.Current.CancellationToken));

        Assert.Equal("Name is required", exception.Message);
        idempotency.Verify(s => s.GetLockAsync("idem-1", TestContext.Current.CancellationToken), Times.Once);
        repository.Verify(
            r => r.Put(It.IsAny<ExampleItemModel>(), It.IsAny<CancellationToken>()),
            Times.Never);
        idempotency.Verify(
            s => s.SetRecordAsync(It.IsAny<string>(), It.IsAny<ExampleItemModel>(), It.IsAny<CancellationToken>()),
            Times.Never);
        lockHandle.Verify(l => l.Unlock(), Times.Never);
    }

    [Fact]
    public async Task PutAsync_ThrowsIdempotentConcurrency_WhenLockIsNotAcquired()
    {
        var repository = new Mock<IExampleItemRepository>();
        var lockHandle = CreateLock(false);
        var idempotency = new Mock<ISubmissionIdempotencyService>();
        idempotency
            .Setup(s => s.GetRecordAsync<ExampleItemModel>("idem-1", TestContext.Current.CancellationToken))
            .ReturnsAsync((ExampleItemModel?) null);
        idempotency
            .Setup(s => s.GetLockAsync("idem-1", TestContext.Current.CancellationToken))
            .ReturnsAsync(lockHandle.Object);
        var service = CreateService(repository.Object, idempotency.Object);

        await Assert.ThrowsAsync<IdempotentConcurrencyException>(() =>
            service.PutAsync(new ExampleItemModel {Name = "widget"}, "idem-1",
                TestContext.Current.CancellationToken));

        idempotency.Verify(s => s.GetLockAsync("idem-1", TestContext.Current.CancellationToken), Times.Once);
        repository.Verify(
            r => r.Put(It.IsAny<ExampleItemModel>(), It.IsAny<CancellationToken>()),
            Times.Never);
        lockHandle.Verify(l => l.Unlock(), Times.Never);
    }
}