using Moq;
using RedShirt.Example.Api.Core.Exceptions.Responses;
using RedShirt.Example.Api.Core.Models;
using RedShirt.Example.Api.Core.Repositories;
using RedShirt.Example.Api.Core.Services;
using RedShirt.Example.Api.Core.Services.Topics.ExampleItem;

namespace RedShirt.Example.Api.Core.UnitTests.Tests.Services.Topics.ExampleItem;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class ExampleItemServiceTests
{
    private static ExampleItemService CreateService(
        IExampleItemRepository? repository = null,
        ISubmissionIdempotencyWrapperService? idempotencyWrapperService = null)
    {
        return new ExampleItemService(
            repository ?? new Mock<IExampleItemRepository>().Object,
            idempotencyWrapperService ?? CreateInvokingWrapper().Object);
    }

    private static Mock<ISubmissionIdempotencyWrapperService> CreateInvokingWrapper()
    {
        var wrapper = new Mock<ISubmissionIdempotencyWrapperService>();
        wrapper
            .Setup(w => w.RunIdempotentlyAsync(
                It.IsAny<string>(),
                It.IsAny<Func<Task<ExampleItemModel>>>(),
                It.IsAny<CancellationToken>()))
            .Returns((string _, Func<Task<ExampleItemModel>> callback, CancellationToken _) => callback());
        return wrapper;
    }

    [Fact]
    public async Task DeleteAsync_DelegatesToRepository()
    {
        var repository = new Mock<IExampleItemRepository>();
        repository
            .Setup(r => r.DeleteByName("widget", TestContext.Current.CancellationToken))
            .Returns(Task.CompletedTask);
        var service = CreateService(repository.Object);

        await service.DeleteAsync("widget", TestContext.Current.CancellationToken);

        repository.Verify(r => r.DeleteByName("widget", TestContext.Current.CancellationToken), Times.Once);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    public async Task DeleteAsync_ThrowsBadRequest_WhenNameIsMissing(string? name)
    {
        var service = CreateService();

        var exception = await Assert.ThrowsAsync<BadRequestException>(() =>
            service.DeleteAsync(name!, TestContext.Current.CancellationToken));

        Assert.Equal("Name is required", exception.Message);
    }

    [Fact]
    public async Task GetAsync_ReturnsRepositoryResult()
    {
        var expected = new ExampleItemModel {Name = "widget"};
        var repository = new Mock<IExampleItemRepository>();
        repository
            .Setup(r => r.GetByName("widget", TestContext.Current.CancellationToken))
            .ReturnsAsync(expected);
        var service = CreateService(repository.Object);

        var result = await service.GetAsync("widget", TestContext.Current.CancellationToken);

        Assert.Same(expected, result);
        repository.Verify(r => r.GetByName("widget", TestContext.Current.CancellationToken), Times.Once);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    public async Task GetAsync_ThrowsBadRequest_WhenNameIsMissing(string? name)
    {
        var service = CreateService();

        var exception = await Assert.ThrowsAsync<BadRequestException>(() =>
            service.GetAsync(name!, TestContext.Current.CancellationToken));

        Assert.Equal("Name is required", exception.Message);
    }

    [Fact]
    public async Task GetListAsync_ReturnsRepositoryResult()
    {
        var expected = new ExampleItemListModel
        {
            ContinuationToken = "next",
            Items = [new ExampleItemModel {Name = "a"}]
        };
        var repository = new Mock<IExampleItemRepository>();
        repository
            .Setup(r => r.GetListAsync("token", TestContext.Current.CancellationToken))
            .ReturnsAsync(expected);
        var service = CreateService(repository.Object);

        var result = await service.GetListAsync("token", TestContext.Current.CancellationToken);

        Assert.Same(expected, result);
        repository.Verify(r => r.GetListAsync("token", TestContext.Current.CancellationToken), Times.Once);
    }

    [Fact]
    public async Task PutAsync_ReturnsWrapperResult_WithoutCallingRepository_WhenCallbackIsSkipped()
    {
        var cached = new ExampleItemModel {Name = "cached"};
        var repository = new Mock<IExampleItemRepository>();
        var wrapper = new Mock<ISubmissionIdempotencyWrapperService>();
        wrapper
            .Setup(w => w.RunIdempotentlyAsync(
                "idem-1",
                It.IsAny<Func<Task<ExampleItemModel>>>(),
                TestContext.Current.CancellationToken))
            .ReturnsAsync(cached);
        var service = CreateService(repository.Object, wrapper.Object);

        var result = await service.PutAsync(new ExampleItemModel {Name = "fresh"}, "idem-1",
            TestContext.Current.CancellationToken);

        Assert.Same(cached, result);
        repository.Verify(
            r => r.Put(It.IsAny<ExampleItemModel>(), It.IsAny<CancellationToken>()),
            Times.Never);
    }

    [Fact]
    public async Task PutAsync_RunsThroughIdempotencyWrapper_AndPersistsOnSuccess()
    {
        var repository = new Mock<IExampleItemRepository>();
        repository
            .Setup(r => r.Put(It.IsAny<ExampleItemModel>(), TestContext.Current.CancellationToken))
            .Returns(Task.CompletedTask);
        var wrapper = CreateInvokingWrapper();
        var service = CreateService(repository.Object, wrapper.Object);
        var model = new ExampleItemModel {Name = "widget"};

        var result = await service.PutAsync(model, "idem-1", TestContext.Current.CancellationToken);

        Assert.Same(model, result);
        repository.Verify(r => r.Put(model, TestContext.Current.CancellationToken), Times.Once);
        wrapper.Verify(w => w.RunIdempotentlyAsync(
            "idem-1",
            It.IsAny<Func<Task<ExampleItemModel>>>(),
            TestContext.Current.CancellationToken), Times.Once);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    public async Task PutAsync_ThrowsBadRequest_WhenNameIsMissing(string? name)
    {
        var repository = new Mock<IExampleItemRepository>();
        var wrapper = CreateInvokingWrapper();
        var service = CreateService(repository.Object, wrapper.Object);

        var exception = await Assert.ThrowsAsync<BadRequestException>(() =>
            service.PutAsync(new ExampleItemModel {Name = name!}, "idem-1",
                TestContext.Current.CancellationToken));

        Assert.Equal("Name is required", exception.Message);
        repository.Verify(
            r => r.Put(It.IsAny<ExampleItemModel>(), It.IsAny<CancellationToken>()),
            Times.Never);
        wrapper.Verify(w => w.RunIdempotentlyAsync(
            "idem-1",
            It.IsAny<Func<Task<ExampleItemModel>>>(),
            TestContext.Current.CancellationToken), Times.Once);
    }
}