using RedShirt.Example.Api.Common.Shared.Core.Abstractions;
using RedShirt.Example.Api.Core.Exceptions;
using RedShirt.Example.Api.Core.Exceptions.Responses;
using RedShirt.Example.Api.Core.Models;
using RedShirt.Example.Api.Core.Repositories;
using RedShirt.Example.Api.Core.Services;
using RedShirt.Example.Api.Core.Services.Topics.ExampleItem;

namespace RedShirt.Example.Api.Core.UnitTests.Tests.Services.Topics.ExampleItem;

/// <summary>
/// Code generated by Cursor (Composer).
/// </summary>
public class ExampleItemServiceTests
{
    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    public async Task GetAsync_ThrowsBadRequest_WhenNameIsMissing(string? name)
    {
        var service = CreateService();

        var exception = await Assert.ThrowsAsync<BadRequestException>(() =>
            service.GetAsync(name!, TestContext.Current.CancellationToken));

        Assert.Equal("Name is required", exception.Message);
    }

    [Fact]
    public async Task GetAsync_ReturnsRepositoryResult()
    {
        var expected = new ExampleItemModel { Name = "widget" };
        var repository = new FakeExampleItemRepository { GetByNameResult = expected };
        var service = CreateService(repository);

        var result = await service.GetAsync("widget", TestContext.Current.CancellationToken);

        Assert.Same(expected, result);
        Assert.Equal("widget", repository.LastGetByName);
        Assert.Equal(TestContext.Current.CancellationToken, repository.LastGetByNameCancellationToken);
    }

    [Fact]
    public async Task GetListAsync_ReturnsRepositoryResult()
    {
        var expected = new ExampleItemListModel
        {
            ContinuationToken = "next",
            Items = [new ExampleItemModel { Name = "a" }]
        };
        var repository = new FakeExampleItemRepository { GetListResult = expected };
        var service = CreateService(repository);

        var result = await service.GetListAsync("token", TestContext.Current.CancellationToken);

        Assert.Same(expected, result);
        Assert.Equal("token", repository.LastContinuationToken);
        Assert.Equal(TestContext.Current.CancellationToken, repository.LastGetListCancellationToken);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    public async Task DeleteAsync_ThrowsBadRequest_WhenNameIsMissing(string? name)
    {
        var service = CreateService();

        var exception = await Assert.ThrowsAsync<BadRequestException>(() =>
            service.DeleteAsync(name!, TestContext.Current.CancellationToken));

        Assert.Equal("Name is required", exception.Message);
    }

    [Fact]
    public async Task DeleteAsync_DelegatesToRepository()
    {
        var repository = new FakeExampleItemRepository();
        var service = CreateService(repository);

        await service.DeleteAsync("widget", TestContext.Current.CancellationToken);

        Assert.Equal("widget", repository.LastDeleteByName);
        Assert.Equal(TestContext.Current.CancellationToken, repository.LastDeleteCancellationToken);
    }

    [Fact]
    public async Task PutAsync_ReturnsCachedResponse_WithoutCallingRepositoryOrLock()
    {
        var cached = new ExampleItemModel { Name = "cached" };
        var repository = new FakeExampleItemRepository();
        var idempotency = new FakeSubmissionIdempotencyService
        {
            GetRecordResult = cached
        };
        var service = CreateService(repository, idempotency);
        var model = new ExampleItemModel { Name = "fresh" };

        var result = await service.PutAsync(model, "idem-1", TestContext.Current.CancellationToken);

        Assert.Same(cached, result);
        Assert.Equal("idem-1", idempotency.LastGetRecordKey);
        Assert.False(idempotency.GetLockCalled);
        Assert.False(repository.PutCalled);
        Assert.False(idempotency.SetRecordCalled);
    }

    [Fact]
    public async Task PutAsync_ThrowsIdempotentConcurrency_WhenLockIsNotAcquired()
    {
        var repository = new FakeExampleItemRepository();
        var lockHandle = new FakeLock(false);
        var idempotency = new FakeSubmissionIdempotencyService
        {
            GetRecordResult = null,
            LockToReturn = lockHandle
        };
        var service = CreateService(repository, idempotency);

        await Assert.ThrowsAsync<IdempotentConcurrencyException>(() =>
            service.PutAsync(new ExampleItemModel { Name = "widget" }, "idem-1",
                TestContext.Current.CancellationToken));

        Assert.True(idempotency.GetLockCalled);
        Assert.Equal("idem-1", idempotency.LastGetLockKey);
        Assert.False(repository.PutCalled);
        Assert.False(lockHandle.UnlockCalled);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    public async Task PutAsync_ThrowsBadRequest_WhenNameIsMissing_AfterLockIsAcquired(string? name)
    {
        var repository = new FakeExampleItemRepository();
        var lockHandle = new FakeLock(true);
        var idempotency = new FakeSubmissionIdempotencyService
        {
            LockToReturn = lockHandle
        };
        var service = CreateService(repository, idempotency);

        var exception = await Assert.ThrowsAsync<BadRequestException>(() =>
            service.PutAsync(new ExampleItemModel { Name = name! }, "idem-1",
                TestContext.Current.CancellationToken));

        Assert.Equal("Name is required", exception.Message);
        Assert.True(idempotency.GetLockCalled);
        Assert.False(repository.PutCalled);
        Assert.False(idempotency.SetRecordCalled);
        Assert.False(lockHandle.UnlockCalled);
    }

    [Fact]
    public async Task PutAsync_PersistsCachesAndUnlocks_OnSuccess()
    {
        var repository = new FakeExampleItemRepository();
        var lockHandle = new FakeLock(true);
        var idempotency = new FakeSubmissionIdempotencyService
        {
            LockToReturn = lockHandle
        };
        var service = CreateService(repository, idempotency);
        var model = new ExampleItemModel { Name = "widget" };

        var result = await service.PutAsync(model, "idem-1", TestContext.Current.CancellationToken);

        Assert.Same(model, result);
        Assert.Same(model, repository.LastPutModel);
        Assert.Equal(TestContext.Current.CancellationToken, repository.LastPutCancellationToken);
        Assert.Equal("idem-1", idempotency.LastSetRecordKey);
        Assert.Same(model, idempotency.LastSetRecordValue);
        Assert.True(lockHandle.UnlockCalled);
    }

    private static ExampleItemService CreateService(
        IExampleItemRepository? repository = null,
        ISubmissionIdempotencyService? idempotencyService = null)
    {
        return new ExampleItemService(
            repository ?? new FakeExampleItemRepository(),
            idempotencyService ?? new FakeSubmissionIdempotencyService());
    }

    private sealed class FakeExampleItemRepository : IExampleItemRepository
    {
        public ExampleItemModel GetByNameResult { get; init; } = new() { Name = "default" };
        public ExampleItemListModel GetListResult { get; init; } = new()
        {
            ContinuationToken = null,
            Items = []
        };

        public string? LastGetByName { get; private set; }
        public CancellationToken LastGetByNameCancellationToken { get; private set; }
        public string? LastContinuationToken { get; private set; }
        public CancellationToken LastGetListCancellationToken { get; private set; }
        public string? LastDeleteByName { get; private set; }
        public CancellationToken LastDeleteCancellationToken { get; private set; }
        public ExampleItemModel? LastPutModel { get; private set; }
        public CancellationToken LastPutCancellationToken { get; private set; }
        public bool PutCalled { get; private set; }

        public Task DeleteByName(string name, CancellationToken cancellationToken = default)
        {
            LastDeleteByName = name;
            LastDeleteCancellationToken = cancellationToken;
            return Task.CompletedTask;
        }

        public Task<ExampleItemModel> GetByName(string name, CancellationToken cancellationToken = default)
        {
            LastGetByName = name;
            LastGetByNameCancellationToken = cancellationToken;
            return Task.FromResult(GetByNameResult);
        }

        public Task<ExampleItemListModel> GetListAsync(string? continuationToken,
            CancellationToken cancellationToken = default)
        {
            LastContinuationToken = continuationToken;
            LastGetListCancellationToken = cancellationToken;
            return Task.FromResult(GetListResult);
        }

        public Task Put(ExampleItemModel model, CancellationToken cancellationToken = default)
        {
            PutCalled = true;
            LastPutModel = model;
            LastPutCancellationToken = cancellationToken;
            return Task.CompletedTask;
        }
    }

    private sealed class FakeSubmissionIdempotencyService : ISubmissionIdempotencyService
    {
        public object? GetRecordResult { get; init; }
        public IAbstractedLock LockToReturn { get; init; } = new FakeLock(true);

        public string? LastGetRecordKey { get; private set; }
        public string? LastGetLockKey { get; private set; }
        public string? LastSetRecordKey { get; private set; }
        public object? LastSetRecordValue { get; private set; }
        public bool GetLockCalled { get; private set; }
        public bool SetRecordCalled { get; private set; }

        public Task<IAbstractedLock> GetLockAsync(string key, CancellationToken cancellationToken = default)
        {
            GetLockCalled = true;
            LastGetLockKey = key;
            return Task.FromResult(LockToReturn);
        }

        public Task<T?> GetRecordAsync<T>(string key, CancellationToken cancellationToken = default)
        {
            LastGetRecordKey = key;
            return Task.FromResult(GetRecordResult is T typed ? typed : default);
        }

        public Task SetRecordAsync<T>(string key, T value, CancellationToken cancellationToken = default)
        {
            SetRecordCalled = true;
            LastSetRecordKey = key;
            LastSetRecordValue = value;
            return Task.CompletedTask;
        }
    }

    private sealed class FakeLock(bool isAcquired) : IAbstractedLock
    {
        public bool IsAcquired { get; } = isAcquired;
        public bool UnlockCalled { get; private set; }

        public void Unlock()
        {
            UnlockCalled = true;
        }
    }
}
