using Moq;
using RedShirt.Api.Example.Connectors.Foo.Core.Models;
using RedShirt.Api.Example.Connectors.Foo.Core.Services;

namespace RedShirt.Api.Example.Connectors.Foo.Core.UnitTests.Tests.Services;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class IFooConnectorContractTests
{
    [Fact]
    public async Task IFooConnector_CanBeMockedForCreateAndGet()
    {
        var createResponse = new CreateFooConnectorResponse {Id = 1, Name = "alpha"};
        var getResponse = new GetFooConnectorResponse {Id = 1, Name = "alpha"};

        var connector = new Mock<IFooConnector>(MockBehavior.Strict);
        connector
            .Setup(c => c.CreateAsync(
                It.Is<CreateFooConnectorRequest>(r => r.Name == "alpha"),
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(createResponse);
        connector
            .Setup(c => c.GetByIdAsync(1, It.IsAny<CancellationToken>()))
            .ReturnsAsync(getResponse);

        var created = await connector.Object.CreateAsync(
            new CreateFooConnectorRequest {Name = "alpha"},
            TestContext.Current.CancellationToken);
        var fetched = await connector.Object.GetByIdAsync(1, TestContext.Current.CancellationToken);

        Assert.Same(createResponse, created);
        Assert.Same(getResponse, fetched);
        connector.VerifyAll();
    }

    [Fact]
    public void IFooConnector_ExposesExpectedOperations()
    {
        var methods = typeof(IFooConnector)
            .GetMethods()
            .Select(m => m.Name)
            .OrderBy(n => n)
            .ToArray();

        Assert.Equal(["CreateAsync", "GetByIdAsync"], methods);
    }

    [Fact]
    public void RequestAndResponseModels_CanBeConstructed()
    {
        var createRequest = new CreateFooConnectorRequest {Name = "widget"};
        var createResponse = new CreateFooConnectorResponse {Id = 7, Name = "widget"};
        var getResponse = new GetFooConnectorResponse {Id = 7, Name = "widget"};

        Assert.Equal("widget", createRequest.Name);
        Assert.Equal(7, createResponse.Id);
        Assert.Equal("widget", createResponse.Name);
        Assert.Equal(7, getResponse.Id);
        Assert.Equal("widget", getResponse.Name);
    }
}