using Moq;
using RedShirt.Example.Api.Core.Cqrs;
using RedShirt.Example.Api.Core.UseCases.ExampleItem.Models;
using RedShirt.Example.Api.Core.UseCases.ExampleItem.Queries.GetRecord;
using RedShirt.Example.Api.Core.UseCases.ExampleItem.Services;

namespace RedShirt.Example.Api.Core.UnitTests.Tests.UseCases.ExampleItem.Queries.GetRecord;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class GetExampleItemRecordQueryHandlerTests
{
    [Fact]
    public async Task Handle_ReturnsRepositoryResult()
    {
        var expected = new ExampleItemModel {Name = "widget"};
        var repository = new Mock<IExampleItemRepository>();
        repository
            .Setup(r => r.GetByName("widget", TestContext.Current.CancellationToken))
            .ReturnsAsync(expected);
        var handler = new GetExampleItemRecordQueryHandler(
            repository.Object,
            new Mock<ICoreRequestValidator>().Object);

        var result = await handler.Handle(
            new GetExampleItemRecordQuery("widget"),
            TestContext.Current.CancellationToken);

        Assert.Same(expected, result);
        repository.Verify(r => r.GetByName("widget", TestContext.Current.CancellationToken), Times.Once);
    }
}