using RedShirt.Example.Api.Core.UseCases.ExampleItem.Queries.GetRecord;

namespace RedShirt.Example.Api.Core.UnitTests.Tests.UseCases.ExampleItem.Queries.GetRecord;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class GetExampleItemRecordQueryValidatorTests
{
    private readonly GetExampleItemRecordQueryValidator _validator = new();

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    public async Task Validate_Fails_WhenNameIsMissing(string? name)
    {
        var result = await _validator.ValidateAsync(
            new GetExampleItemRecordQuery(name!),
            TestContext.Current.CancellationToken);

        Assert.False(result.IsValid);
        Assert.Contains(result.Errors, error => error.ErrorMessage == "Name is required");
    }

    [Fact]
    public async Task Validate_Succeeds_WhenNameIsPresent()
    {
        var result = await _validator.ValidateAsync(
            new GetExampleItemRecordQuery("widget"),
            TestContext.Current.CancellationToken);

        Assert.True(result.IsValid);
    }
}