using RedShirt.Api.Example.Connectors.Bar.Core.Exceptions;

namespace RedShirt.Api.Example.Connectors.Bar.Core.UnitTests.Tests.Exceptions;

/// <summary>
///     Code generated by Cursor (Composer).
/// </summary>
public class BarExceptionTests
{
    [Fact]
    public void BarConnectorException_MessageOnlyConstructor_SetsMessage()
    {
        var exception = new BarConnectorException("classified failure")
        {
            IsHandled = false,
            CouldBeTransient = true,
            CouldBeExternallySolvable = false
        };

        Assert.Equal("classified failure", exception.Message);
        Assert.Null(exception.InnerException);
    }

    [Fact]
    public void BarConnectorException_PreservesInnerExceptionAndFlags()
    {
        var inner = new InvalidOperationException("upstream failed");
        var exception = new BarConnectorException(inner)
        {
            IsHandled = true,
            CouldBeTransient = false,
            CouldBeExternallySolvable = true
        };

        Assert.Same(inner, exception.InnerException);
        Assert.Equal(inner.Message, exception.Message);
        Assert.True(exception.IsHandled);
        Assert.False(exception.CouldBeTransient);
        Assert.True(exception.CouldBeExternallySolvable);
    }

    [Fact]
    public void BarRecordNotFoundException_CapturesIdAndMessage()
    {
        var exception = new BarRecordNotFoundException(42);

        Assert.Equal(42, exception.Id);
        Assert.Equal("Bar record 42 was not found.", exception.Message);
    }
}
